### ISSUE TITLE
--regress switch

### ISSUE THREAD

**Issue by dominicraf** [rdiff-backup/rdiff-backup#10]
Enhancement request. While --check-destination-dir regresses a damaged archive, there is no official way to regress an undamaged archive. I have written [rdiff-backup-regress.sh](http://www.timedicer.co.uk/programs/help/rdiff-backup-regress.sh.php) which does this but in an unofficial way. There are legitimate reasons why one might want to regress an undamaged archive (including wishing to reverse the bloating that can happen when some large data gets unintentionally included in a new backup session). 

At its simplest this could be a --regress switch which does what --check-destination-dir does but without first requiring that there be more than one current_mirror file. If this doesn't break anything...

**Comment by frankcrawford** [comment]
@ericzolf while I can understand adding this is not a top priority for adding into rdiff-backup, it would be worth including @dominicraf rdiff-backup-regress.sh script in the tools directory or somewhere else, or at least adding a note in one documentation about it's existence

What do you think?

**Comment by ericzolf** [comment]
I think, good idea. Can you take care?

I'd suggest at the same time to move `misc` to `tools/helpers` and put the script in there. Make sure it has a small explanation header.
