### ISSUE TITLE
Backup files not saved with original user

### ISSUE THREAD

**Issue by ClodoaldoPinto** [rdiff-backup/rdiff-backup#1002]
I'm using `rdiff-backup` to backup from local filesystems to a remote Hetzner server with a mounted remote storage box. The storage box is mounted on the remote server as a `cifs` filesystem. The backup is run locally as root and the `ssh` connection to the remote server is also on root account. The problem I have is that the original files owner/group are not preserved. Everything gets owned by root.

This is how the storage box is mounted in `/etc/fstab`:
```
//user.your-storagebox.de/backup /storagebox cifs iocharset=utf8,rw,credentials=/etc/backup-credentials.txt,seal,uid=0,gid=0,file_mode=0660,dir_mode=0770 0 0
```
And the local command to backup:
```
rdiff-backup -v4 --api-version 201 backup --print-statistics \
    --include /home/cpn/Documents \
    --include /home/cpn/ProgramasRFB \
    --include /home/cpn/Pictures \
    --include /home/cpn/Videos \
    --include /hd2t/Fotos \
    --include /hd2t/Videos \
    --include /etc \
    --exclude '**' \
    / root@example.com::/storagebox/Backup/ & disown;
```
In instead of the files/directories be owned by the original user they all get owned by root in the storage box:
```
# ll
total 0
drwxrwx---. 2 root root 0 May 14 16:58 Documents
drwxrwx---. 2 root root 0 May  1 09:23 Pictures
```
What am I missing? My guess is that the problem is related to `cifs`

**Comment by ericzolf** [comment]
This is also my understanding that CIFS doesn't support chown, so that everything is saved with the rights of the calling process. This said, it's not too bad because rdiff-backup saves the access rights and restores them.

**Comment by ericzolf** [comment]
OK, closing, simply reopen if you have more questions.
