### ISSUE TITLE
[BUG] "OSError: [Errno 36] File name too long"

### ISSUE THREAD

**Issue by schymans** [rdiff-backup/rdiff-backup#1005]
## Bug summary

Backup corrupted due to recursive folders written into backup. Now getting "OSError: [Errno 36] File name too long". The error should have occurred before writing file into backup.

## Version, Python, Operating System

Call `rdiff-backup info` and replace the following line with the output,
repeat for each environment impacted, especially if using remote operations:
This command yields: `Fatal Error: Switches missing or wrong number of arguments`, but my version is 2.0.5-2rogress5 on Progress Linux 5.99 (engywuck-backports) with Python Python 2.7.16 (installed) and 3.10.13 as default on the command line (through conda).

```yaml
<REPLACE THIS LINE - version info>
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
sudo rdiff-backup --no-fsync --tempdir ~/rubbish --print-statistics --exclude ~/.gvfs --exclude ~/.cache --exclude '**'/tmp --exclude '**'/temp --exclude '**'/rubbish --exclude '**'/Trash  --exclude ~/Programs --exclude ~/Downloads --exclude ~/Music --exclude ~/polybox --exclude ~/'VirtualBox*' --exclude ~/.local/share/data/'Mendeley*' --exclude ~/.recoll --exclude ~/miniconda3 --terminal-verbosity 5 ~/ /media/[snip]/rdiff_backup/
```

## What happened and what did you expect?
Failure with error:
```
OSError: [Errno 36] File name too long: b'/media/[snip]/rdiff_backup/rdiff-backup-data/increments/.icedove/[snip].default/webaccountMail/outlook.office365-2.com/Conversation History.sbd/Conversation History.sbd/[...]
```
Normally, this backup just runs through and reports the outcomes: ...Errors: 0
I found the recursive folders in my Thunderbird profile, deleted the folder, but the error still persists, as it has already been written to the backup previously. The error should have prevented rdiff-backup from writing such a long path into the backup in the first place.

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.
```
[...]
Previous backup seems to have failed, regressing destination now.
Exception '[Errno 36] File name too long: b'/media/rdiff_backup/rdiff-backup-data/increments/.icedove/[snip].default/webaccountMail/outlook.office365-2.com/Conversation History.sbd/Conversation History.sbd/[...]
[...]raised of class '<class 'OSError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
[...]
Backup: escape_dos_devices = 0
Backup: escape_trailing_spaces = 0
Regressing to Mon Mar 25 23:07:14 2024
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
[...]
OSError: [Errno 36] File name too long: b'/media/[snip]/rdiff_backup/rdiff-backup-data/increments/.icedove/[snip].default/webaccountMail/outlook.office365-2.com/Conversation History.sbd/Conversation History.sbd/[...]
```

**Comment by ericzolf** [comment]
I forgot: it would be interesting to get an extract of the logs (backup.log resp. error_... in the repository under rdiff-backup-data):

1. when the culprit was added to the repository for the first time (did it make the backup fail?)
2. when the error appeared for the first time

**Comment by ericzolf** [comment]
OK, closing, please re-open if needed.

**Comment by schymans** [comment]
@ericzolf Thanks again for looking into this. So, the recursive directories appeared only after the last successful backup in March. Here are the last lines of backup.log:
```
--------------[ Session statistics ]--------------
StartTime 1709747460.00 (Wed Mar  6 18:51:00 2024)
EndTime 1709749196.28 (Wed Mar  6 19:19:56 2024)
ElapsedTime 1736.28 (28 minutes 56.28 seconds)
SourceFiles 1742623
SourceFileSize 779265126344 (726 GB)
MirrorFiles 1438091
MirrorFileSize 763991774004 (712 GB)
NewFiles 317278
NewFileSize 18142472738 (16.9 GB)
DeletedFiles 12746
DeletedFileSize 2402147304 (2.24 GB)
ChangedFiles 8943
ChangedSourceSize 10454729804 (9.74 GB)
ChangedMirrorSize 10921702898 (10.2 GB)
IncrementFiles 338971
IncrementFileSize 3190884722 (2.97 GB)
TotalDestinationSizeChange 18464237062 (17.2 GB)
Errors 0
--------------------------------------------------

--------------[ Session statistics ]--------------
StartTime 1711404434.00 (Mon Mar 25 23:07:14 2024)
EndTime 1711405980.85 (Mon Mar 25 23:33:00 2024)
ElapsedTime 1546.85 (25 minutes 46.85 seconds)
SourceFiles 1708066
SourceFileSize 788533056125 (734 GB)
MirrorFiles 1742623
MirrorFileSize 779265126344 (726 GB)
NewFiles 13796
NewFileSize 9631444242 (8.97 GB)
DeletedFiles 48353
DeletedFileSize 4267785638 (3.97 GB)
ChangedFiles 6549
ChangedSourceSize 10396981218 (9.68 GB)
ChangedMirrorSize 6492710041 (6.05 GB)
IncrementFiles 68705
IncrementFileSize 2418973320 (2.25 GB)
TotalDestinationSizeChange 11686903101 (10.9 GB)
Errors 0
--------------------------------------------------

Previous backup seems to have failed, regressing destination now.
Previous backup seems to have failed, regressing destination now.
Previous backup seems to have failed, regressing destination now.
2024-05-24 09:17:48.501667 +0200  <CLIENT-1587302>  Previous backup seems to have failed, regressing destination now.
2024-05-24 09:17:48.505326 +0200  <CLIENT-1587302>  Regressing to Mon Mar 25 23:07:14 2024
Previous backup seems to have failed, regressing destination now.
```
The last error_log, file_statistics, increments and mirror_metadata files all refer to 2024-03-25, nothing later. And yet, for some reason, the folder increments does contain the recursive folders.

I cannot use rdiff-backup-delete, as I get:
```fail to acquired repository lock. A backup may be running.```
The solution for this would be to regress the repo, but I cannot do this for the original reason... :-(

**Comment by schymans** [comment]
@ericzolf I don't know how to re-open the ticket, but unless you are interested to follow up on this recursive folder problem, I will have to overwrite the backup with a fresh one to proceed, as I don't see a way of saving it. Please let me know in case you would like took into it before I overwrite.

**Comment by ericzolf** [comment]
I'm interested but I don't really have the time currently. Anyway, what I would need is information on how the file really looks like, what is it exactly, how is the recursion created, so that rdiff-backup doesn't detect it properly (long filenames have always been an issue under Windows)? Perhaps the lines around the place where this file has been backup-ed successfully could help.

**Comment by schymans** [comment]
Unfortunately, I have no idea how the recursion came about, but it is related to the Thunderbird add-on owl, and its connection to an outlook office365 account. This is the base pattern of the recursion:
```
$ sudo ls -l rdiff-backup/rdiff-backup-data/increments/.icedove/sd4p9p07.default/webaccountMail/outlook.office365-2.com/
total 4
drwx------ 3 root root 4096 May 23 22:33 'Conversation History.sbd'
-rw------- 1 root root    0 Apr 14 10:15 'Conversation History.sbd.2024-03-25T23:07:14+01:00.missing'
```
'Conversation History.sbd' is a folder with exactly the same contents.
Actually, the recursion only occurs in increments, not in the backup itself:
```
sudo ls -l rdiff_backup/.icedove/sd4p9p07.default/webaccountMail/outlook.office365-2.com/
total 4
drwx------ 3 root root 4096 May 23 22:33 'Conversation History.sbd'
```
I wonder if the recursion was not created by rdiff-backup itself, perhaps because TB was writing to the file during the backup?

Is there a chance that I can still rescue the history of this backup drive, or should I just overwrite it all and create a new set of backups?

**Comment by schymans** [comment]
Hmmm, I removed the recursion from increments by hand, but the error message is still the same.
