### ISSUE TITLE
[?] Differnt backup levels to the same destination folder

### ISSUE THREAD

**Issue by T1MOXA** [rdiff-backup/rdiff-backup#1012]
## What is it about?

Can I make different backup levels to the same destination folder ?
For example, different exclude settings for full, and partial backups.
Full backups will be scheduled for every week, and partial backups every day.

## Version, Python, Operating System
system: Ubuntu 22.04.4
rdiff-backup 2.0.5
`rdiff-backup info` gives an error:
```
Fatal Error: Switches missing or wrong number of arguments
See the rdiff-backup manual page for more information.
```

## rdiff-backup call
```
# Full backup
rdiff-backup /backup/test_rdiff/src /backup/test_rdiff/dst
# Partial
rdiff-backup --exclude='**/folder3' /backup/test_rdiff/src /backup/test_rdiff/dst
```

And the second command (for partial backups) deletes folder3, but I wanted to just ignore it.

```
.
├── dst
│   ├── folder1
│   └── folder2
└── src
    ├── folder1
    ├── folder2
    └── folder3
```

**Comment by ikus060** [comment]
This is not possible at the moment. This feature is requested in #629
