### ISSUE TITLE
[?] pager

### ISSUE THREAD

**Issue by depesz** [rdiff-backup/rdiff-backup#1013]
## What is it about?

REPLACE THIS LINE - A clear and concise description of what the question or your need is

## Version, Python, Operating System

Call `rdiff-backup info` and replace the following line with the output,
repeat for each environment impacted, especially if using remote operations:

```yaml
<REPLACE THIS LINE - version info>
```

## rdiff-backup call

If you tried something already, how did you call rdiff-backup, with which parameters:

```
<REPLACE THIS LINE - parameters>
```

And what was the result?

```
<REPLACE THIS LINE - output>
```

**Comment by ericzolf** [comment]
Just reopen with the necessary information if you meant to ask for help.
