### ISSUE TITLE
[?] How to use the new syntax

### ISSUE THREAD

**Issue by yuppox** [rdiff-backup/rdiff-backup#1017]
## What is it about?

I have been using the "old" syntax and want to know how to use the new one. However, I don't see most of the options I use:

```
--no-acls
--no-eas
--ssh-no-compression
--print-statistics
--exclude
```

How do those translate to the new syntax?

## Version, Python, Operating System

```
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/local/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.6
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.9.2
system:
  fs_encoding: utf-8
  platform: Linux-5.10.0-9-amd64-x86_64-with-glibc2.31
...
```

## rdiff-backup call

If you tried something already, how did you call rdiff-backup, with which parameters:

```
See above
```

And what was the result?

```
N/A
```

**Comment by ikus060** [comment]
Hello @yuppox,

For questions like this, it might be better to use the mailing list.

Regarding your inquiry, the new syntax for rdiff-backup uses subcommands to define actions such as backup, restore, delete, etc. For example: `rdiff-backup [subcommand]`

All the options you're looking for are now part of the backup subcommand. You can see the full list of available options by running `rdiff-backup --help` and then `rdiff-backup [subcommand] --help`. For instance, `rdiff-backup backup --help` will give you the details for the backup command.

**Comment by yuppox** [comment]
Thanks! That helps.
