### ISSUE TITLE
Remote backup fails with truncated pickle data

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#115]
Testing rdiff-backup from latest git version with remote backup fails with an error of:

Sending back exception pickle data was truncated of type <class '_pickle.UnpicklingError'>

See traceback attached.
[backup.log](https://github.com/rdiff-backup/rdiff-backup/files/3563105/backup.log)

**Comment by ericzolf** [comment]
Sorry for the problem but can you please: re-run the command with verbosity 9 and send the command used as well as the output of `git describe --long --all`? There isn't enough information to understand the problem. We might have even to ask you to provide the file causing the issue, but let's see first what the more verbose output is saying.

**Comment by frankcrawford** [comment]
As always in computing, both requests are harder than it sounds, in that this is being run under a wrapper program called safekeep, and rdiff-backup is actually installed from an RPM built from a download from git master.
The RPM is rdiff-backup-1.3.4-0.20190829git56cfd72.fc30.x86_64, which was from master 56cfd72.
The command as listed in the attached typescript was (and seems to not have listed the appropriate quotes):
nice -n10 ionice -c3 -t rdiff-backup --remote-schema ssh -oStrictHostKeyChecking=ask -v -i /var/lib/safekeep/.ssh/safekeep-server-data-key %s rdiff-backup --server --exclude-sockets --exclude-fifos -v 9 --exclude /mnt/safekeep-23491-itdbvje5-rbind/dev/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/media/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/misc/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/mnt/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/net/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/proc/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/selinux/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/sys/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/run/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/tmp/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/var/cache --exclude /mnt/safekeep-23491-itdbvje5-rbind/var/lock --exclude /mnt/safekeep-23491-itdbvje5-rbind/var/run --exclude /mnt/safekeep-23491-itdbvje5-rbind/var/tmp --exclude /mnt/safekeep-23491-itdbvje5-rbind/var/spool/squid --exclude /mnt/safekeep-23491-itdbvje5-rbind/var/lib/nfs/rpc_pipefs/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/var/lib/imap/socket/ --exclude /mnt/safekeep-23491-itdbvje5-rbind/var/lib/mysql/mysql.sock --exclude /mnt/safekeep-23491-itdbvje5-rbind/srv/ --include /mnt/safekeep-23491-itdbvje5-rbind/ --exclude-regexp /mnt/safekeep-23491-itdbvje5-rbind.* root@safekeep-client.local::/mnt/safekeep-23491-itdbvje5-rbind /srv/archive/./safekeep-client/backup

[typescript.txt](https://github.com/rdiff-backup/rdiff-backup/files/3578982/typescript.txt)

**Comment by ericzolf** [comment]
OK, the good news is that my development and test system is also Fedora 30 so it should work. The bad news is that "true" remote work (i.e. via SSH) isn't being tested only simulated, so it's possible we missed something specific to SSH.

Another possibility is a discrepancy of libs between both systems. Do you have the same versions of rdiff-backup, Python and Linux on both sides (details please)? Nothing around Endianness differences?

**Comment by ericzolf** [comment]
And I forgot to ask: is the statement about the `Bad rdiff-backup-data dir on destination side` a consequence of the first failed run, or do you get this error also on the first run towards a new repository? Respectively was the directory created by an older version of rdiff-backup or a fresh one?

**Comment by frankcrawford** [comment]
Eric,
Actually both VMs are Fedora 29, not 30, although the rdiff-backup RPM is F30, as all my other systems are now F30.  Either way, they are identical, setup specifically for testing rdiff-backup and safekeep (FYI, I'm one of the package maintainers for rdiff-backup in Fedora).  I can upgrade to F30 if you want me to,  I'll probably recreate them shortly as F30 VMs, not I've noted they are a bit behind.

As for the bad rdiff-backup-data dir, I believe that is due to it being the initial run, as I cleared out the destination prior to running this.

Previously these systems have been running rdiff-backup 1.2.8 (standard Fedora RPM) without any issue.

**Comment by frankcrawford** [comment]
Sorry, a better explanation of the bad rdiff-backup-data dir is that the safekeep wrapper script automatically kicks off a clean up when the rdiff-backup fails, but as there has never been a successful backup completed, it does not have any valid data to roll backup to.

**Comment by ericzolf** [comment]
OK:

- good to hear that there is an active maintainer for the package, even if upstream has been inactive for many years! Happy to meet you.
- now that I know that the broken repository isn't the issue, I can concentrate on the actual issue.
- my first guess is that it's really the SSH transfer which doesn't work, let me try to reproduce the issue
- making sure that it's properly automatically tested will be more challenging, if it's indeed the issue...
- anyway, no need to upgrade anything for now...

**Comment by ericzolf** [comment]
I can reproduce the issue simply with `rdiff-backup -v 9 root@localhost::${BASEDIR}/rdiff-backup_testfiles /var/tmp/backup`, which means that the SSH approach is broken.

**Comment by ericzolf** [comment]
Some progress in here: the pickle incomplete issue is just a follow-up error. The actual error is a MemoryError happening before, interrupting the transmission, and hence the pickle data is incomplete.

The MemoryError itself is due to the length of the data being badly transmitted, and leading to an insanely high value (roughly 1536TB, no typo). As my laptop doesn't have that much memory, quite unsurprisingly, this leads to the memory error when `connection.py` tries to read this length in `_read()` (line 266). I'm already able to understand where the insane length comes from, but why it is garbled over SSH, and not when simulating, I'm still searching.

**Comment by ericzolf** [comment]
Hi Frank, can you please check that the PR #125 really fixes your issue? On my side, it solved the issue reliably but want to be sure it does for you as well before we merge. Thanks.

**Comment by frankcrawford** [comment]
Okay, I'll check over the weekend and let you know.

**Comment by frankcrawford** [comment]
Yes, this seems to fix the problem.  I didn't actually apply the patch, but update my copy to remove "bufsize=0" on both client and server and it now runs correctly through multiple tests.
