### ISSUE TITLE
Add a --port/-p option to change the default ssh port

### ISSUE THREAD

**Issue by hsicilia** [rdiff-backup/rdiff-backup#130]
Now the sintaxis we must use to change only the default port is complex: 
--remote-schema 'ssh -p PORT -C %s rdiff-backup --server'

I think it would be nice to have a -p (as ssh) or a -P (as scp).

**Comment by ericzolf** [comment]
We can look into it but not before we've fixed many other things, and especially introduced a more modern approach to command line parsing.

**Comment by ericzolf** [comment]
Reviewing all issues, I realize that you can simply use something like `rdiff-backup sourcedir ssh://targethost:1234::/backupdir`, probably worth adding as example to the docs, but it makes me think that we might not need an extra option and complexity in building the command.
