### ISSUE TITLE
Migrate to travis.com

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#145]
According to this announcement, we should be using travis.com instead of travis.org.

https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

**Comment by ollytom** [comment]
The [relevant documentation][1] from Travis CI has this to say about migrating existing open source projects to travis-ci.com:

> Open source projects and their build history will continue to run on travis-ci.org at this time.
>
> However, you can be included in the closed beta testing to start migrating your open source 
> repositories to travis-ci.com.

Perhaps it’s worth holding off until the service isn’t a closed beta? On the other hand, they advise
all new repositories (open source and private) to be activated on travis-ci.com straight away.

[1]: https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg

**Comment by ericzolf** [comment]
This is done.
