### ISSUE TITLE
rdiff-backup -l lists increment dirs as binary string

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#160]
This is a minor issue, but currently `rdiff-backup -l` lists the incremental dirs as binary string, e.g.

    [root@safekeep-server frank]# rdiff-backup -l /srv/archive/safekeep-server/backup/
    Found 1 increments:
        b'increments.2019-11-02T03:32:57+11:00.dir'   Sat Nov  2 03:32:57 2019
    Current mirror: Sat Nov  2 15:45:40 2019

Note the listing as binary string, i.e. `b'...'`

**Comment by ericzolf** [comment]
I'll look into it, probably no big deal.

**Comment by whataboutpereira** [comment]
I believe the same is happening here when taking a backup:

`b'UpdateError var/lib/pve-cluster/config.db-shm File changed from regular file before signature'`

**Comment by ericzolf** [comment]
Please don't add unrelated comments to an already closed issue, that makes it very difficult to track. Just create a new issue.

**Comment by whataboutpereira** [comment]
Alright, done it is. :)
