### ISSUE TITLE
Option remove-older-than should have ability to remove only sub-sets of repo history

### ISSUE THREAD

**Issue by janreges** [rdiff-backup/rdiff-backup#17]
Hi,

is in this GitHub repo included patch from "Josh Nisly" from this issue: http://savannah.nongnu.org/bugs/?25962 ?

And is there any plan to release next official version? Latest is 1.3.3. I'm a Gentoo user :)

Thank you very much. Is great, that you take next rdiff-backup development.

**Comment by mennojansz** [comment]
I'm also keen to see this patch included. Is there any plan for a next release?

**Comment by ottok** [comment]
Hello @janreges and mennojansz!

The code base has been rewritten for Python 3 and there will be no further releases for the 1.x series in Python 2 anymore. Could you please help out and test again with the latest development version (https://github.com/rdiff-backup/rdiff-backup#installing-the-latest-development-version) if you can still reproduce this?

With your help, the upcoming 2.0.0 release could be improved and this reported issue eventually solved in future 2.x releases.

**Comment by ericzolf** [comment]
I'd think that this is something we could do by using the include/exclude options, but I don't see it happen any time soon (the patch from Josh evoked seems to have vanished, and anyway I wouldn't want to do this before the code has been cleaned-up).

**Comment by ericzolf** [comment]
rdiff-backup-delete already answers part of the initial request (remove wrongly backed-up files). Do you really need more? IMHO a backup tool isn't an archiving tool, if you need something for a longer period of time, you should put it in a different place (an archive) and not play around with backup periods.

**Comment by ericzolf** [comment]
Closing as invalid, I don't think we need this kind of complexity, and as said, there is a difference between backup and archive.
