### ISSUE TITLE
delete the script tools/makerpm

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#175]
I haven't done anything more than a cursory look at this, but it is really just a wrapper around rpmbuild for the two spec files, in the form that one of the previous distributors used.

As we have killed off the other build files and we will never use this, I would suggest that makerpm should be deleted as well.

Comments?

**Comment by ericzolf** [comment]
Sounds like a plan to me. Where is the PR? :stuck_out_tongue_winking_eye:

**Comment by frankcrawford** [comment]
I'll generate one later today.

**Comment by frankcrawford** [comment]
Closed by PR #178
