### ISSUE TITLE
Some destination dirs tend to bloat

### ISSUE THREAD

**Issue by xHire** [rdiff-backup/rdiff-backup#19]
I have noticed that rdiff-backup is extremely bloaty with one of my destination dirs. To illustrate I ran `--increments-size` on two different ones:

#### the bloaty destination directory
**Size:** 765MB
**Cumulative size:** 877MB
**Number of increments:** 2139
**du -sh:** 11G

#### a different/normal destination directory
**Size:** 3.51GB
**Cumulative size:** 3.99GB
**Number of increments:** 6986
**du -sh:** 11G

So it makes something like 10 gigabytes for the rdiff-backup data which seems to me like a lot (well, the other one isn’t lean either, but at least it’s more proportional to the size of actual data). I suspect that there are files that don’t need to be there, but I failed to find out how to distinguish them. Also, `--check-destination-dir` didn’t do anything.

**Comment by marshallstokes** [comment]
I would assume `increment size` is a function of the variety of data you are backing up. For instance if you host some websites and decide to keep frequent incremental backups of all website source code stored in `/var/www` your increment size is likely to remain lean and consistent in its growth. However, imagine your websites see a decent amount of traffic and you frequently run backups of `/var/log/httpd` - odds of developing a case of "bloaty destination directory" likely pretty high.

Consider the data you are backing up and how frequently it changes and turns over. Even a single log file or temporary folder in your set may find there is a high turnover folder in your backup source. If you want to exclude a folder containing unneeded files like boated logs, the `--exclude` feature and related CLI options are brilliant for this exact use case.

**Comment by xHire** [comment]
Shouldn’t this be accounted for in the `increment size` number? I wouldn’t mind if the increments were huge, because I understand that those are my backed up data. What I was wondering is, why the cumulative size of all increments is lower by an order of a magnitude than the total size of `rdiff-backup-data/` directory where they are stored?

(Just by the way, the first example is a directory with my source codes, the second one of my e-mails stored in Maildir format (i.e., one file for each e-mail message – but even the old mailbox format was fine in terms of bloating (nonetheless, that was a separate rdiff-backup repository)). Both constitute almost a year of backups once per 30 minutes.)

**Comment by ericzolf** [comment]
With the explanations from marshallstokes, I think we can close this issue. Feel free to re-open it if you think that it's still an issue.
