### ISSUE TITLE
rdiff-backup-1.4.0b0-win64.exe --version answers DEV instead of 1.4.0b0

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#190]
This is quite certainly due to the usage of setuptools-scm to generate the version on the fly or fall back to DEV. The solution might be to also use setup.py to generate the binary on Windows with or without the pyinstaller plug-in.

**Comment by ericzolf** [comment]
Found this issue: https://github.com/pyinstaller/pyinstaller/issues/4180 so we're not alone.
The question is if we can find a workaround, as pyinstaller offers some ways to tweak the packaging, like --add-data --add-binary or even hooks.

**Comment by ericzolf** [comment]
Working on it now...

**Comment by ericzolf** [comment]
Crap, spoke too fast, Chocolatey is unusable... https://status.chocolatey.org/issues/2019-11-29-slow-and-intermittent-connection-issues/

@ardovm can you check in your build if it's sufficient to add `--add-data src/rdiff_backup.egg-info/PKG-INFO;rdiff_backup.egg-info/PKG-INFO` to pyinstaller call to solve the issue? Possibly everything under `src/rdiff_backup.egg-info/PKG-INFO` needs to be added, or PKG-INFO must be added to the root dir of the packaged exe, etc...

In the meantime I remove myself from this issue.

**Comment by ardovm** [comment]
@ericzolf,

> Crap, spoke too fast, Chocolatey is unusable... https://status.chocolatey.org/issues/2019-11-29-slow-and-intermittent-connection-issues/
> 
> @ardovm can you check in your build if it's sufficient to add `--add-data src/rdiff_backup.egg-info/PKG-INFO;rdiff_backup.egg-info/PKG-INFO` to pyinstaller call to solve the issue? Possibly everything under `src/rdiff_backup.egg-info/PKG-INFO` needs to be added, or PKG-INFO must be added to the root dir of the packaged exe, etc...

Yes, it is!

`--add-data=src/rdiff_backup.egg-info/PKG-INFO;rdiff_backup.egg-info`

I am going to fix my script. Thank you.

**Comment by ardovm** [comment]
FWIW on my Linux system (Python 3.6.9 x86_64) the displayed version is 0.1.dev1107+g58b0c3c instead.
The (working) Windows environment is Python 3.7.0 for win32.

**Comment by ericzolf** [comment]
From the look of it, you haven't pulled the latest tag v1.4.0.beta from git.

**Comment by ardovm** [comment]
> From the look of it, you haven't pulled the latest tag v1.4.0.beta from git.

Yes! You are right! I am sorry for the noise.
