### ISSUE TITLE
Merge back the website repo into the code repo under docs

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#215]
A lot of the documentation present on our site is duplicated with the documentation present under `docs`, which makes it difficult to keep in sync (it's already overall rather outdated). I've already prepared the basis for this move by creating an `index.md` as basis, and configuring the project site to appear under https://rdiff-backup.github.io/rdiff-backup/, but there is still more to be done:

1. decide if it's really the right approach
2. clarify why the theme selected https://github.com/pages-themes/tactile doesn't work as expected
3. generally make the result nicer looking
4. fix the documentation
5. move the documentation from the dedicated repo https://github.com/rdiff-backup/rdiff-backup.net into this repo
6. update the documentation to the new version of rdiff-backup

Some helpful links:
* https://help.github.com/en/github/working-with-github-pages for https://pages.github.com
* https://jekyllrb.com/docs/

@frankcrawford you've done already a good job on the documentation, do you want to work on this?

**Comment by frankcrawford** [comment]
@ericzolf Yes, I'll have a go at this, although it probably won't be until the end of the week before I can do much.

**Comment by ericzolf** [comment]
Cool, thanks. No hurry, we all have a private life.

**Comment by frankcrawford** [comment]
Been looking through this request in between other things, and it shouldn't be too hard.
I'd propose to move all the docs from rdiff-backup.net to md format and, similar to our other plans, and to eventually use the master branch /docs folder as the home for the website.
I'll see what I can do about it all this week, as it shouldn't be a lot of work.

**Comment by ericzolf** [comment]
> and to eventually use the master branch /docs folder as the home for the website.

This is already configured like this, even if the page is https://rdiff-backup.github.io/rdiff-backup/ and not https://rdiff-backup.net, but that's one option to change once the website works properly.

**Comment by frankcrawford** [comment]
Okay.  A minor problem is that I can't see the settings as I don't have write access to the repo, but I don't really want write access either.  I'm fine with the current permissions.
If those are the current settings, then it allows us to test against the github site before actual release.

**Comment by ericzolf** [comment]
Here the current settings, you probably should set-up your own repo the same way so that you can try your code more easily (without protecting the master branch):
![image](https://user-images.githubusercontent.com/3105685/71594840-bf401680-2b39-11ea-8883-81e1a39e6c59.png)

**Comment by frankcrawford** [comment]
Thanks.  I'll setup my clone with those options and get it working.  I see currently you don't have a theme set, but want to use tactile.

**Comment by ericzolf** [comment]
I actually selected the style tactile but perhaps I did it wrong. Tell me! 😄 (and if another style works better, we're not married with it).

**Comment by ericzolf** [comment]
OK, I know now the issue, I oversaw the error message as I selected the theme: "Unable to commit _config.yml to protected branch". 

So it seems the solution is to create the file yourself.

**Comment by frankcrawford** [comment]
Yeah, I was wondering about where that file was.  I was going to create it as part of this update.

**Comment by frankcrawford** [comment]
After playing around with this for a while the sites are pretty simple, although there are a few issues I have recently found.
If we set it up to automatically translate from markdown to HTML, then it ends up as HTML4, and some of our current md files don't translate correctly.
Secondly, a few of the files will really need to be HTMLised first, in particular the man pages.
Finally, we do need to look at which pages we do want to present, as the only automatically added links are zip and tarballs.

How do you want to proceed?

**Comment by ericzolf** [comment]
>  If we set it up to automatically translate from markdown to HTML, then it ends up as HTML4, and some of our current md files don't translate correctly.

We can re-shape them so that they work?

> Secondly, a few of the files will really need to be HTMLised first, in particular the man pages.

I had anyway the idea to generate also the manpages from markdown, it is theoretically possible, didn't try hard yet.

> Finally, we do need to look at which pages we do want to present, as the only automatically added links are zip and tarballs.

Not sure to understand this statement correctly: do you mean the bubbles at the top of the page?

**Comment by frankcrawford** [comment]
> > If we set it up to automatically translate from markdown to HTML, then it ends up as HTML4, and some of our current md files don't translate correctly.
> 
> We can re-shape them so that they work?

Maybe.  I've tried a few things and github's translator still gets it wrong.  I'll keep working on it to see what I can do.

> > Secondly, a few of the files will really need to be HTMLised first, in particular the man pages.
> 
> I had anyway the idea to generate also the manpages from markdown, it is theoretically possible, didn't try hard yet.

Unfortunately, every time I've tried to get markdown to translate to manpages, it looks to be a mess.  While they do conform to the man macros, when you look at the file they are a much more of a mess than you would expect.

I think it would be best to use something else to translate the manpages to HTML directly.

> > Finally, we do need to look at which pages we do want to present, as the only automatically added links are zip and tarballs.
> 
> Not sure to understand this statement correctly: do you mean the bubbles at the top of the page?

Yes, the bubbles a the top of the page.

**Comment by ericzolf** [comment]
I see that `groff`, which should be available on all Linux systems, can export (X)HTML, I'd start with this. `groff -mandoc -Thtml rdiff-backup.1 > rdiff-backup.1.html` looks kind of OK for a start, we can always improve later.

Regarding the bubbles, I'm not sure how much you can influence them, but I'd wish:

* (Download) to https://github.com/rdiff-backup/rdiff-backup/releases (get rid of tar.gz and .zip, they're rather useless for a start)
* (Documentation) to a page listing all further documents
* (Contribute) to GitHub's repo https://github.com/rdiff-backup/rdiff-backup
* (Support) to GitHub's issues https://github.com/rdiff-backup/rdiff-backup/issues
* (Contact) to https://lists.nongnu.org/mailman/listinfo/rdiff-backup-users

**Comment by frankcrawford** [comment]
Yes, that is what I was going to do for the manpages.
As for the others, I'll turn off the autogeneration of the bubbles and have to make it manually.

**Comment by ikus060** [comment]
For the time being, could we remove the duplicate pages from rdiff-backup.net and simply redirect to https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/FAQ.md

**Comment by ericzolf** [comment]
Or to https://rdiff-backup.github.io/rdiff-backup/FAQ.html as you prefer, fine with me. Just make sure you compare/merge both versions before deleting one.

**Comment by ericzolf** [comment]
Looking through https://medium.com/@danieljimgarcia/publishing-static-sites-to-github-pages-using-github-actions-8040f57dfeaf I think that our approach should be to have all the _source_ files in our main repo (the [current one](..)), then add a GitHub action to publish the site to https://github.com/rdiff-backup/rdiff-backup.net (see below), from which the GitHub Pages would automatically take the site and publish it to rdiff-backup.net.

The publishing from one Git repo to the next could be done in three main ways:

1. custom HTML generation, more or less as today, just with automated conversion from asciidoc to HTML
2. use a static site generator, both Hugo and Jekyll understand asciidoc
3. create a Jekyll _source_ site and let GitHub Pages make a website out of it

Few random notes:
1. option 1 and 2 require to set `.nojekyll` flag file to avoid interpretation as Jekyll source site (as today)
2. option 1 is probably the easiest one, but could become the ugliest one, it'll continue to look like a bunch of pages instead of an integrated website. I'd know how to implement option 2 using Hugo but I guess Jekyll isn't more complex. Option 3 could be a compromise with less work, but I don't know if GitHub's Jekyll has the asciidoc plug-in installed.

**Comment by ericzolf** [comment]
I've had a first go at it, in a [forked repo](https://github.com/rdiff-backup/rdiff-backup-site-tests/) to avoid too much noise, and the result is now visible at https://rdiff-backup.github.io/rdiff-backup-site-tests/ - it's far from finished and it doesn't look especially nice but the principle works.

@ottok I think you own the domain rdiffbackup.net - did you have to do something on your end to redirect it to the right github.io site? I'm still wondering how some of the DNS/HTTP magic works.

**Comment by ericzolf** [comment]
OK, I'm still a bit unsure but reading https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain, I have the impression that the only important aspect is the domain redirection and it's independent from the repository, so it should be fine as it is currently.
