### ISSUE TITLE
Document step-by-step Windows development

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#220]
I'm trying to get a windows 7 environment working to compile the C extension.

I tried to follow the windows playbook, but the installation of `visualstudio2017buildtools` with chocolatey is failing without any apparent reason. 

I've start documenting the procedure so a human could make sens of it, but I would need help my self to get it work.

@ericzolf  Maybe you could provide your input here ? I saw various comments in the playbook regarding package failing to install using chocolatey. Did you had any problem with visualstudio2017buildtools ?

Otherwise, I've also try to install visual studio 2017 from https://www.techspot.com/downloads/6278-visual-studio.html But it also fail with a certificate error.

I love Windows !

**Comment by ardovm** [comment]
FWIW, on my Windows system I followed the instructions from here: https://wiki.python.org/moin/WindowsCompilers.

I installed "Microsoft Build Tools for Visual Studio 2019" by hand (i.e. I did not rely on Chocolatey or anything) and I was set.

I hope this helps.

**Comment by ericzolf** [comment]
The installation of the build tools was quite a nightmare indeed. The main issue was lack of memory, my VM had to have at least 8GB of RAM, if not more. It was also damn slow and needed multiple reboots and retries until it worked. And this is even a step where I stopped using Ansible and installed the package using choco directly.

I also might have missed the --passive flag + IIRC there was a recommendation to install the dependencies them reboot then install the package.

**Comment by ericzolf** [comment]
Forget about --passive, the default --quiet is even less interactive (well, --passive might be better for debugging).
