### ISSUE TITLE
Is there any way to install it on CentOS 8?

### ISSUE THREAD

**Issue by georgio-sd** [rdiff-backup/rdiff-backup#226]
Hi everybody!
I tried to installed rpm from centos 7 repo but it didn't work out. Is there any solution to install it on centos 8?

**Comment by georgio-sd** [comment]
I found it by googling "rdiff-backup el8" and the libraries it needs.

**Comment by frankcrawford** [comment]
@georgio-sd FYI, it is available from my COPR repo
https://copr.fedorainfracloud.org/coprs/frankcrawford/rdiff-backup/repo/epel-8/frankcrawford-rdiff-backup-epel-8.repo
