### ISSUE TITLE
Plans to release 32-bit (x86-32) binaries?

### ISSUE THREAD

**Issue by tomasz1986** [rdiff-backup/rdiff-backup#243]
Please forgive me if this has been already explained, but I have searched and could not find any specific information.

Are there any plans to release 32-bit (x86-32) binaries alongside the currently available x86-64 ones? I have at least a few Intel Atom based systems, which are 32-bit only, hence the question.

**Comment by ericzolf** [comment]
Yes, there will be i686 wheels being released. Hence closing.
