### ISSUE TITLE
Tries to access a directory that is excluded as the user doesn't have access, and hence gives a Permission Denied error

### ISSUE THREAD

**Issue by KevWal** [rdiff-backup/rdiff-backup#245]
Rdiff-backup tries to access a directory that is excluded (as the user doesn't have access), and hence gives a Permission Denied error:

ListError .android_secure [Errno 13] Permission denied: '/storage/3334-3438/.android_secure'

This is reported elsewhere, but I am assuming this is the right forum now?
https://savannah.nongnu.org/bugs/?32597

**Comment by ericzolf** [comment]
I can confirm the issue with a most recent version:

```
$ rdiff-backup --version
rdiff-backup 1.9.0b1.dev1+g0ce57fa
$ cd /tmp
$ mkdir -p from/alpha/beta/gamma 
$ sudo chown root:root from/alpha/beta/gamma/ 
[sudo] password for xxx: 
$ sudo chmod 700 from/alpha/beta/gamma/ 
$ rdiff-backup --exclude '**/alpha' from/ to/ 
ListError: 'alpha/beta/gamma' [Errno 13] Permission denied: b'from/alpha/beta/gamma'
```
As it's not a regression but an old bug, we'll look into it once our next release is out (hopefully very soon).
