### ISSUE TITLE
Running latest version on windows errors when specifying a remote directory

### ISSUE THREAD

**Issue by geekbozu** [rdiff-backup/rdiff-backup#260]
![image](https://user-images.githubusercontent.com/4099721/74095436-b6d6e600-4abe-11ea-90be-03e27008ef2f.png)

Expected results:
Connects via supplied SSH command to remote server and performs a backup

What happens:
Errors with an iterable error on Popen. 

Really not sure what I'm doing wrong. Any help here would be great.

Remote server is an RPI running the latest version 1.9.0b as well.
Local backups work fine but soon as I add the :: it fails.

This happens when using --test-server as well

**Comment by ikus060** [comment]
This is a very interesting error. 
It cleary seams to be related to Windows only and not Linux. Could you try to run the same command or something very similar for that purpose without the --remote-schema ? This seams to be the culprit.

Then post the results of the logs here again. That should help use get this fixed.

**Comment by geekbozu** [comment]
Its the exact same :)
![image](https://user-images.githubusercontent.com/4099721/74096173-4bdedc80-4ac9-11ea-82ec-4cd7ef7aa561.png)
I have no way to do any debugging on this on windows, But after some digging for some reason it seems like the call to popen is getting passed a bad remote_cmd
https://github.com/rdiff-backup/rdiff-backup/blob/master/src/rdiff_backup/SetConnections.py#L172

It looks correct on my rpi side which ive made some code edits to see variables as they are used. So really not sure whats going on on the Windows end of things.

**Comment by ericzolf** [comment]
The remote_cmd looks good to me, I have the impression that the issue is rather some Windows speciality in the Python code of subprocess.Popen. A wild guess on my side is that subprocess.PIPE is the culprit. I need to check this but it'll take a while, my Windows environment is down. @geekbozu which SSH did you install and how on Windows?

**Comment by ericzolf** [comment]
OK, I think I found the culprit:

```
Changed in version 3.8: args parameter accepts a path-like object if shell is False and a sequence containing bytes and path-like objects on Windows.
```

We already encountered the issue that Python got some fixes in 3.8 around bytes paths (which we can't use yet). So one more workaround for Windows...

**Comment by geekbozu** [comment]
I have tried it with both a custom call to plink and a version of ssh that
just happens to be on my system. Both result in the same error. I had a
friend of mine test it as well it showed the same result. Not 100% sure on
his setup.

Python is version 3.7.4 from anaconda. Not the latest distribution version
of 3.8.1. I'll update that tomorrow and see if that fixes it.

**Comment by ericzolf** [comment]
Confirmed: `subprocess.Popen("dir", shell=True)` works, but `subprocess.Popen(b"dir", shell=True)` fails with the ominous "int isn't an iterable" error. It's a Python issue (actually) but we'll work around it.

You don't need to upgrade your Python, the Windows-exe comes with its own version embedded (3.7).

**Comment by geekbozu** [comment]
I realized that and edited my response before hand no worries!
And awesome you guys are great, I found this the other day looking for a
solution to my weird setup and this tool won the usage award so i'm super
happy to see it getting maintained so fast!

**Comment by ericzolf** [comment]
@geekbozu can you please try the attached binary (created by PR #262) and tell us your results:
[rdiff-backup-1.9.0b1.dev9+g94eb73a.win32exe.zip](https://github.com/rdiff-backup/rdiff-backup/files/4179469/rdiff-backup-1.9.0b1.dev9%2Bg94eb73a.win32exe.zip) ?

**Comment by geekbozu** [comment]
Works no problem now, 
--remote-schema flag works as well. 
so that seemed to do it!
