### ISSUE TITLE
Debian package cannot be installed on debian:sid

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#263]
Either we should document more or get our debian pacakge fixed.
I'm trying to use the debian package as part of an automation and it's failing as follow.

```
$ docker run --rm -it debian:sid
# apt update
...
# apt install wget
...
# apt install ./rdiff-backup_1.4.0b1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'rdiff-backup' instead of './rdiff-backup_1.4.0b1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rdiff-backup : Depends: python3 (< 3.7) but 3.7.5-3 is to be installed
                Depends: librsync1 (>= 0.9.6) but it is not installable
                Recommends: python3-pylibacl but it is not going to be installed
                Recommends: python3-pyxattr
E: Unable to correct problems, you have held broken packages.
```
@ottok Which version of Debian is supported ?

**Comment by ottok** [comment]
Where did you get this `rdiff-backup_1.4.0b1_amd64.deb` from you used in this test? That is quite central to the question, as deb and rpm packages are not universal like a .exe in Windows, but usually target certain distro versions.

**Comment by ikus060** [comment]
Sorry, I've remove the wget call.
I got it from here: https://github.com/rdiff-backup/rdiff-backup/releases/tag/v1.9.0b0
https://github.com/rdiff-backup/rdiff-backup/releases/download/v1.9.0b0/rdiff-backup_1.4.0b1_amd64.deb

**Comment by ottok** [comment]
That package is build in Ubuntu 18.04 (I think Travis-CI runs it) and thus it has bindings to the Python version in Ubuntu 18.04. It should install OK in a Ubuntu 18.04 Docker image.

For Debian Sid you could use the Ubuntu 20.04 build from https://code.launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-development/+packages

..unfortunately the PPA is now broken, I need to debug that too.

**Comment by ikus060** [comment]
Ok, If that debian package is only working for a specific version of Ubuntu, might be better to avoid deploying this deb. all together and only keep the build of deb as a test without distribution package.

**Comment by ottok** [comment]
You can try https://code.launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-development/+build/18692368/+files/rdiff-backup_1.9.0b1.dev10+g4744471-0~202002110832~ubuntu20.04.1_amd64.deb

**Comment by ottok** [comment]
Yes, I agree and I commented this earlier, but I guess I was not clear enough in my arguments.

It is best to let users consume rdiff-backup on Linux either from pip or via their own package manager so they get all the security and authenticity their download channels provide instead of manually downloading and installing binaries.

**Comment by ericzolf** [comment]
That's an easy one, you just need to restrict the condition `condition: $MAKE_STEP == ?dist*` on line 33 of .travis.yml and hence exclude bdist_deb (or rename `bdist_deb` to something else)
