### ISSUE TITLE
Pypi.org only has source packages deployed

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#264]
@ericzolf 
Had a look at pypi.org to check if the packages are properly working.
I notice the last release 1.9.0b1 only has source package distribution. I'm guessing it should contains the binaries too with the last changes made to travis. Or is it only pushed to test.pypi.org ?

See https://pypi.org/project/rdiff-backup/1.9.0b0/#files

**Comment by ericzolf** [comment]
That's OK: it was Otto who created the release manually, nothing to do with my last version of the Travis CI (my tests went only to test.pypi.org).

**Comment by ikus060** [comment]
I tough you had created another tags after your changes to travis.
Sorry.
