### ISSUE TITLE
Location of Windows binaries unclear 

### ISSUE THREAD

**Issue by bendybendy** [rdiff-backup/rdiff-backup#267]
The documentation for Windows describes a rdiff-backup-VERSION-PLATFORM.exe compiled binary, but it is unclear where the download is hosted. Top level links to the .zip and .tgz downloads do not seem to contain the windows binary, nor does the github repo.

**Comment by ericzolf** [comment]
Sorry, we'll improve the documentation: all the files are available under https://github.com/rdiff-backup/rdiff-backup/releases - the Windows executable is now packed in the file called `rdiff-backup-VERSION.win32exe.zip`.
