### ISSUE TITLE
Reconsider the software architecture of rdiff-backup

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#274]
As I go through the depth of the rdiff-backup code, it appears necessary to reconsider a re-factoring of the code, mainly to simplify it and make it easier to understand and maintain. This issue is meant as a place for me to put my rambling as I think about it. Feel free to comment it or ignore it.

There are for now my ideas how the structure of the code should look like:

* there are 3 types of repositories:
    * OriginRepo: from where a backup is being made
    * BackupRepo: to where a backup is being made, or from where a restore is made
    * RestoreRepo: to which a restore is being made, from a backup repo
* Each Repo type is linked to a FileSystem, which knows how to handle "strange" filenames (the "real" one, too long, forbidden character, ...) and can provide a fitting "quoted" name, this is nothing that needs to interest anybody else (else FilenameMapping, QuotedRBPath, LongFilename, etc... are bad ideas, they shouldn't need to be visible to the outside world).
* Between Repos we just need to exchange "files" (aka RPath objects) which contains everything a Repo needs to know how to handle it. A Repo is also created from an RPath, as it is at the end just a directory with some specifics.
* In the middle of everything, we have controllers/actions (Backup, Restore, Verify, Compare, etc...), which generally asks one SourceRepo (e.g. OriginRepo for BackupAction resp. BackupRepo for RestoreAction) which files/RPaths it has  and hands them over to TargetRepo (similarly BackupRepo resp. RestoreRepo).

We need a few more objects like Connection, Selection, Log, etc... but that should be most of it.

A few more questions circle in my mind at this stage:
* is the selection (include/exclude) made by the Repos or by the Action?
* how to move from the current situation to the final one (which doesn't need to look like above) without breaking the interfaces each time?

**Comment by ikus060** [comment]
I'm really interested to help you on the refactoring side. But I know I
don't have a depth knowledge of the internal like you do.

Would be nice if you find a small issue or refactoring I can work on to
dive into the code. Obviously, after 2.0.0

**Comment by ericzolf** [comment]
Some more thoughts as I go through the code (to prefix internal functions with an underscore, see branch ericzolf-internal-functions):
- the metadata.py files contains as well base functions for eas, acls and win_acls as a manager class to keep them together; this creates circular dependencies
- having eas and acls in the same module might not make much sense.
To fix those issues and clarify the code, I'm thinking about the following:
1. create a meta package
2. split metadata in "meta.base" for the base classes, and "meta.manager" to manage them all
3. derive "meta.eas", "meta.acls" and "meta.win_acls" (with or without s) from "meta.base"
4. re-shape of course the tests to fit the new structure

In order to keep at least for one version the compatibility, we'll have to keep the old modules and classes as a compatibility-wrapper.

**Comment by dbaarda** [comment]
Random suggestion on include/exclude;

One approach thats worked for similar problems for me is a view/model/controller approach where the include/exclude is a "view" that can be applied to a repo "model". This kind of approach can also be used for transforming repo's between different filesystem naming constraints, with the filename mapping also being done by the "view".

**Comment by ericzolf** [comment]
Continuing to think about it: we'll need also a 'utils' sub-package for all utilities, with requirement:
- no internal dependency and avoid external dependencies (i.e. only dependencies on standard modules)
- no direct relation to the core of the rdiff-backup features
i.e. users/groups, timesdates, etc...

**Comment by ericzolf** [comment]
@dbaarda well thought, even if I'm unsure if a view model is the right approach: a view/model approach implies that you might have multiple views on the same model, whereas here the include/exclude view doesn't change during the course of the program, so isn't it then part of the model rather than a view on it?

**Comment by dbaarda** [comment]
No, the model is the filesystem, and the view gives you a selected and/or transformed view of it, that you can then put into your backup. The backup can also be implemented with the filesystem model API, allowing you to use the same view mechanism to give a selected/transformed view for restores. "Views" can be used to select a subset of files, possibly rename/move them, and transform between filesystem limitations in reversable ways (symlinks, case-sensitive, etc). If the view itself implements the same filesystem model API then you can even stack them.

**Comment by ericzolf** [comment]
The new structure with actions and locations, is near enough to the ideas discussed so that we can close this issue. It still requires more clean-up and simplification, but that will happen naturally. No need for this issue to remain open.
