### ISSUE TITLE
Re-implement the arguments parsing using argparse module

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#280]
This will make the code more modern and robust, and give us "for free" the `--help` option.

The behaviour shall not change at all, only the implementation, using https://docs.python.org/3/library/argparse.html#module-argparse

**Comment by ottok** [comment]
Another option is https://typer.tiangolo.com/ or https://click.palletsprojects.com/en/7.x/ (which Typer also builds upon).

**Comment by ericzolf** [comment]
Typer doesn't seem to be broadly packaged (not in Debian or Fedora), whereas click seems more present, but argparse is part of the standard library, so it needs to be weighted if those non-standard libraries are worth the additional dependency.
