### ISSUE TITLE
What Documentation Files To Distribute

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#291]
With the revamp of the logo, etc, I've realised that we should agree what documentation should be distributed in downstream distributions.

Currently Fedora has:
    %doc CHANGELOG COPYING README.md
    %doc docs/FAQ.md docs/examples.md docs/DEVELOP.md docs/Windows-README.md
which doesn't include docs/Windows-DEVELOP.md (which is in setup.py), nor any of the icons in docs/resources.

So, what would you like to see in a distibution?

**Comment by ericzolf** [comment]
Your decision honestly. I would keep the windows docs even on Linux because rdiff-backup is cross platform, and users might want to read docs on either of them. Not sure the icons have an added value though (perhaps only the one referenced from the readme).

**Comment by frankcrawford** [comment]
@ericzolf Just realised I can't pickup the icons, as they aren't copied anywhere by setup.py.

**Comment by frankcrawford** [comment]
Also noticed that docs/index.md also not in setup.py.

**Comment by ikus060** [comment]
> Just realised I can't pickup the icons, as they aren't copied anywhere by setup.py.
> Also noticed that docs/index.md also not in setup.py.

My opinion, I would only redistribute the man page, CHANGELOG, COPYING. Those are text file and self contain. If user want more documentation I think we know how to search with google...

@frankcrawford Your decision honestly

**Comment by frankcrawford** [comment]
What I am currently distributing is the same files as those included in setup.py.
