### ISSUE TITLE
FAQ and examples are duplicate in rdiff-backup and rdiff-backup.net repo

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#300]
The FAQ and examples pages are almost identical and I'm wondering what to do with them.
Maintaining both of them at the same time is probably not appropriate. So I'm recommending to keep only one version. Either the version from the web site or from github.

Since the target audience of rdiff-backup is mostly technical, I would keep the version from github (rdiff-backup). And the web site could link to github: https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/FAQ.md

What do you think ?

**Comment by frankcrawford** [comment]
I think the longer term plan is to move the web site to use the rdiff-backup repo, and get rid of rdiff-backup.net.

However, the other problem with adding the link is that the file doesn't get automatically preprocessed to HTML.

**Comment by ericzolf** [comment]
Correct, it's #215 . Let's continue the discussion there.
