### ISSUE TITLE
man page for rdiff-backup-delete in markdown format

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#301]
We need a man-page for the new rdiff-backup-delete. 

Regarding man-pages, @frankcrawford and I tried (not too hard from my side) to translate the existing man-pages to Markdown for automated conversion to troff (I used pandoc), without success (the result was miserable). Extra points if you manage to do it properly for the rdiff-backup-delete man-page so that we can apply the receipt to the existing ones :-P (I can take care of adapting the setup.py to make the conversion on-the-fly).

http://jeromebelleman.gitlab.io/posts/publishing/manpages/ seems like a good start.

_Originally posted by @ericzolf in https://github.com/rdiff-backup/rdiff-backup/pull/285#issuecomment-599036248_

**Comment by ericzolf** [comment]
I found this explanation, which seems to work well: https://eddieantonio.ca/blog/2015/12/18/authoring-manpages-in-markdown-with-pandoc/

The short version is:

1. use the attached template (rename it) 
[hello.1.md.txt](https://github.com/rdiff-backup/rdiff-backup/files/4590904/hello.1.md.txt)
2. `pandoc --standalone --to man hello.1.md -o hello.1`
3. check with `man -l hello.1`
4. Web page creation with `pandoc --standalone --to html hello.1.md -o hello.1.html` works as well quite good, which will help us in the future.

It creates a new dependency on pandoc but as it's packaged for Debian and Fedora at least, it shouldn't be a big issue.

**Comment by frankcrawford** [comment]
@ericzolf the hard part is that you have to rewrite the page in md format and check it.  While pandoc will convert man to md as well it is a very poor translation.
Of course, it is only required once and then you can move forward with it.

**Comment by ericzolf** [comment]
Agreed for the existing ones, and nothing urgent, but IMHO the way to go for this new one.

**Comment by ottok** [comment]
I am a big fan of https://www.gnu.org/software/help2man/ nowadays. I use it in my Python projects to automatically generate man pages that are never out-of-date :)

Unfortunately help2man is not compatible with the help format of the custom rdiff-backup argument parser we have, in fact one cannot even run `rdiff-backup --help`.

**Comment by ericzolf** [comment]
We have #280 for the help option.
