### ISSUE TITLE
Missing word in docs/DEVELOP.md

### ISSUE THREAD

**Issue by albert-github** [rdiff-backup/rdiff-backup#303]
In `docs/DEVELOP.md` we see the source code (line 184):
```
> **NOTE:** There is no uninstall command provided by the Python
distutils/setuptools system. One strategy is to use the `python3 setup.py
install --record <file>` option to save a list of the files installed to <file>,
another is to created a wheel package with `python3 setup.py bdist_wheel`,
as it can be installed and deinstalled.
```
which renders to:
> **NOTE:** There is no uninstall command provided by the Python
distutils/setuptools system. One strategy is to use the `python3 setup.py
install --record <file>` option to save a list of the files installed to <file>,
another is to created a wheel package with `python3 setup.py bdist_wheel`,
as it can be installed and deinstalled.

In the rendering we miss the second `<file>` as the md interpreter sees  it as a (unknown) html tag.
Better would be:
```
> **NOTE:** There is no uninstall command provided by the Python
distutils/setuptools system. One strategy is to use the `python3 setup.py
install --record <file>` option to save a list of the files installed to `<file>`,
another is to created a wheel package with `python3 setup.py bdist_wheel`,
as it can be installed and deinstalled.
```
which renders to:
> **NOTE:** There is no uninstall command provided by the Python
distutils/setuptools system. One strategy is to use the `python3 setup.py
install --record <file>` option to save a list of the files installed to `<file>`,
another is to created a wheel package with `python3 setup.py bdist_wheel`,
as it can be installed and deinstalled.

**Comment by ericzolf** [comment]
Would you like to fix yourself the typo and provide a Pull Request? It's just an offer if you'd like to try it.

You may start with forking: https://help.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #309
