### ISSUE TITLE
Unable to install on Raspbian (librsync.h/librsync.c)

### ISSUE THREAD

**Issue by Tahutipai** [rdiff-backup/rdiff-backup#316]
Manual install on Ubuntu via pip3: no problem.  But I am unable to do the same on a raspberry pi.

``python-librsync`` is installed, but it appears to be looking for the C source code for librsync, and I am not sure how to install that.

Truncated log:
```
>sudo pip3 install rdiff-backup
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting rdiff-backup
  Using cached rdiff-backup-2.0.0.tar.gz (408 kB)
Building wheels for collected packages: rdiff-backup
  ERROR: Command errored out with exit status 1:
   arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c src/_librsyncmodule.c -o build/temp.linux-armv7l-3.7/src/_librsyncmodule.o
  src/_librsyncmodule.c:25:10: fatal error: librsync.h: No such file or directory
   #include <librsync.h>
            ^~~~~~~~~~~~
```
How does one install the required C librsync library on Raspbian?

--

Also, just to avoid traps, for beginners, under installation the line:
``curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py sudo python3 get-pip.py sudo pip3 install rdiff-backup``
Should perhaps read:
``curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && sudo python3 get-pip.py && sudo pip3 install rdiff-backup``

**Comment by Tahutipai** [comment]
Ah figured it out, one just needs to run ``sudo apt update; sudo apt install librsync-dev``

Perhaps the installation document could be updated to reflect this? As it appears having the C source for librsync is a requirement.

**Comment by ericzolf** [comment]
It depends, only because it's ARM and we don't provide (pre-compiled) wheels for ARM but only for x86 and x86_64. And the formatting is also wrong, as you noticed yourself. We'll keep this issue opened until we've fixed the documentation. Thanks for reporting.

**Comment by Tahutipai** [comment]
Thanks Eric.  

Would it be useful if I format a clean RaPi, and write up the procedure to install rdiff-backup on vanilla Raspbian? (for beginners)

RaPi's are fairly common as is, but as the new Pi4 has gigabit ethernet and a separate bus for USB3 drives, it becomes a more practical candidate for certain backup requirements.

**Comment by ericzolf** [comment]
Proper testing can never hurt, try to stick to the Debian instructions though pip is packaged as `python3-pip` and doesn't need IMHO to be downloaded + you need also librsync-dev because of none-Intel architecture.

**Comment by ericzolf** [comment]
@Tahutipai are the new instructions from @ikus060 good enough for you at #318 ? Can we close this issue?

**Comment by ottok** [comment]
@Tahutipai Did you perhaps try installing rdiff-backup from the Ubuntu PPA as documented on the main README of this project? https://github.com/rdiff-backup/rdiff-backup#ubuntu-from-ppa

If has packages for these archs:
![image](https://user-images.githubusercontent.com/668724/79633418-14964700-816e-11ea-9446-e20534a63438.png)

What version of Raspberry Pi are you running?

**Comment by ikus060** [comment]
@Tahutipai Trying to followup on this issue. The documentation was updated to clarify the step and dependencies required.

**Comment by Tahutipai** [comment]
@Patrik Dufresne Apologies for the delay, we are currently out of province
for other reasons, will be returning home in ~4 days

**Comment by Tahutipai** [comment]
Wiped and installed a fresh Pi to test - using latest Rasbian 10, as at time of writing.

Confirming: the following will install rdiff-backup (v2.0.0 as of todays date)

```
sudo apt update    
sudo apt install python3-pip librsync-dev    
sudo pip3 install rdiff-backup
```

Given the ubiquity of Rasberry Pi's, and that as of v4 they are a more acceptable backup device (1Gbps eth & USB 3.0), and that they appeal to a more education (perhaps less experienced) audience, my subjective opinion would be to add a seperate "Raspberry Pi" installation heading in the [readme](https://github.com/rdiff-backup/rdiff-backup/blob/master/README.md#installation)

A user may wish to just backup data, and have zero experience of Python or Python package managers etc.
