### ISSUE TITLE
Support: compare directory structures and generate patch-like file

### ISSUE THREAD

**Issue by gschaffner** [rdiff-backup/rdiff-backup#317]
Is there a way to use rdiff-backup to compare two directory structures? I'm trying to detect movement of files within a larger directory structure. I'd like to compare files just by file sizes, modification times, and checksums.

Essentially, I'm looking for something that behaves like `diff -rq dir1 dir2`, except (a) file moves are detected and (b) comparison is done by sizes, mod times, and hashes rather than file contents (since I'm looking to use this tool with mounted rclone remotes). `rclone check` does something like this, but does not detect moves.

Unfortunately a hardlink-based method (such as [this](https://lincolnloop.com/blog/detecting-file-moves-renames-rsync/)) also won't work for me as I'm trying to compare a local to a remote directory.

I've looked through the examples and FAQ and searched the man page, but haven't found a way to do this. (Using rdiff-backup for this use case was suggested [here](https://serverfault.com/questions/39534/best-way-to-compare-diff-a-full-directory-structure).)

Apologies if this is the wrong place to post this --- I couldn't find any other support forum for rdiff-backup.

Thank you!

**Comment by ericzolf** [comment]
There is also a mailing list bit it's as good a place as it can be to ask questions.

This said, rdiff-backup has no move-detection capabilities. Sorry.
