### ISSUE TITLE
[ENH] Remove increments based on number of increments, rather than age?

### ISSUE THREAD

**Issue by apocalyptech** [rdiff-backup/rdiff-backup#323]
This is a pretty minor/unimportant feature request, but I'd love to have an option which takes a number of increments, and removes all increments older than the last one (so rather than specifying by age, you're telling it that you want to keep N increments, regardless of age).  I run rdiff-backup nightly and generally like to keep a month's worth (30 days) of increments on-disk, but sometimes I'll have systems shut down for days or weeks at a time (generally coinciding with vacations or the like), and if I'm *just* doing age-based clearing, I'll find myself with a much reduced backup footprint as the older stuff gets cleared out.

I'm wrapping all my rdiff-backup calls with scripting anyway, so I'm just doing this in code right now (using `-l` to list increments and then using the age information given in there to construct an appropriate `--remove-older-than` argument), but it'd be nice to have it natively in the app.

Thanks for keeping rdiff-backup alive!  Nice to see 2.0 out here.  :)

**Comment by ericzolf** [comment]
That's an easy one! The option exists already, just use `--remove-older-than 30B`. It's documented in the man page under the TIME FORMATS section,  which I recognize is a bit unexpected.

**Comment by apocalyptech** [comment]
Oh!  Sheesh, you'd think I'd have found that.  :)  Thanks!
