### ISSUE TITLE
Deploy pre-release versions on PyPi

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#326]
To make it easier for a casual bug reporter to check out if their bug is fixed on git master and otherwise to install/test/debug latest development version and thus contribute and save our time in testing, it would be good to publish pre-release versions on PyPi.org.

We [did that](https://github.com/rdiff-backup/rdiff-backup/issues/58#issuecomment-576016726) prior to the 2.0.0 release, but not after. I think we should.

I did it manually now, but it could be in Travis-CI.

![image](https://user-images.githubusercontent.com/668724/79692377-78536980-826d-11ea-97fe-4984e70d162a.png)

Steps to do it manually:
```
git checkout feature/pypi-integration
git rebase -i master
make container
make bdist_wheel
python3 -m twine upload --verbose dist/rdiff-backup-2.0.1.dev9+g1e4f236.tar.gz
```

Unfortunately this fails right now due to the `+g1e4f236` local component in the version number.

Related:
- https://packaging.python.org/guides/distributing-packages-using-setuptools/#id68
- https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions

**Comment by ericzolf** [comment]
It's just a matter of tagging with alpha releases, and the Travis CI will work as expected.

**Comment by ottok** [comment]
OK!

Maybe the pre-release "pipeline" and versioning scheme should be documented
under
https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/DEVELOP.md#versioning
so
people know what to look for or to expect in terms of pre-releases

There is also under
https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/DEVELOP.md#releasing
>  An automated Pypi release is foreseen but not yet implemented.


Related, I noticed this sentence:
> TIP: Travis will not trigger again on a commit which has already gone
through the pipeline, even if you add a tag. This applies especially to PR
commits merged to master without squashing.

Travis-CI _never_ triggers on tags. It only triggers on commits. If
Travis-CI sees a commit that also has been tagged, it may see the tag, but
tagging events themselves are not sent to Travis-CI and Travis does not
track tags. One can however trigger a build manually on Travis-CI.org and
reference the commit id using a tag name.

**Comment by ottok** [comment]
I was wrong here ^ - Travis-CI does indeed also trigger on tag pushes, and it re-runs the whole pipeline for the same commit id it has already done before.

**Comment by ericzolf** [comment]
I am the opinion that it is a difference between travis-ci.org and .com but whatever, it makes pushing tags/new versions much easier indeed. PEP-440 describes what is acceptable but you can be more succinct. While you're at it, you might want to correct the links from travis-ci.org to travis-ci.com.

**Comment by ikus060** [comment]
Could we close this then ? We all agree it's possible to deploy dev/beta/rc version to PyPi with the appropriate tag ?

**Comment by ottok** [comment]
Can we close this once we have seen that automatic-by-tag dev/beta/rc
pre-release done at least once to PyPi?

**Comment by ericzolf** [comment]
Almost all the betas and the rc have been deployed like this, but as you see fit....

**Comment by ottok** [comment]
> Almost all the betas and the rc have been deployed like this, but as you see fit....

So 1.9.2rc0 was an automatically published version?

I think I manually published all the other versions.

**Comment by ericzolf** [comment]
Definitely rc0 and 1.9.1b0, and the Dev releases on test.pypi.org

**Comment by ericzolf** [comment]
I clarified the current configuration of Travis in this regard, please review.

**Comment by ottok** [comment]
Thanks for the documentation. I see you were using https://test.pypi.org/ for
dev releases. That site is only for testing PyPi, not intended for
distributing dev releases. All of our dev releases should go to real
https://pypi.org/ <https://test.pypi.org/>
