### ISSUE TITLE
[ENH] Create a version of rdiff-backup 1.3.3 that is co-installable with 2.0.0

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#333]
Being able to install 1.3.3 alonside 2.x on a new system (Ubuntu Focal or Debian Bullseye or newer) would make migrations from old systems easier (see [docs/migration.md](docs/migration.md)).

The package should be a stripped down version that simply installs `/usr/bin/rdiff-backup-1` alongside the `/usr/bin/rdiff-backup` (from version 2.x) plus pulls in the required Python 2 dependencies. No man pages or anything else would be needed for this compat version. Package could be called `rdiff-backup-1-compat`.

Idea discussed in https://github.com/rdiff-backup/rdiff-backup/pull/314

**Comment by ottok** [comment]
Published at https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-1-compat

**Comment by ottok** [comment]
```
root@5a38c2d94814:/build# rdiff-backup --version
rdiff-backup 2.0.0
root@5a38c2d94814:/build# rdiff-backup-1 --version
rdiff-backup 1.3.3
root@5a38c2d94814:/build# dpkg -L rdiff-backup-1-compat      
/.
/usr
/usr/bin
/usr/bin/rdiff-backup-1
/usr/lib
/usr/lib/python2.7
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/rdiff_backup
/usr/lib/python2.7/dist-packages/rdiff_backup/C.x86_64-linux-gnu.so
/usr/lib/python2.7/dist-packages/rdiff_backup/FilenameMapping.py
/usr/lib/python2.7/dist-packages/rdiff_backup/Globals.py
/usr/lib/python2.7/dist-packages/rdiff_backup/Hardlink.py
/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py
/usr/lib/python2.7/dist-packages/rdiff_backup/Rdiff.py
/usr/lib/python2.7/dist-packages/rdiff_backup/Security.py
/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py
/usr/lib/python2.7/dist-packages/rdiff_backup/TempFile.py
/usr/lib/python2.7/dist-packages/rdiff_backup/Time.py
/usr/lib/python2.7/dist-packages/rdiff_backup/__init__.py
/usr/lib/python2.7/dist-packages/rdiff_backup/_librsync.x86_64-linux-gnu.so
/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py
/usr/lib/python2.7/dist-packages/rdiff_backup/compare.py
/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py
/usr/lib/python2.7/dist-packages/rdiff_backup/eas_acls.py
/usr/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py
/usr/lib/python2.7/dist-packages/rdiff_backup/hash.py
/usr/lib/python2.7/dist-packages/rdiff_backup/increment.py
/usr/lib/python2.7/dist-packages/rdiff_backup/iterfile.py
/usr/lib/python2.7/dist-packages/rdiff_backup/lazy.py
/usr/lib/python2.7/dist-packages/rdiff_backup/librsync.py
/usr/lib/python2.7/dist-packages/rdiff_backup/log.py
/usr/lib/python2.7/dist-packages/rdiff_backup/longname.py
/usr/lib/python2.7/dist-packages/rdiff_backup/manage.py
/usr/lib/python2.7/dist-packages/rdiff_backup/metadata.py
/usr/lib/python2.7/dist-packages/rdiff_backup/regress.py
/usr/lib/python2.7/dist-packages/rdiff_backup/restore.py
/usr/lib/python2.7/dist-packages/rdiff_backup/robust.py
/usr/lib/python2.7/dist-packages/rdiff_backup/rorpiter.py
/usr/lib/python2.7/dist-packages/rdiff_backup/rpath.py
/usr/lib/python2.7/dist-packages/rdiff_backup/selection.py
/usr/lib/python2.7/dist-packages/rdiff_backup/static.py
/usr/lib/python2.7/dist-packages/rdiff_backup/statistics.py
/usr/lib/python2.7/dist-packages/rdiff_backup/user_group.py
/usr/lib/python2.7/dist-packages/rdiff_backup/win_acls.py
/usr/lib/python2.7/dist-packages/rdiff_backup-1.3.3.egg-info
/usr/share
/usr/share/doc
/usr/share/doc/rdiff-backup-1-compat
/usr/share/doc/rdiff-backup-1-compat/changelog.Debian.gz
/usr/share/doc/rdiff-backup-1-compat/changelog.gz
/usr/share/doc/rdiff-backup-1-compat/copyright
```

**Comment by ottok** [comment]
Note that we can do this only for Ubuntu Focal. In Ubuntu Groovy (upcoming 20.10 version) Python 2 has been dropped and it is too much work to build the compat package there. For the same reason we cannot have a compat package in Debian Sid either.

**Comment by dominicraf** [comment]
This sounds great Otto thanks! Is it tested and working in Ubuntu 20.04 (Focal Fossa) both as client and server? That gives us 5 years support for dual-version - enough time to migrate I think.

**Comment by frankcrawford** [comment]
Just an update rdiff-backup 1.2.8 is available for RPM based systems as well (Fedora, RHEL, etc).
It can be installed as:
`sudo yum install yum-plugin-copr epel-release`
`sudo yum copr enable frankcrawford/python2-rdiff-backup`
`sudo yum install python2-rdiff-backup`
and will install a `rdiff-backup-1`
Note: v1.2.8 is the same as previously distributed for these systems.

**Comment by ericzolf** [comment]
\o/
Adding that Fedora surely doesn't need `epel-release` but Fedora not being a long-term supported distro, it shouldn't be the first candidate for this approach (in other words, 6-12 months of support for Fedora 32 and then probably gone).

**Comment by ericzolf** [comment]
How do we want to publish the information present in this issue and close it (this issue)? I would suggest to have a new document we can ditch later on, linked from the main readme (e.g. "if you still need version v1 for migration purposes, look in \[compatibility version instructions](docs/COMPAT_v1.md)").

What do you think? Who takes the action? @frankcrawford @ottok I think you need to work together on this one, one makes the PR, the other one reviews it?

**Comment by frankcrawford** [comment]
@ericzolf I can see what I can do for it, as I'm have a couple of minor updates to README.md to also add.

**Comment by ikus060** [comment]
For Debian, Ive started working on a backport version of rdiff-backup v1.2.8 (not v1.3.3) that is installable for Stretch, Buster and Bullseye.
Everything is available here and I will probably maintain this for a while.
https://gitlab.com/ikus-soft/rdiff-backup-build

**Comment by ericzolf** [comment]
You could have put the repo in the rdiff-backup organization to make it easier for others to participate, if they want. The name is perhaps not very specific though :-)

**Comment by ikus060** [comment]
I could probably clone and make it available in Gitlhub too. But the pipeline will stay in Gitlab.
Any recommendation regarding the name of the repo ?

**Comment by ericzolf** [comment]
Sorry, I oversaw that it's in GitLab. Not worth the effort then IMHO. I'm just thinking if and where we could link it from the documentation, for people to find more easily.

**Comment by ericzolf** [comment]
Nothing happened and the period for migration is passed IMHO, so I close the issue. Feel free to re-open it if you plan to do anything about it.

**Comment by frankcrawford** [comment]
Eric,
I agree that the time has passed.  Packages exist for CentOS, and I think for Debian, they are just separate to the standard rdiff-backup distributions.

Frank
