### ISSUE TITLE
[BUG]Need consistent exit code after verification failure

### ISSUE THREAD

**Issue by dominicraf** [rdiff-backup/rdiff-backup#338]
## Bug summary

In all versions of rdiff-backup, if a verification fails the return code is the number of 'bad_files'. This makes it impossible to tell from a return code whether the failure was because of a verification problem or some other extraneous issue.

The purpose of verification is to determine if the repo is consistent so being unable to tell whether a failure indicates lack of consistency is a serious problem.

## Version, Python, Operating System

This bug precedes v2 and is found in all earlier versions as well. It is a breaker for my [timedicer-verify ](https://www.timedicer.co.uk/programs/help/timedicer-verify.sh.php) script which therefore applies a similar patch (but currently only for v1.2.8).

## Fix

The attached patch was made for compare.py in v2.0.0 and should work, but is untested for this version. A similar patch for v1.2.8 has worked for me for many years.

With this patch, if there are one or more files that fail verification then the return code is 2, and there is an appropriate text message, otherwise it is 0. So a return fault code of 1 (or indeed any code other than 2) from a verification operation would have to come from some other problem.

A small improvement would be to state the number of bad_files in the text message, but even this is beyond my very limited python coding ability, sorry.
[patch_compare.py_verify_exit_code.txt](https://github.com/rdiff-backup/rdiff-backup/files/4556827/patch_compare.py_verify_exit_code.txt)

**Comment by ericzolf** [comment]
Looks good to me. Fancy submitting your patch as a Pull Request?

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
(you'll need to go the "fork" route)

**Comment by dominicraf** [comment]
OK Eric, I have done that now (I think) - new territory for me!
