### ISSUE TITLE
ListError prints wrong path when excluding user mounted directory as root

### ISSUE THREAD

**Issue by alextz** [rdiff-backup/rdiff-backup#34]
Running as root, trying to exclude a user-mounted directory, rdiff-backup prints a ListError with a confusing path. Here's a script that shows the issue. Comments in the bash script explain what I've found.

[listerror.sh.txt](https://github.com/sol1/rdiff-backup/files/2289518/listerror.sh.txt)

**Comment by ericzolf** [comment]
The issue still exists under rdiff-backup 2.0.3 (and beyond in Git). Here a slightly modified version of the script (I don't like doing tests involving my home directory).
[listerror.sh.txt](https://github.com/rdiff-backup/rdiff-backup/files/4844072/listerror.sh.txt)

I'm not finished with the analysis but breakpoint set to `/usr/local/lib64/python3.8/site-packages/rdiff_backup/backup.py:266`, failing at `/usr/local/lib64/python3.8/site-packages/rdiff_backup/rorpiter.py:202` when the next rp (holding the mount point) is pulled from rpiter.
