### ISSUE TITLE
Cannot build from a git clone

### ISSUE THREAD

**Issue by byron-hawkins** [rdiff-backup/rdiff-backup#35]
The repository layout is different from the tarball, so `setup.py` is completely broken when run from a git clone of this repository. 

    > python setup.py --librsync-dir="$lab/tools/librsync/build" install --prefix=~/.local
    running install
    running build
    running build_py
    error: package directory 'rdiff_backup' does not exist

I tried soft links to help the script find things, but it didn't work.

**Comment by jjdavis** [comment]
A probably inelegant way around that is to copy setup.py from rdiff-backup/rdiff-backup/dist to rdiff-backup/rdiff-backup and then munge a couple of paths to files:

68c68
< 	  ext_modules = [Extension("rdiff_backup.C", ["cmodule.c"]),
---
> 	  ext_modules = [Extension("rdiff_backup.C", ["rdiff_backup/cmodule.c"]),
70c70
< 							   ["_librsyncmodule.c"],
---
> 							   ["rdiff_backup/_librsyncmodule.c"],
79c79
< 					 ['CHANGELOG', 'COPYING', 'README', 'FAQ.html'])],
---
> 					 ['CHANGELOG', 'COPYING', 'README'])],

That let me run python setup.py --prefix=/usr/local successfully on an Ubuntu 16.04 box after cloning the current distribution.

**Comment by ardovm** [comment]
For what I could understand, the script `rdiff-backup/dist/makedist.py` shall be used to make an archive of the sources.

The command:
`$ python dist/makedist.py 1.2.3`
will generate the file `rdiff-backup-1.2.3.tar.gz`. Such archive should allow installation by means of `setup.py`.

**Comment by ericzolf** [comment]
If you have a look at PR#53 `./setup.py build` works flawlessly, I haven't looked yet at the packaging framework though, but I would argue that `setup.py` doesn't need absolutely to work from a tarball. Hence we could close this issue once the branch is merged.

**Comment by ottok** [comment]
To confirm the project is buildable I've created a Dockerfile to containerize the build (and dependencies). Works well now, so closing this issue.
