### ISSUE TITLE
directory with no read permissions for owner causes crash

### ISSUE THREAD

**Issue by rwd2** [rdiff-backup/rdiff-backup#352]
Steps to reproduce:

```
mkdir -p source/x backup
touch source/x/test
chmod 444 source/x
rdiff-backup source backup
```
Expected outcome:
Warning about not being able to read/backup directory 'source/x' when backing up directory 'source'

Actual outcome:
fatal error., and, if there were previous increments, the backup directory now requires '--check-destination-dir'.

**Comment by rwd2** [comment]
I ran into this issue because packages occasionally seem to have these non-readable files and folders. As a workaround I now issue this before backing up, but it seems to me rdiff-backup should not require this:

find sourcedir -type d,f \! -perm /u+w  -exec chmod u+w {} \+

**Comment by ericzolf** [comment]
Wasn't there a template available as you created the issue?
Can you please fill it?

Just FYI:

```
$ mkdir -p source/x backup
$ touch source/x/test
$ chmod 444 source/x
$ touch source/z
$ rdiff-backup source backup
ListError: '(b'x', b'test')' [Errno 13] Permission denied: b'source/x/test'
ListError: '(b'x', b'test')' [Errno 13] Permission denied: b'source/x/test'
$ echo $?
0
$ ll backup
total 0
drwx------. 3 ericl ericl 260 May  7 07:22 rdiff-backup-data
drwxr--r--. 2 ericl ericl  40 May  7 07:22 x
-rw-rw-r--. 1 ericl ericl   0 May  7 07:22 z
$ rdiff-backup --version
rdiff-backup 2.0.1rc0
```

**Comment by rwd2** [comment]
## Bug summary
When a folder with no read permissions for owner, which has one of more files in it is backed up rdiff-backup crasehs

## Version, Python, Operating System

Version: 2.0.0
Python: 3.8.2-2
Operating System: Arch Linux (5.4.36-1-lts #1 SMP Wed, 29 Apr 2020 16:23:03 +0000 x86_64 GNU/Linux)

Call `rdiff-backup -v9` and paste the output between the backquotes below, repeat for each environment impacted:

```
2020-05-07 08:53:29.947590 +0200  <CLIENT-230334>  Using rdiff-backup version 2.0.0
2020-05-07 08:53:29.947721 +0200  <CLIENT-230334>  	with cpython /usr/bin/python version 3.8.2
2020-05-07 08:53:29.952509 +0200  <CLIENT-230334>  	on Linux-5.4.36-1-lts-x86_64-with-glibc2.2.5, fs encoding utf-8
2020-05-07 08:53:29.952669 +0200  <CLIENT-230334>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.

```

## rdiff-backup call

How did you call rdiff-backup, with which parameter:

```
rdiff-backup source backup

```

## What happened and what did you expect?
crash.
[rdiff-backup_error.txt](https://github.com/rdiff-backup/rdiff-backup/files/4591205/rdiff-backup_error.txt)


## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

**Comment by ericzolf** [comment]
Issue has already been reported and should be fixed with the next version. Could you please verify with the release candidate at https://github.com/rdiff-backup/rdiff-backup/releases/tag/v2.0.1rc0 and/or close the issue if everything is fine?

**Comment by rwd2** [comment]
I tried to install the release candidate with pip3 on my Arch Linux system, instead of the package manager, as described on https://github.com/rdiff-backup/rdiff-backup/blob/v2.0.1rc0/README.md, but running it gives permission errors. this seems to create files with wrong permissions, so I can't run it.  I will wait until it is released because Arch Linux is rolling release.

**Comment by ericzolf** [comment]
You should remove first the arch package then install via pip, or you wait, also OK. Let me close the issue, feel free to open a new one if you still see the issue after upgrade.
