### ISSUE TITLE
[BUG] Trojan:WIN32/Azden.B!cl

### ISSUE THREAD

**Issue by RAJensen** [rdiff-backup/rdiff-backup#365]
## Bug summary

Windows Defender put file: rdiff-backup-2.0.3\rediff-backup.exe in quarantine as due to:
Trojan: Win32/Azden.B!cl

## Version, Python, Operating System
Version: 2.0.3 Windows 10.

Call `rdiff-backup -v9` and paste the output between the backquotes below, repeat for each environment impacted:

```
```

## rdiff-backup call

How did you call rdiff-backup, with which parameter:

``` Did double clicl on rdiff-back.exe
```

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

**Comment by ericzolf** [comment]
I can't swear it but I would assume a false positive: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Azden.B!cl shows that it's AI based, hence subject to errors. At this stage, I'm not sure how to get certitude one way or the other, and/or get rid of the false positive.

**Comment by ericzolf** [comment]
I tried to submit the exe-file under https://www.microsoft.com/en-us/wdsi/filesubmission as software developer but the upload failed. @ikus060 @ottok could one of you try?
@RAJensen could you please provide the [definition version](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus#definition-version)?

**Comment by ericzolf** [comment]
Hi,

We've got a report that the latest rdiff-backup version 2.0.3 might be infected.

I rather suspect a false positive but security goes first, and until we've definitely clarified the situation, please be careful and, if you've got Microsoft-super-powers, your help is very much appreciated, so that we can quickly close the topic.

We'll keep you posted as situation evolves.

KR, Eric

**Comment by ericzolf** [comment]
The upload failed again this morning. Typical for Microsoft, there is only a unhelpful error message "ile upload failed - please try again." so I'd appreciate if someone else could try. Here are my entries:
[job_5-Submit_a_file_for_malware_analysis_-_Microsoft_Security_Intellig.pdf](https://github.com/rdiff-backup/rdiff-backup/files/4648283/job_5-Submit_a_file_for_malware_analysis_-_Microsoft_Security_Intellig.pdf)

**Comment by RAJensen** [comment]
> 
> 
> I tried to submit the exe-file under https://www.microsoft.com/en-us/wdsi/filesubmission as software developer but the upload failed. @ikus060 @ottok could one of you try?
> @RAJensen could you please provide the [definition version](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus#definition-version)?

Defender definition: 1.315.932.0

**Comment by JirkaV** [comment]
For the record, I have the same problem. Windows Defender intelligence version 1.317.589.0

**Comment by ericzolf** [comment]
I still can't upload the file to Microsoft for some reason, not explained of course (must be a recommended practice of MS).

**Comment by krbvroc1** [comment]
Same issue... copied rdiff-backup 2.0.3 exe to another windows machine and it was removed/quarantined. Currently being flagged by 9 different virus engines.

Also, are we sure this is a false positive?

https://www.virustotal.com/gui/file/83f2788f4bc5b6879a1179774cd22fc6da4ada764b8e68c2fd2383d44e1e1ea7/detection

![image](https://user-images.githubusercontent.com/1335118/84176865-0c60d680-aa50-11ea-8d54-c5fab83e8827.png)

**Comment by ikus060** [comment]
This look bad and the only solution is to submit the file to each antivirus
as a false positive and wait

See here nsis as similar issue.
https://nsis.sourceforge.io/NSIS_False_Positives

**Comment by ericzolf** [comment]
I uploaded the ZIP file to virustotal and only 2 engines flag it as suspicious, whereas 8 (not 9 anymore) flag the executable as suspicious. It's not serious IMHO, it's the same executable, but they all detect something different...

As for submitting as false positive, I tried to do it for Microsoft and it failed, so if someone wants to try...

**Comment by ericzolf** [comment]
@ikus060 if you would finish #381 and I'd like to close #392 we could then release a new bugfix version, which might get rid of the issue?

**Comment by ericzolf** [comment]
I've uploaded the recent [v2.0.4rc0 exe-file to Virus Total](https://www.virustotal.com/gui/file/31bb693e75d15e919b9ed62b34a41515ca82eb81ef15e4fd079723c421b696d1/detection) and it is still detected as malware by 8 anti-virus, but at least not Microsoft... I really guess that it's just the fact that we have Python and a lot of its binary modules packed, which makes the heuristic(s) cry wolf.

This said, I'm not sure how to close the issue...

**Comment by ericzolf** [comment]
I pointed Virus Total at rdiff-backup 2.0.5 and entered the following comment:

> The linked file rdiff-backup is generated automatically through the pipeline of Travis CI and also automatically published to GitHub, without any human intervention, and hence without risk of infection on a corrupted PC (unless Travis CI or GitHub itself would be corrupted, which would be very conspicuous).
> 
> The file is sometimes detected as malware probably because it contains an embedded Python (if you hesitate what it is, it's a programming language and a runtime engine) to facilitate installation and usage under Windows.
> 
> While I can't completely exclude the slim possibility of an infection, as a maintainer of rdiff-backup, I can certify that we haven't deliberatly introduced any malware or spyware in our software, and that we are doing all reasonable efforts to avoid security issues.

See:

1. the URL https://www.virustotal.com/gui/url/0d3dc3930be6fda9b67c8eacaafc79f47b33d4e1d18f3185907b444059628af0
2. the ZIP file https://www.virustotal.com/gui/file/33c206a872ee125447c0f34726a9b5b0afec29b5394cd287a8c413cbad6203a6
3. the EXE file https://www.virustotal.com/gui/file/763fdef438d0a87484c448b428a93c409ee9f95cfd3595c7b4c12521f98d223d

Side note: VirusTotal has an API, perhaps we could use it to upload the URL/Files at build time even though I'm not sure what it exactly would give us and if it's worth the effort...

**Comment by ericzolf** [comment]
I also uploaded the EXE to Microsoft and to Sophos, no reaction yet from Sophos, but Microsoft with 1.321.1469.0 seems to be the opinion that rdiff-backup is safe:
![image](https://user-images.githubusercontent.com/3105685/90317418-b023a280-df29-11ea-84bf-7147dc0516c4.png)
Very strange...

**Comment by krbvroc1** [comment]
> I also uploaded the EXE to Microsoft and to Sophos, no reaction yet from Sophos, but Microsoft with 1.321.1469.0 seems to be the opinion that rdiff-backup is safe:
> ![image](https://user-images.githubusercontent.com/3105685/90317418-b023a280-df29-11ea-84bf-7147dc0516c4.png)
> Very strange...

Not really strange...as I reported above on June 10, I submitted rdiff-backup.exe to Microsoft as a false positive. They investigated, resolved the ticket, and it has not been flagged since. Unfortunately the same needs to happen with those other dozen of virus engine companies so they can investigate and 'whitelist it'. I am unsure how to even contact those other companies like McAfee, Sophos, FireEye, etc.

**Comment by ericzolf** [comment]
I read this but Virus Total still states that Microsoft doesn't like us, so I assumed that the new version 2.0.5 wasn't anymore in the whitelist of Microsoft, but then Microsoft tells me that everything is fine...

**Comment by ericzolf** [comment]
I haven't heard for a while from this one and there isn't much we can do anyway, hence closing. If the issue happened again, please ask for instructions on the mailing list before opening a new issue.
