### ISSUE TITLE
module 'errno' has no attribute 'EDEADLOCK'

### ISSUE THREAD

**Issue by northnose** [rdiff-backup/rdiff-backup#366]
Trying to perform an initial/clean backup from my Mac (High Sierra 10.13.6) to a Linux box consistently fails after a while with:

```
Sending back exception module 'errno' has no attribute 'EDEADLOCK' of type <class 'AttributeError'>: 
  File "/usr/local/Cellar/rdiff-backup/2.0.3/libexec/rdiff_backup/connection.py", line 400, in answer_request
    result = eval(request.function_string)(*argument_list)
  File "/usr/local/Cellar/rdiff-backup/2.0.3/libexec/rdiff_backup/connection.py", line 568, in readfromid
    return cls.vfiles[id].read()
  File "/usr/local/Cellar/rdiff-backup/2.0.3/libexec/rdiff_backup/iterfile.py", line 322, in read
    if not self.addtobuffer():
  File "/usr/local/Cellar/rdiff-backup/2.0.3/libexec/rdiff_backup/iterfile.py", line 349, in addtobuffer
    currentobj = next(self.iter)
  File "/usr/local/Cellar/rdiff-backup/2.0.3/libexec/rdiff_backup/backup.py", line 133, in get_diffs
    attach_snapshot(diff_rorp, src_rp)
  File "/usr/local/Cellar/rdiff-backup/2.0.3/libexec/rdiff_backup/backup.py", line 95, in attach_snapshot
    fileobj = robust.check_common_error(
  File "/usr/local/Cellar/rdiff-backup/2.0.3/libexec/rdiff_backup/robust.py", line 38, in check_common_error
    if catch_error(exc):
  File "/usr/local/Cellar/rdiff-backup/2.0.3/libexec/rdiff_backup/robust.py", line 68, in catch_error
    errno.ESRCH, errno.EINVAL, errno.EDEADLOCK,
```

From looking at the code, it seems `errno.EDEADLOCK` is being referenced in `robust.py`:
```
def catch_error(exc):
    """Return true if exception exc should be caught"""
    for exception_class in (rpath.SkipFileException, rpath.RPathException,
                            librsync.librsyncError, C.UnknownFileTypeError,
                            zlib.error):
        if isinstance(exc, exception_class):
            return 1
    if (isinstance(exc, EnvironmentError)
            # the invalid mode shows up in backups of /proc for some reason
        and ('invalid mode: rb' in str(exc) or 'Not a gzipped file' in str(exc)
        or exc.errno in (errno.EPERM, errno.ENOENT, errno.EACCES, errno.EBUSY,
                         errno.EEXIST, errno.ENOTDIR, errno.EILSEQ,
                         errno.ENAMETOOLONG, errno.EINTR, errno.ESTALE,
                         errno.ENOTEMPTY, errno.EIO, errno.ETXTBSY,
                         errno.ESRCH, errno.EINVAL, errno.EDEADLOCK,
                         errno.EDEADLK, errno.EOPNOTSUPP, errno.ETIMEDOUT))):
        return 1
    return 0
```

However it seems `EDEADLOCK` isn't a thing on my machine for some reason:

```
$ python3
Python 3.7.7 (default, Mar 10 2020, 15:43:27) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import errno
>>> errno.EDEADLOCK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'errno' has no attribute 'EDEADLOCK'
>>> errno.EDEADLK
11
```

OS X client is running rdiff-backup 2.0.3 from Homebrew.
Linux (CentOS 8) server is running rdiff-backup 2.0.0 from EPEL.

**Comment by ericzolf** [comment]
It seems a Mac specificity because under Linux, it works:

```
$ python 
Python 3.8.2 (default, Feb 28 2020, 00:00:00) 
[GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)] on linux
>>> import errno
>>> errno.EDEADLOCK
35
>>> errno.EDEADLK
35
>>> 
```

Note: I get the same result under Python 3.5 so I guess it's true under all versions.

I need to think how to fix it. For now, as a workaround, you can just try to remove the `errno.EDEADLOCK, ` from the list directly in the code (only on the Mac side).

**Comment by ericzolf** [comment]
OK, found it, e.g. http://man7.org/linux/man-pages/man3/errno.3.html -

>        EDEADLK         Resource deadlock avoided (POSIX.1-2001).
> 
>        EDEADLOCK       On most architectures, a synonym for EDEADLK.  On
>                       some architectures (e.g., Linux MIPS, PowerPC,
>                       SPARC), it is a separate error code "File locking
>                       deadlock error".
Meaning, we can't just get rid of it, we need to, and this for each signal which isn't POSIX (but it is the only one currently):
* create a list
* validate that the errno exists and add it (or not) to the list
This said, I'm not sure which criteria were used to create this list, so perhaps there is a smarter solution.

**Comment by northnose** [comment]
I deleted it and was able to finish the backup -- but should I be worried about a deeper issue? It doesn't look like this line of code is new, and I've never seen this issue before.

**Comment by ericzolf** [comment]
I have no clue of Mac but I don't think so, it looks rather genuine to me. Which version of rdiff-backup were you using before?

**Comment by zjw** [comment]
>     * This said, I'm not sure which criteria were used to create this list, so perhaps there is a smarter solution.

The criteria for the list, in the original developer's own words, is stated here:

https://lists.gnu.org/archive/html/rdiff-backup-users/2003-03/msg00114.html

That was the last message in a thread which resulted in the the addition of EDEADLOCK to the code in order to skip over files that were in use.

**Comment by ericzolf** [comment]
Thanks, I'm impressed, well spotted! Means we need to keep the signal, but add a test because not POSIX.
