### ISSUE TITLE
Found too many current_mirror incs doesn't say where

### ISSUE THREAD

**Issue by WolfgangFahl** [rdiff-backup/rdiff-backup#37]
When displaying this error message the path to the culprit directory should be included.

**Comment by WolfgangFahl** [comment]
This script is a  workaround:
`#!/bin/bash
# https://stackoverflow.com/questions/9157138/recursively-counting-files-in-a-linux-directory

#
# get the current mirrors
# param 1: filter
#
get_current_mirrors() {
  local l_filter="$1"
  for f in $(find . -name current_m* ) ; do 
    d=$(dirname $f)
    b=$(basename $f)
    case $l_filter in
      "dir") echo $d;;
      "file") echo $f;;
      *) echo $f
    esac
  done
}

#get_current_mirrors 
#get_current_mirrors file
get_current_mirrors dir | sort | uniq --count --repeated`

**Comment by ericzolf** [comment]
Adding `% Globals.rbdir.get_safepath()` to `assert len(curmir_incs) == 2, "Found too many current_mirror incs!"` in `src/rdiff_backup/Main.py` line 1100 will fix the issue. I'll do it once #60 is closed.
