### ISSUE TITLE
[BUG] Invalid Python download link in the Windows-DEVELOP.md file.

### ISSUE THREAD

**Issue by JirkaV** [rdiff-backup/rdiff-backup#377]
The verbal description suggests downloading Python 3.7.5 (32-bit) while the download link points to Python 3.7.3 (64-bit).

I'm pointing this out mostly because the documentation specifically says "Python 3.7.3 is not supported".

**Comment by ericzolf** [comment]
Thanks. Would you mind providing a pull request for this fix?

**Comment by JirkaV** [comment]
No problem - wasn't sure on the versions but used the docs text as a guidance.
