### ISSUE TITLE
rdiff-backup fails on gluster/hadoop volumes

### ISSUE THREAD

**Issue by seanfulton** [rdiff-backup/rdiff-backup#378]
I have been using rdiff-backup for years and it is awesome! Thank you for taking on this project.

As our network has exceeded the capacity of a single backup node, we've been trying to use different network-based filesystems as backup media. We tried Hadoop via NFS, but got errors like below. Now we're using GlusterFS, 7.5, and getting the same errors. The gluster volume works, all file operations on the volume seem to work, and rsync works flawlessly. But with an rdiff-backup, we get the errors below. This is with rdiff-backup 1.2.8 on CENTOS6

How did you call rdiff-backup, with which parameter:

rdiff-backup -v 9 r8168-8.011.00 /bigdrive/rdiff/test
Mon May 25 09:06:29 2020  Using rdiff-backup version 1.2.8
Mon May 25 09:06:29 2020  Found interrupted initial backup. Removing...
Mon May 25 09:06:29 2020  Unable to import win32security module. Windows ACLs
not supported by filesystem at r8168-8.011.00
Mon May 25 09:06:29 2020  escape_dos_devices not required by filesystem at r8168-8.011.00
Mon May 25 09:06:29 2020  -----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Mon May 25 09:06:29 2020  Making directory /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3
Mon May 25 09:06:29 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/5-_ a.snapshot.gz
Mon May 25 09:06:29 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/5-_ a.snapshot.gz
Mon May 25 09:06:29 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/uniᄉ
Mon May 25 09:06:29 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/uniᄉ
Mon May 25 09:06:29 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/:\"
Mon May 25 09:06:29 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/:\"
Mon May 25 09:06:29 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/A
Mon May 25 09:06:29 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/A
Mon May 25 09:06:29 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/foo
Mon May 25 09:06:29 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/foo
Mon May 25 09:06:29 2020  Making directory /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/hl
Mon May 25 09:06:29 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/hardlinked_file1
Mon May 25 09:06:29 2020  Hard linking /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/hl/hardlinked_file2 to /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/hardlinked_file1
Mon May 25 09:06:29 2020  POSIX ACLs not supported by filesystem at /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3
Mon May 25 09:06:29 2020  Unable to import win32security module. Windows ACLs
not supported by filesystem at /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3
Mon May 25 09:06:29 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/dir_inc_check
Mon May 25 09:06:29 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/dir_inc_check
Mon May 25 09:06:29 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/regfile
Mon May 25 09:06:30 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/regfile
Mon May 25 09:06:30 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/high_perms_file
Mon May 25 09:06:30 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/high_perms_dir
Mon May 25 09:06:30 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/high_perms_file
Mon May 25 09:06:30 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/high_perms_dir
Mon May 25 09:06:30 2020  Touching /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/symlinked_file1
Mon May 25 09:06:30 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/symlinked_file2
Mon May 25 09:06:30 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/symlinked_file1
Mon May 25 09:06:30 2020  escape_dos_devices not required by filesystem at /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3
Mon May 25 09:06:30 2020  Deleting /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3
Mon May 25 09:06:30 2020  Removing directory /bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3
Mon May 25 09:06:30 2020  Exception '[Errno 107] Transport endpoint is not connected: '/bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/hl'' raised of class '<type 'exceptions.OSError'>':
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/Main.py", line 334, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/fs_abilities.py", line 922, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/fs_abilities.py", line 171, in init_readwrite
    subdir.delete()
  File "/usr/lib64/python2.6/site-packages/rdiff_backup/rpath.py", line 1070, in delete
    self.conn.shutil.rmtree(self.path)
  File "/usr/lib64/python2.6/shutil.py", line 212, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib64/python2.6/shutil.py", line 221, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python2.6/shutil.py", line 219, in rmtree
    os.rmdir(path)

Mon May 25 09:06:30 2020  Fatal Error: Filesystem reports connection failure:
[Errno 107] Transport endpoint is not connected: '/bigdrive/rdiff/test/rdiff-backup-data/rdiff-backup.tmp.3/hl'

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

**Comment by ikus060** [comment]
I'm not sure of the exact reason of this error message: `Fatal Error: Filesystem reports connection failure: [Errno 107] Transport endpoint is not connected` Seams related to the FileSystem layer an not much to rdiff-backup it self. Reading a bit about GlusterFS this might be an issue with multiple lock.

But to but honest, I'm more curious about your initial issue. You are saying you are maxing out the network of your backup server ? And I'm a bit surprise! As most installation I'm doing are maxing our the CPU way before maxing our the bandwidth. So I'm a bit curious about what is your setup and what are you backup up.

Also, knowing a bit about GlusterFS, it's not very well suited if you want to boost the performance of rdiff-backup since GlusterFS usually slow down as you are adding more servers. Unless you have a dedicated cluster interconnected with 10GB or more.

I can't tell about Hadoop since I've never experiment with it.

**Comment by seanfulton** [comment]
Well, that's what I need to know--what is rdiff-backup complaining about? We've got no problems with gluster. The capacity issue is that the backup server is out of space at 40TB. I am using gluster to spread that storage across multiple nodes. The performance is fine. But the error is not. There's nothing wrong with the glusterfs, so what is rdiff-backup complaining about?

**Comment by ikus060** [comment]
To be very picky about the wording. The error message is raised by the OS.
It's not an error generated by rdiff-backup itself. It might be interesting
to check your operating system logs. Syslog, glusterfs and dmesg logs may
or may not have more detail about the exception.
Could you check?

**Comment by ericzolf** [comment]
Sounds like your issue: https://bugzilla.redhat.com/show_bug.cgi?id=1335538
Searching for the error message and gluster, I find quite a lot of those kind of issues.
The solution would probably be to introduce retries on ENOTCONN errors, but I'm reluctant to add so much complexity to solve an issue due to what looks like a broken system.

**Comment by ikus060** [comment]
I should I put the reference. This is exactly what I found too.
And I support your point, I would not add a retrial mechanism.

**Comment by ericzolf** [comment]
The linked bug states that it's fixed with glusterfs-4.1.3 but there are four more open issues with this: https://bugzilla.redhat.com/buglist.cgi?quicksearch=Transport%20endpoint%20not%20connected
Anyway, without more arguments from your side @seanfulton I would soon close the issue because we don't see a way/need to address it.

**Comment by ericzolf** [comment]
OK, closing by lack of information. Feel free to re-open if you're convinced that we can do something about it. Notice also that we're not supporting any more v1.2.8 but switched to v2.0.3. You might want to consider the upgrade, even though I don't see any reason it would solve your issue.
