### ISSUE TITLE
Crash with AssertionError while backing up to exFAT partition

### ISSUE THREAD

**Issue by rik-shaw** [rdiff-backup/rdiff-backup#38]
Using rdiff-backup 1.2.8 (Ubuntu / Debian repositories) and 1.3.3 (built from source), when backing up to an exFAT formatted partition it crashes.  From the crash output, it is related to this line:

rdiff_backup/fs_abilities.py:
assert not upper_a.lstat()

https://github.com/sol1/rdiff-backup/blob/8ccc5a3b44c996ecd810f8d5d586d0da6435cc32/rdiff-backup/rdiff_backup/fs_abilities.py#L325

If I *comment out* that line (so no assert command is run), then rdiff-backup will complete without error using an exFAT partition. I do not understand why rdiff-backup crashes on exFAT but other non-case-sensitive fomats such as FAT32 and NTFS do not crash. I wonder if that line is essential or what the implication would be if it were removed?

The full error is as follows (from source at savannah it is line 304, instead of line 325 here, since I was not successful in building from source with the current github code):

```
Message: Found interrupted initial backup. Removing...
Exception '' raised of class '<type 'exceptions.AssertionError'>':
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 306, in error_check_Main
    try: Main(arglist)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 326, in Main
    take_action(rps)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 282, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 336, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 959, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 156, in init_readwrite
    self.set_case_sensitive_readwrite(subdir)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 304, in set_case_sensitive_readwrite
    assert not upper_a.lstat()

Traceback (most recent call last):
  File "/usr/local/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 306, in error_check_Main
    try: Main(arglist)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 326, in Main
    take_action(rps)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 282, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 336, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 959, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 156, in init_readwrite
    self.set_case_sensitive_readwrite(subdir)
  File "/usr/local/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 304, in set_case_sensitive_readwrite
    assert not upper_a.lstat()
AssertionError
```

**Comment by ericzolf** [comment]
The truth is that rdiff-backup has issues with other (more or less) case insensitive file systems, see #11, so we should improve the way we detect and treat those file systems in the most possible safe way.

This issue will probably get closed together with #11 but I keep it separate for now as there is a slight chance that the solution will be different.

**Comment by ottok** [comment]
Hello @rik-shaw  !

The code base has been rewritten for Python 3 and there will be no further releases for the 1.x series in Python 2 anymore. Could you please help our efforts and test again with the latest development version (https://github.com/rdiff-backup/rdiff-backup#installing-the-latest-development-version) if you can still reproduce this and provide us with a test case (steps on how to reproduce the issue) that applies for latest development version?

With your help, if we can reproduce this problem still with the 2.x code base if might be fixed it in upcoming 2.x series releases.

**Comment by ericzolf** [comment]
The issue is still there in 2.0.3.

**Comment by ericzolf** [comment]
That's a funny one and has nothing to do with rdiff-backup, I can reproduce the issue independently of it, on an exfat volume:

1. `touch A; rm a; stat A` -> no error!!! stats are shown
2. `touch A; rm A; stat A` -> No such file error
3. `touch A; rm a; sleep 0.9; stat A` -> still no error, stats are shown
4. `touch A; rm a; sleep 1; stat A` -> No such file error, at last after one full second!

It sounds to me like there is a timer of 1 second in the exFAT driver before the names are synced. I tried to `sync` in-between but that didn't help. We could introduce a sleep of 1 second also in the code, but that's very ugly. I couldn't find anything in the man-pages to change the behaviour of exfat. I'll plug a bug towards the driver and see what the developers have to say. Perhaps they'll have an idea how to workaround/overcome.

**Comment by ikus060** [comment]
What if you call fsync?

**Comment by ericzolf** [comment]
That's the sync I was describing, no effect sadly.

**Comment by ericzolf** [comment]
OK, I thought about it and even if I could easily fix the test with a sleep 1, I can't guarantee that the rest of the code will work properly under all circumstances with such a flaw in its implementation, so I will improve the error handling and close the bug with it, but not try to fix the test.

**Comment by brainchild0** [comment]
> I'll plug a bug towards the driver and see what the developers have to say.

Is this issue still open upstream? Would you provide a link?

Is the [arter97/exfat-linux](https://github.com/arter97/exfat-linux) project relevant to resolving full support for exFAT?
