### ISSUE TITLE
[BUG] incorrect use of assert statements throughout the rdiff-backup code

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#398]
According to https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement the assert statements are skipped when the python code is compiled optimized and `__debug__` is ignored. The issue here is that our code is using assert 263 times (!) and in ways which are not optional and would break the code in optimized mode. On top, many of those assert statements fail without proper error message.

So we should get rid of all those asserts and replace them with proper error messages and exit statements. My idea would be to create a `log.assert` function which would take two parameters like the assert statement does, but where the error message isn't optional.

**Comment by ikus060** [comment]
Hum, I've been aware of this assert thing as being optional. Not sure all
our assert need to be replaced by real validation or exception.

Also take note. In practice, none of the default python are compiled to
skip the assert.

So it's an issue, but not a critical one.

**Comment by dbaarda** [comment]
Note that librsync makes extensive use of assert statements for debug
precondition/postcondition/invariant contract style checking.

This means with debug builds  it's fairly good at detecting programming
errors in itself and programs using its API, but its also much slower. You
probably want to make sure NDEBUG is defined for release builds you have
good confidence in.

**Comment by ikus060** [comment]
Donovan, librsync is using the assert keyword in c or c++. Which are not
the same as assert statement in python.

In c++ the assert statement are usually skip for release where as in python
the assert statement depend of the way python was compiled.

**Comment by dbaarda** [comment]
Ah, yes, python asserts. I assume you are using python with a release build
of librsync then. If you ever had doubts about librsync working it might
help debugging by using a debug build with trace turned on.

I'd still recommend a similar approach to python asserts as librsync's;
only use asserts for checking for possible program errors, never for
validity checking of potentially untrusted/corrupted inputs. Also never use
explicit checking/handling for program errors, only use asserts. This
ensures that program errors are more quickly highlighted and identified
with asserts enabled, but correct programs still work correctly and run
fast with `python -o`.

Precondition/Postcondition/Invariant contracts for each function/method are
obvious candidates for asserts.

**Comment by ericzolf** [comment]
This is definitely not the way (python) asserts are used in their majority today in rdiff-backup, and even if they are used the right way, they should generate a meaningful error message. Not urgent, I agree, but something to improve the code quality (which is my current priority).
