### ISSUE TITLE
[BUG] mirror_metadata are compressed even with --no-compression

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#402]
Even when running `rdiff-backup --no-compression`, mirror_metadata files are created as gz file.

rdiff-backup 2.0.3

Looking at the way MetadataFile compression is handled, it's not using the global compression variable to termine if the files should be created with or without compression.

**Comment by ericzolf** [comment]
In my opinion, this isn't a bug: the no-compression is a flag for the data not for the metadata, e.g. when you know that your data can't be compressed. The metadata has a good compression ratio hence it's always worth compressing it.

I guess you'd like this feature for the metadata to be easier to analyze, but that would be an enhancement with a different parameter.

**Comment by ikus060** [comment]
When using the no compression switch diff files, file statistics, sessions
statistics, ACL and other are not compressed...

I'm using this switch where I install rdiff-backup on a file system that
compress files directly. The FS is doing the job faster and better. Like
zfs.

**Comment by ericzolf** [comment]
OK, convinced.

**Comment by ericzolf** [comment]
I have a branch which (almost) fixes the issue at https://github.com/rdiff-backup/rdiff-backup/tree/ericzolf-fix-meta-compress-402 *BUT* it breaks the backward compatibility of the repo format with rdiff-backup 2.0, so I hesitate to introduce it in version 2.2, I'd prefer to reserve it for version 3.0+.

**Comment by ikus060** [comment]
I'm fine with this. It's not a show stopper to have the file compressed by rdiff-backup.

Thanks !
