### ISSUE TITLE
[BUG] --verify never finishes on repository with missing files

### ISSUE THREAD

**Issue by OneLineTwoBugs** [rdiff-backup/rdiff-backup#406]
## Bug summary

The --verify option never finishes when some files have been removed from the repository. Also, it uses quite a bit of memory. In my case, I'm running it on a 700MB repository with 3200 files and 711 folders. The largest couple of files are 180MB, 90MB, 80MB, 30MB.

Running --verify on the non-corrupted respository finishes within 1.5 seconds. Running it after deleting some files from the repository, it takes >10 minutes before I aborted. It does however find the missing files and reports the errors.

## Version, Python, Operating System

Debian bullseye, amd64
```
2020-06-19 09:33:23.912376 +0200  <CLIENT-734797>  Using rdiff-backup version DEV
2020-06-19 09:33:23.912506 +0200  <CLIENT-734797>       with cpython /usr/bin/python3 version 3.8.3
2020-06-19 09:33:23.920785 +0200  <CLIENT-734797>       on Linux-5.4.0-4-amd64-x86_64-with-glibc2.29, fs encoding utf-8

```

## rdiff-backup call

```
rdiff-backup --verify -v9 km2019/
```

## What happened and what did you expect?
The command never finishes after listing the missing files. Even with -v9 there is no more output. It uses 100% of one CPU and memory consumption continues to grow slowly (>1GB after 10 minutes)

**Comment by ericzolf** [comment]
If you could write the smallest repeater you can (create a source structure, backup it, corrupt the repo, and verify), that would be great and would help the fixing a lot (and spare me a lot of time, starting from zero). The repeater can be in whichever language you see fit, bash, python or even pseudo-code.

**Comment by ericzolf** [comment]
No more feedback since more than one year, closing.
