### ISSUE TITLE
[ENH] 

### ISSUE THREAD

**Issue by KlockiLego** [rdiff-backup/rdiff-backup#409]
Is there a chance to prepare rdiff-backup 2.x.x packages for older versions of debian?

http://ppa.launchpad.net/rdiff-backup/rdiff-backup-backports/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]

Is it not advisable to use the new version of rdiff-backup and should I stay with version 1.2.8-7?

**Comment by ericzolf** [comment]
No, sorry, we only support Python 3.5+ and jessie has only Python 3.4 which is out of support anyway.
