### ISSUE TITLE
[ENH] get rid of setuptools as runtime dependency

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#418]
## Is your feature request related to a problem? Please describe.

We have identified that we need to have setuptools _at runtime_ in order to have `rdiff-backup --version` spit out the correct version instead of simply `DEV`. Our packagers find that pulling 3MB for this small feature isn't acceptable, on the other hand our developers.

## Describe the solution you'd like

I want all team members to fill well with the solution we choose while not impacting the efficiency and the precious little spent by volunteers to develop rdiff-backup.

## Describe alternatives you've considered

This issue is here for everybody to propose and discuss alternatives.

## Additional context

This is a follow-up enhancement to the issue #305 but is to be considered independently of any specific packaging format (DEB or RPM).

**Comment by telsin** [comment]
Having been bitten by this, and having had it produce a series of difficult to track down errors, it should be fixed. It's not acceptable to have a situation where the application may not return the correct version information based on the presence, absence, or possibly version of external libraries. If it's self contained, it should be self contained to the point where it can return it's own version information. At least if it's going to print warnings based on said information, at any rate. I'm strongly in favor of removing the run time dependency on an external library for simple version information.

**Comment by ericzolf** [comment]
First some numbers from my side, based on the [comment from @ikus060 ](https://github.com/rdiff-backup/rdiff-backup/issues/305#issuecomment-654344243), due to the fact that I had no clue about what we're talking about, so some simple statistics based on Fedora 32:

```
$ sudo dnf repoquery --whatrequires python3 |  wc -l
5460
$ sudo dnf repoquery --whatrequires python3-setuptools |  wc -l
959
```

So, very roughly, 20% of the Python 3 packages require also setuptools at runtime, meaning we're not a very seldom exception and there is a good chance that a user installs setuptools not only for rdiff-backup. On my own PC, I would get 297 packages removed if I try to remove python3-setuptools (18 of them are directly dependent).

Not knowing if @ottok counted also dependencies in the 3MB he told, I check it as well starting a fresh podman:

```
$ podman run -it fedora:32 bash
[root@82b178631058 /]# rpm -qa | grep python3
python3-3.8.2-2.fc32.x86_64
python3-hawkey-0.47.0-1.fc32.x86_64
python3-rpm-4.15.1-3.fc32.1.x86_64
python3-libs-3.8.2-2.fc32.x86_64
python3-libcomps-0.1.15-1.fc32.x86_64
python3-libdnf-0.47.0-1.fc32.x86_64
python3-gpg-1.13.1-7.fc32.x86_64
python3-dnf-4.2.21-1.fc32.noarch
[root@82b178631058 /]# dnf install python3-setuptools
[...]
Dependencies resolved.
==============================================================================================================================================================================================================================================
 Package                                                          Architecture                                         Version                                                     Repository                                            Size
==============================================================================================================================================================================================================================================
Installing:
 python3-setuptools                                               noarch                                               41.6.0-2.fc32                                               fedora                                               588 k

Transaction Summary
==============================================================================================================================================================================================================================================
Install  1 Package

Total download size: 588 k
Installed size: 2.9 M
```
So no further dependencies and similarly 3MB to consider in our thinking.

**Comment by ericzolf** [comment]
@telsin we all agree that it's not optimal but the question is if the alternatives aren't worse. We arrived to this situation because we had requirements and, as main developer, I appreciate a lot the workflow it allows me to have. And, honestly, 3MB is nowadays not exactly a show-stopper. Self-containment has never been an objective, at least not that I would know of, it already depends on a few external libraries to work, so IMHO not a valid argument.

While I write those lines, I realise/remember that setuptools is a dependency of pip, limiting the impact of this discussion solely to users not installing via pip, but only via yum/apt.

**Comment by telsin** [comment]
Yes, and I don't mind having setup tools installed if it's a dependancy, the space needs are not a concern for me. 
It's probably worth a test against a system with multiple pythons installed to ensure it doesn't return bad results in some cases. As long as you don't get a case where some combo of installed components returns errors, go for the simplest solution.

**Comment by ericzolf** [comment]
The only issue is that you get "DEV" as version if setuptools isn't installed, which is rather cosmetic.

**Comment by telsin** [comment]
The big annoyance for me wasn't printing "DEV", it's that it then complains if the local version and remote version doesn't match. DEV might be easier to track down now, but it's not obvious why it's printing this error message. And if you have a lot of automated backups running, you get a lot of warnings.

**Comment by frankcrawford** [comment]
@telsin the message about version differences is important, because of how rdiff-backup does remote calls.  This is a warning that their may be API differences and hence failures during execution.

This is a good reason why we need to get the version number right.

**Comment by telsin** [comment]
@frankcrawford I agree, it's a good message when it's correct. But when the version being checked against was "DEV", even though it was actually a version that matched the backup targets machine (2.0.3), the error isn't correct, is it? And it was not easy to track down, since everything else (yum, etc) thought the versions matches, and some machines with the save repo version would return the error and some wouldn't.

**Comment by frankcrawford** [comment]
I agree that the version coming out as "DEV" is a bug at least for distributed versions.  I'd only expect to see it from a locally built version of rdiff-backup, generated directly from git repo.

We have a workaround in place currently (install setuptools), and eventually may have a better solution.

**Comment by ericzolf** [comment]
Good news, we have a new option for getting the version: https://packaging.python.org/guides/single-sourcing-package-version/ (point 5, importlib metadata). The package is part of Python 3.8 and, for older Python versions, there is a compatible module available as [PyPI module](https://pypi.org/project/importlib-metadata/#files) which is roughly 30kB big.

I created a _draft_ pull request using this new library at #427 

This raises a few issues though:

- importlib-metadata isn't packaged for Fedora and possibly other distros (Debian bullseye has it). It's only an issue if targeting Python < 3.8 but still. Fedora 32 and Debian Bullseye are already on Python 3.8 so no sweat here.
- because I can't define alternative dependencies (either importlib-metadata or setuptools), even if the user has already installed setuptools, importlib-metadata will nevertheless be installed under older versions of Python. Given the size, no big deal IMHO.

If everybody accepts the consequences, I can adapt the documentation according to the changes made, and "un-draft" the PR. I would nevertheless do it after the upcoming bug-fix release, as I feel that changing package dependencies isn't fit for a bug-fix release (unless it's super important to you).

Opinions? Add emoticons to this comment:
* a thumbs up if you think, the PR is the way to go,
* or a thumbs down if you are for the status-quo with runtime dependency on setuptools, 
* and _additionally_ a rocket if you think that the PR should absolutely be in this bug-fix release, but then argument it

**Comment by frankcrawford** [comment]
While it may be in Fedora 32, etc, the bigger usage is RHEL 7, and we may need to make sure importlib-metadata is also in EPEL.

I will see what I can find out, but would also request that you hold this off until after you release rdiff-backup 2.0.4.

**Comment by frankcrawford** [comment]
Just to update on my comment about it not being in RHEL/EPEL 7, I've just arranged for permission to add it to EPEL 7.
