### ISSUE TITLE
rdiff-backup lacks sparse file support

### ISSUE THREAD

**Issue by sid3windr** [rdiff-backup/rdiff-backup#42]
Today I noticed something was off with the sizes of some of our backups: a VM with a 20GB hard drive had a 450+GB backup. Turns out /var/log/lastlog is a 458GB sparse file on a number of systems and rdiff-backup backs up the whole thing.

A quick Google suggests this was discovered [in 2005 already](https://savannah.nongnu.org/support/?102559), and a [patch was written in 2011](https://lists.gnu.org/archive/html/rdiff-backup-users/2011-01/msg00000.html), but unfortunately due to maintainer sleep this never got into rdiff-backup code. May be useful to integrate in the repository now?

If it helps I could make a pull request but as it's posted there it's not actually my code...

**Comment by ericzolf** [comment]
Should have been fixed with PR #248 - I'm closing but feel to re-open if you find out that it's not the case.
