### ISSUE TITLE
Remove Hound CI from Pipeline

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#432]
I have never seen the "hound" do anything useful and now it's blocking my pipeline on #431 for no apparent reason.
From the description, it's anyway doing duplicate work with "flake8" so we definitely won't lose any feature. Just wanted to be sure I don't oversee anything before I shut it off.

**Comment by ericzolf** [comment]
I browsed quickly through the code at https://github.com/houndci/hound and it doesn't do anything else than running flake8 with yet another config file, undocumented as far as I could go quickly through the code.

So, unless someone stops me with very good arguments, I'll "unleash the dog" very soon as being useless.

**Comment by ikus060** [comment]
Isn't our flake8 already in place in tox ?
If our code is not flake8 compliant, the build fail. Right ?

**Comment by ericzolf** [comment]
Exactly, we have already flake8 in tox, I had a few cases where the job also failed because of flake8 in tox, but never failed in Hound (until today, but it was a hang, not a fail). In other words, the dog never barked at me, even if there was a fault, hence useless.

**Comment by ikus060** [comment]
Isn't it @ottok who added Hound recently ? 
We should wait for is input.
On my side, I don't mind. As long as we have flake8 running in our pipeline.

**Comment by ericzolf** [comment]
No, hound was there more or less from the beginning on.

**Comment by ericzolf** [comment]
Hound has just blocked #428, I remove it.
