### ISSUE TITLE
macOS: '[Errno 1] Operation not permitted' linking PkgInfo

### ISSUE THREAD

**Issue by wmertens** [rdiff-backup/rdiff-backup#44]
On macOS, it seems that Apple disallows hardlinking files inside .app directories.

This happens at https://github.com/sol1/rdiff-backup/blob/8ccc5a3b44c996ecd810f8d5d586d0da6435cc32/rdiff-backup/rdiff_backup/backup.py#L568

I'm not entirely certain why the temp file is hardlinked and not moved. Would it be possible to fall back onto a move/copy?

**Comment by ericzolf** [comment]
Could someone with MacOS check if this issue is still valid? If not, I'll close the issue (MacOS isn't officially supported after all, I'm happy to try to make it work but _I_ won't invest too much time in it).

**Comment by wmertens** [comment]
Well, not me anymore in any case :) i suppose we can choose this since no-one else chimed in in all this time.
