### ISSUE TITLE
[BUG] PUA

### ISSUE THREAD

**Issue by DillFrescott** [rdiff-backup/rdiff-backup#449]
## Bug summary

Detected as ML PUA by Sophos Home Antivirus. This may be intentional after reading up on what is considered a PUA. I believe it indeed falls under some of the categories. What do you think?

https://community.sophos.com/kb/en-us/127332

**Comment by ericzolf** [comment]
It's basically the same issue as #365 

It's quite surely a false positive, but there is not much we can do about it.
