### ISSUE TITLE
vfat misidentified as case sensitive

### ISSUE THREAD

**Issue by LeonardMichlmayr** [rdiff-backup/rdiff-backup#45]
I have just noticed some trouble with rdiff-backup on vfat (as target fs) in linux. The filesystem is not completely case-insensitive when mounted with the option iocharset=utf8. 
$ touch A ; touch a
will result in an error, but
$ touch a; touch A
will not.

$ stat a
will not recognize the file A, but
$ touch a
is not allowed to create the file a if A exists.

rdiff-backup should always assume case insensitive behavior on vfat! If not, you will run into trouble, as soon as there are two files with the same lowercase representation. Currently, rdiff-backup mistakes vfat as case sensitive!

_Originally posted by @LeonardMichlmayr in https://github.com/sol1/rdiff-backup/issues/11#issuecomment-490814664_

**Comment by ericzolf** [comment]
Let me close this bug as duplicate and we'll work on it with #11
