### ISSUE TITLE
PPA for Ubuntu 16.04 not working?

### ISSUE THREAD

**Issue by hameno** [rdiff-backup/rdiff-backup#460]
I'm trying to install 2.0 on 16.04 systems but apt doesn't show the new version after adding the ppa

```
# cat /etc/apt/sources.list.d/rdiff-backup-ubuntu-rdiff-backup-backports-xenial.list
deb http://ppa.launchpad.net/rdiff-backup/rdiff-backup-backports/ubuntu xenial main
# deb-src http://ppa.launchpad.net/rdiff-backup/rdiff-backup-backports/ubuntu xenial main
```

```
# apt update
Hit:1 http://mirror.hetzner.de/ubuntu/packages xenial InRelease
Hit:2 http://mirror.hetzner.de/ubuntu/packages xenial-backports InRelease
Hit:3 http://mirror.hetzner.de/ubuntu/packages xenial-updates InRelease
Hit:4 http://mirror.hetzner.de/ubuntu/security xenial-security InRelease
Hit:5 http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.1/ubuntu xenial InRelease
Hit:6 http://repo.percona.com/apt xenial InRelease
Hit:7 http://de.archive.ubuntu.com/ubuntu xenial InRelease
Hit:8 http://ppa.launchpad.net/gluster/glusterfs-3.12/ubuntu xenial InRelease
Hit:9 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:10 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:11 http://ppa.launchpad.net/rdiff-backup/rdiff-backup-backports/ubuntu xenial InRelease
Hit:12 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:13 http://apt.puppetlabs.com xenial InRelease
Ign:14 https://artifacts.elastic.co/packages/5.x/apt stable InRelease
Hit:15 https://artifacts.elastic.co/packages/5.x/apt stable Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
58 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

```
# apt list -a rdiff-backup
Listing... Done
rdiff-backup/xenial,xenial,now 1.2.8-7 amd64 [installed]
```

According to https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-backports?field.series_filter=xenial there should be a backport available

**Comment by hameno** [comment]
Found the reason, the builds failed. Could someone fix that?

**Comment by ericzolf** [comment]
@ottok can you have a look at it?

**Comment by ottok** [comment]
This is the status of the backport packages:
https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-backports/+packages
![image](https://user-images.githubusercontent.com/668724/92865554-258a7200-f407-11ea-9927-29deb97d0792.png)

There has never been a working Xenial backport, as it requires so many dependencies not available in Ubuntu 16.04 LTS (Xenial).

Current build failure in https://launchpadlibrarian.net/492363098/buildlog_ubuntu-xenial-amd64.rdiff-backup_2.0.5-1+debhelper9~ubuntu16.04.1~ppa1_BUILDING.txt.gz is 
```
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 226, in <module>
    setup_requires=['setuptools_scm'],
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 19, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 102, in get_version
    version = _do_parse(root, parse)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 80, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % root)
LookupError: setuptools-scm was unable to detect version for '/<<PKGBUILDDIR>>'.

Make sure you're not using GitHub's tarballs (or similar ones), as those don't contain the necessary metadata. Use PyPI's tarballs instead.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
E: pybuild pybuild:274: clean: plugin distutils failed with: exit code=1: python3.5 setup.py clean 
dh_auto_clean: pybuild --clean -i python{version} -p 3.5 --dir . returned exit code 13
debian/rules:7: recipe for target 'clean' failed
make: *** [clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
```

Unless there is some huge interest, I don't think it makes sense for me to invest more time in Xenial backports.

**Comment by ottok** [comment]
Related: #330, #333 and https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/migration.md

To cope with upgrades, you can install the 1.x version on a newer Ubuntu host from https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-1-compat and then backup Xenial -> newer. Once you don't have any Xenial hosts left, you can stop running the 1.x version completely.

This is an open source project. Contributions to improve the README and other documentation is welcome, and your "fresh eyes" could be very useful in producing us better documentation on how to upgrade from older versions.

**Comment by hameno** [comment]
I went with a pip install on 16.04 and upgraded a few remaining 14.04 hosts

**Comment by xastor** [comment]
I got bitten by this too, I was expecting the backports repo to contain actual backports.  Worked around this using pip install.

**Comment by mvoorhis** [comment]
I'd suggest removing the xenial directory from this repo so that people don't need to struggle with installation, find this bug report, and then discover that it won't be fixed.  Like xastor I was thrown because I read the installation instructions for rdiff-backup, followed those instructions and then got no new software.  Had the instructions said "if you're running Ubuntu-16.04, you've got to upgrade to v18.04." I would have done that instead of wasting time trying to get this repo working.

**Comment by vguna** [comment]
Yup, same here like @mvoorhis.

**Comment by bhaines** [comment]
Burned four hours only to learn the promised backports were never backported like @mvoorhis.

**Comment by ericzolf** [comment]
Sorry to hear this.
@ottok could you remove the xenial repo as suggested previously? And then I guess we could close the issue.

**Comment by ericzolf** [comment]
If I don't get news from this before the end of the holiday season, I'll close the issue. Xenial ist old enough to not be relevant anymore.

**Comment by ericzolf** [comment]
End of the holiday season, closing!

**Comment by mitar** [comment]
I was also burned by this. README lists PPA with backports, you go there, it lists that Xenial is on the list, great, you follow instructions and nothing. No error, just no package. It [even lists that Xenial is supported](https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-backports?field.series_filter=xenial).

It took me quite some time to figure out to search for an issue here.

Please remove all info that Xenial is supported from PPA if this is not true. Not to list Xenial with no packages.

**Comment by ottok** [comment]
@mitar Which README are you referring to? Xenial was supported last time I checked and I still see it e.g. at https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-backports?field.series_filter=xenial

**Comment by mitar** [comment]
> Xenial was supported last time I checked and I still see it e.g. at https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-backports?field.series_filter=xenial

That is exactly the problem. Can you simply remove the Xenial from the PPA? I do not have permissions to contribute that.
