### ISSUE TITLE
Add Centos 7 to distribution list

### ISSUE THREAD

**Issue by oktayaa** [rdiff-backup/rdiff-backup#461]
I recently did a yum update on Centos 7 (7.8.2003) which seems to have upgrade rdiff to 2.0.5 .  You might want to list this on the github entry page for the project.

Of course my backup repo server is still running a 1.x version and can't work with that particular server anymore which makes me think Centos should really have not done this automatically.

**Comment by ericzolf** [comment]
We're dependent on https://repology.org/project/rdiff-backup/report to do something about it and can't change the list ourselves. Thanks for reporting though.

As a side remark, the package came quite surely from the EPEL and not directly from CentOS, which is why the distribution isn't reported.

**Comment by oktayaa** [comment]
I do have EPEL. That must be it. Thanks.

**Comment by frankcrawford** [comment]
Yes it is part of EPEL 7 & 8.
