### ISSUE TITLE
[BUG] Option --max-file-size changed behaviour

### ISSUE THREAD

**Issue by oyvindstegard** [rdiff-backup/rdiff-backup#466]
## Bug summary

Rdiff-backup recently changed behaviour with regard to option `--max-file-size`. This option is specifically described as an exclusion option in the manual page, but when I use it in scripts, in combination with other exclusion rules, the following error occurs:

```
Fatal Error: Last selection expression:
    Maximum size 10240000000
only specifies that files be included.  Because the default is to
include all files, the expression is redundant.  Exiting because this
probably isn't what you meant.
```

## Version, Python, Operating System

```
2020-09-26 13:23:55.838421 +0200  <CLIENT-25440>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
2020-09-26 13:23:55.834978 +0200  <CLIENT-25440>  Using rdiff-backup version 2.0.6.dev22
2020-09-26 13:23:55.835072 +0200  <CLIENT-25440>        with cpython /usr/bin/python3 version 3.6.9
2020-09-26 13:23:55.838339 +0200  <CLIENT-25440>        on Linux-5.4.0-47-generic-x86_64-with-Ubuntu-18.04-bionic, fs encoding utf-8

```

## rdiff-backup call

How did you call rdiff-backup, with which parameter:

```
/usr/bin/rdiff-backup --exclude-if-present .NOBACKUP --exclude-if-present CACHEDIR.TAG --exclude-device-files --exclude-fifos --exclude-sockets --print-statistics --exclude-globbing-filelist <some-exclude-list-file> --exclude-globbing-filelist <some-exclude-list-file> --max-file-size 10240000000 --remote-schema '%s' 'nice -n +19 sudo /usr/bin/rdiff-backup --server --restrict-read-only /'::'/' '<some-dest-dir>'
```

## What happened and what did you expect?

I expected `--max-file-size` to exclude files with size above the specified size, and this has worked fine with rdiff-backup for years.

## More information

It only seems to happen when the remote server uses rdiff-backup v2.0.6-dev22, while remotes with rdiff-backup 2.0.0 still work OK. (Client is always v2.0.6-dev22.)

**Comment by ericzolf** [comment]
Can you reproduce the issue with v2.0.5? Version v2.0.6 has never been released, it's still important to fix it, but it would give us  a better idea of when it appeared.

**Comment by oyvindstegard** [comment]
I follow this PPA for my Ubuntu 18.04 hosts (including the backup server itself):
https://code.launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-development/

According to my backup server logs, around 12 September, rdiff-backup got upgraded from 2.0.6-dev6 to 2.0.6-dev22, at which point the error started occuring for all hosts running the newer version.

Other hosts running Ubuntu 20.04 use the standard package of rdiff-backup, which is at version 2.0.0, those were OK, despite the rdiff-backup upgrade on the backup server.

I currently work around it by reordering options so that `--max-file-size` comes first in the argument list. That seems to work, although I have not confirmed that the option still has the desired effect. (I monitor mirror sizes, so I will notice if it suddenly starts backing up huge files above the limit.)

**Comment by ericzolf** [comment]
Yeah, but the commit hashes are not in the main repo... I could only count the "dev" steps (6 or 22) and make an educated guess.
@ottok do you have a better idea and/or know why the commits are not in the repo?

**Comment by oyvindstegard** [comment]
Yes, I noticed this as well. Unfortunately, I failed to find a logical link between the PPA build logs for respective packages and actual rdiff-backup git commit refs used as source tree.

**Comment by oyvindstegard** [comment]
At least it is very easy to reproduce the issue.

Given a source directory tree:
```
source/1k
source/2k
source/ex/exclude-me.txt
```
where files `1k` and `2k` have sizes one and two kilobytes respectively.

Invoking rdiff-backup like this:
```
rdiff-backup --max-file-size 1024 --exclude source/ex source/ dest/
```
works fine and yields the following files in `dest/`:
```
dest/1k
dest/rdiff-backup-data/
```

But if putting `--max-file-size 1024` after the `--exclude`, gives the error:
```
rdiff-backup --exclude source/ex --max-file-size 1024 source/ dest/
Fatal Error: Last selection expression:
    Maximum size 1024
only specifies that files be included.  Because the default is to
include all files, the expression is redundant.  Exiting because this
probably isn't what you meant.
```

So at least my work-around is OK wrt. excluding large files :smile_cat:, since the `2k` file is not included.

**Comment by ericzolf** [comment]
OK, I'll look into it once i'll refactor the file selection approach, we have a few issues with it. Thanks so much for the repeater.

**Comment by ericzolf** [comment]
Using `git diff 385ebe3 1ef7c45` (the `g` in front of the Debian versions most probably stands for Git) I think I found the issue:

```
-        sel_func.exclude = 1
+        sel_func.exclude = Select.EXCLUDE
```
whereas `Select.EXCLUDE` is defined as `0` and not `1`... I still need to find an elegant way to fix the code because writing `sel_func.exclude = Select.INCLUDE`, though it would probably fix the issue, wouldn't make any sense.
