### ISSUE TITLE
Create a CI pipeline

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#48]
We should create a CI pipeline that runs on every commit and every pull request.

## What tests to run?

The new Python 3 branch introduces the Tox testing framework, so we should at least run Tox.

Tox should be extended to test as much as possible. We need to look into if Tox is enough, or if we need some separate tool to do acceptance tests and run in bash some actual rdiff-backup jobs/cycles. I would be interested in having some tests that generate a backup archive with version 1.2.8 and then runs the latest git development version to further process that archive and make new increments etc. This would show us if the code remains backwards compatible or not.

We could also run some static code analysis. Since this is a Python project, running flake8 on all Python files would seem natural. Requiring everybody to follow PEP-8 in their Python code is probably OK.

## What testing system to use?

Github does not have any built in testing system (unlike Gitlab which has Gitlab CI). Personally I have lot's of experience with Travis-CI and it is free for open source projects, so we could adopt it.

**Comment by ericzolf** [comment]
Few comments from me:

- yes we need CI/CD!
- Flake8/PEP8 - yes, please! (the current tabs are ugly and killing my editor) - my next task after Python3 is merged would be to fix all files in this regard.
- regarding the current tox setup - my impression is that many things are tested multiple times which cost time, we might want to clean this to optimize waiting time at merge time but can be a 2nd step
- it would be nice to have a test coverage measurement tool (I think it's not too bad, but actually no clue)

**Comment by ottok** [comment]
Yes, code coverage is a good idea and it should be possible to have with Tox (see e.g. https://www.rfk.id.au/blog/entry/testing-better-coverage-tox/).

I have now activated https://travis-ci.org/rdiff-backup/rdiff-backup but there is no real .travis.yml file done yet.

**Comment by ottok** [comment]
First PR filed as #96

**Comment by ottok** [comment]
Second step will be running full Tox suite. WIP at https://github.com/rdiff-backup/rdiff-backup/tree/feature/travis-ci-tox

**Comment by ottok** [comment]
I have been playing around with different approaches to Travis-CI at https://travis-ci.org/rdiff-backup/rdiff-backup/builds using just one big job, or a matrix, or stages. I am not sure what route to take here. Does anybody have comments? @ikus060 maybe?

**Comment by ikus060** [comment]
@otto I'm on mobile, a bit harder to point you to the right direction. For
rdiffbackup will need to compile with manylinux.
https://github.com/pypa/manylinux

Take a look a their example projet.

We need to compile with manylinux since we have extension in c.

**Comment by ottok** [comment]
I think I will settle with this "user experience":

![image](https://user-images.githubusercontent.com/668724/64079728-9c206a00-ccf3-11e9-91dc-4cbc9f2afc1d.png)

![image](https://user-images.githubusercontent.com/668724/64080037-f1f71100-ccf7-11e9-9e57-906882232f16.png)

**Comment by ericzolf** [comment]
The steps look good to me, without exactly knowing what is behind each of them. Are you able to test each Python version from 3.5 till 3.8?

**Comment by ottok** [comment]
You can see it at https://travis-ci.org/rdiff-backup/rdiff-backup/builds and followg the links to the commits or view the whole WIP branch at https://github.com/rdiff-backup/rdiff-backup/tree/feature/travis-ci-tox

ATM the goal is just to get the tests pass so we can prevent new regressions from sneaking in, and then we can start to expand the tests, the Python versions and the platforms later on.

**Comment by ikus060** [comment]
Could we close this ticket ? Looking at the current Travis pipeline everything is good to me. If anything is missing we should probably create a separate tickets that are more specific.

**Comment by ericzolf** [comment]
I think we should first add at least all relevant versions of Python (3.5 to 3.8) before we do this. It's a small thing, adding other platforms and the automated generation of binaries would need to go into another issue. What do you think?

**Comment by ikus060** [comment]
ok, I will start working on travis build to add other version. But seriously, if it's not working for 3.5 or 3.6, I'm fine to only support py3.7.
1. adding other platforms see #105 should cover Windows
2. automated generation of binaries, just created #188
