### ISSUE TITLE
[ENH] Explicitly mention that binary diffs work and roughly how (in the README)

### ISSUE THREAD

**Issue by bernd-wechner** [rdiff-backup/rdiff-backup#482]
## The problem

I just read the README and I like. But reading it raises one curious question to nay half way experienced reader that I can't find answer anywhere easily. It relates to this:

"rdiff-backup only stores the differences from the previous backup to the next one"

which is great but begs the question how and in what format? Reason being is that we're all familiar I'm sure with many efficient diff formats for text files how to use them, merge them, patch with them and more. But the realm of binary diffs, formats, and ways to apply them, is a little less well know, more to the point I'm curious how it works. And so I'd love to see a few words, not much, just a little, in the README brooching this topic and maybe pointing to more reading. What does a diff between two binary files look like and how is it used. 

## Describe the solution you'd like

Just some extra words in the README for curious arrival.

**Comment by ericzolf** [comment]
The technical background is all given by librsync e.g. https://github.com/librsync/librsync/blob/master/doc/format.md - hope this gives you what you look for.
