### ISSUE TITLE
[ENH] 

### ISSUE THREAD

**Issue by Laanan** [rdiff-backup/rdiff-backup#485]
Answered my own question, sorry

**Comment by ikus060** [comment]
> Hi, is it possible to see the progress of a backup? I started a backup about an hour ago and still just have a blinking cursor on bash. Not sure if the backup is still running or...?

Rdiff-backup doesn't provide a progress bar, but you may get more verbose logs by passing `-v 5`. Level 5 seams to most useful log to get progress of backup
