### ISSUE TITLE
Rebuild of rdiff-backup with Python 3.10.0a2

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#489]
@ericzolf you may want to read RedHat Bugzilla 1898980 (https://bugzilla.redhat.com/show_bug.cgi?id=1898980).  While the proposed change has been rolled back from Python 3.10, other possible updates will probably be tested in the future.

**Comment by ericzolf** [comment]
From the comment, I'm unsure if I should introduce the approach suggested or if it's a bad idea. I think, I'll wait until a beta version of Python 3.10 is released before I really care.

**Comment by frankcrawford** [comment]
@ericzolf  Yes, I'd agree with not doing anything at present, but it does look like they are going to use Fedora to test a number of proposals.  I'll attempt to keep you up to date with them.

**Comment by ericzolf** [comment]
I close this version as the issue doesn't seem to want to come back. Re-open if you want to prove me wrong :wink:
