### ISSUE TITLE
Split gh-pages branch to separate repository

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#49]
Currently our webpage is built from the gh-pages branch of this same repository. I don't think that makes sense in the long run. We should consider splitting that out into a separate repository at github.com/rdiff-backup/website or something along those lines.

**Comment by ottok** [comment]
Comments anybody?

**Comment by afoster** [comment]
As long as we plan to use https://pages.github.com, the current recommended practise is to create a repo called `rdiff-backup.github.io`. Custom domains can then be attached to that.

**Comment by ottok** [comment]
Using `rdiff-backup.github.io` as repo name is not necessary. The current repo and gh-pages branch already work as is, but indeed I think it would be cleaner if the website was in a separate repo.

Any comments from @ericzolf ?

**Comment by ericzolf** [comment]
Using branches for content unrelated to master is rather sick, so I'm all for a separate repo. If the repo name is recommended practice, I'm fine with it.

**Comment by ottok** [comment]
gh-pages branch now moved to https://github.com/rdiff-backup/rdiff-backup.net
