### ISSUE TITLE
[BUG] unable to include all hidden files  in source dir, while excluding everything else not specified 

### ISSUE THREAD

**Issue by zany130** [rdiff-backup/rdiff-backup#492]
## Bug summary

unable to include all hidden files in source dir, while excluding everything else not specified. Ignores the ```+ /home/zany130/*. ``` line in the provided include list
[include-list.txt](https://github.com/rdiff-backup/rdiff-backup/files/5581350/include-list.txt)

## Version, Python, Operating System
Arch Linux
Call `rdiff-backup --version --api-version 201` or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```
rdiff-backup -v9
2020-11-23 01:24:31.864876 -0500  <CLIENT-1257200>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
2020-11-23 01:24:31.862868 -0500  <CLIENT-1257200>  Using rdiff-backup version 2.0.5
2020-11-23 01:24:31.862917 -0500  <CLIENT-1257200>      with cpython /usr/bin/python version 3.8.6
2020-11-23 01:24:31.864833 -0500  <CLIENT-1257200>      on Linux-5.9.8-95-tkg-pds-x86_64-with-glibc2.2.5, fs encoding utf-8
```
## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
sudo rdiff-backup --verbosity 5 --print-statistics --include-special-files --include-globbing-filelist include-list.txt /home/zany130/ /mnt/BACKUPS/rdiff/
```

## What happened and what did you expect?

ignored line 2 of include file and didn't back up hidden files

expected hidden files to be backup such as .bashrc while excluding any folder or file not specified (ex: non-hidden files and .cache and some other folders not specified)

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

**Comment by ericzolf** [comment]
The 2nd line `<somedir>/*.` matches on files which _end_ with a dot, not on files which _start_ with a dot as would `<somedir>/.*`.

Please close the issue if that was your problem.

**Comment by zany130** [comment]
oops yeah fixed it but still have the same issue of not being able to backup only hidden files it just does everything. or it gives an error about what I am trying to do is redundant

**Comment by ericzolf** [comment]
What about something like the following as include file:

```
+ /home/zany130/.*
- /home/zany130/*
```

**Comment by zany130** [comment]
it gives this if i add that and remove all the other wild card declarations 

Fatal Error: Last selection expression:
    Command-line include glob: b'/home/zany130/.wine/'
only specifies that files be included.  Because the default is to
include all files, the expression is redundant.  Exiting because this
probably isn't what you meant.
Backup: escape_dos_devices = 0
Backup: escape_trailing_spaces = 0
Reading globbing filelist include-list.txt

**Comment by zany130** [comment]
ok so if include looks like this for example
```
+ /home/zany130/.*
+ /home/zany130/.config/
+ /home/zany130/.wine/
- /home/zany130/.wine/dosdevices/
- /home/zany130/*
```
it will just backup all hidden folders including for example ```.cache``` which I don't want 

if i do this 
```
- /home/zany130/.wine/dosdevices/
- /home/zany130/*
+ /home/zany130/.*
+ /home/zany130/.config/
+ /home/zany130/.wine/
``` 
then it gives this error 
```
Fatal Error: Last selection expression:
    Command-line include glob: b'/home/zany130/.wine/'
only specifies that files be included.  Because the default is to
include all files, the expression is redundant.  Exiting because this
probably isn't what you meant.
Backup: escape_dos_devices = 0
Backup: escape_trailing_spaces = 0
Reading globbing filelist include-list.txt
```

**Comment by ericzolf** [comment]
Yeah, if you don't want to backup `.cache`, then exclude it, why do you try to solve this issue by including files you've already included with `xxx/.*`? And if you only want to include specific dotted files, then only list those:

```
- /home/zany130/.wine/dosdevices
+ /home/zany130/.config
+ /home/zany130/.wine
- /home/zany130/*
```

else the following also works:

```
- /var/tmp/from/.wine/dosdevices/
- /var/tmp/from/.cache/
+ /var/tmp/from/.*
- /var/tmp/from/*
```

The order is important as the first match on a path will "win".

**Comment by zany130** [comment]
I think the problem is that folders are treated the same as files so I can't tell it ignores all .folders and do include . files without doing some tricky with the find command or something. thanks though
