### ISSUE TITLE
[ENH] Offline rdiff-backup installation

### ISSUE THREAD

**Issue by ShawnTheCoder** [rdiff-backup/rdiff-backup#493]
Hi team,

Is there a way to install the package without connection to Internet.
I tried to use "python setup.py install" but got the following error.

> Download error on https://pypi.org/simple/setuptools-scm/: [Errno 101] Network is unreachable -- Some packages may not be found!
> Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
> Download error on https://pypi.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
> No local packages or working download links found for setuptools_scm
> Traceback (most recent call last):
>   File "setup.py", line 226, in <module>
>     setup_requires=['setuptools_scm'],
>   File "/share/home/jyang/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 142, in setup
>     _install_setup_requires(attrs)
>   File "/share/home/jyang/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
>     dist.fetch_build_eggs(dist.setup_requires)
>   File "/share/home/jyang/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
>     replace_conflicting=True,
>   File "/share/home/jyang/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 780, in resolve
>     replace_conflicting=replace_conflicting
>   File "/share/home/jyang/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in best_match
>     return self.obtain(req, installer)
>   File "/share/home/jyang/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1075, in obtain
>     return installer(requirement)
>   File "/share/home/jyang/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
>     return cmd.easy_install(req)
>   File "/share/home/jyang/anaconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
>     raise DistutilsError(msg)
> distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')

Thanks!

**Comment by ericzolf** [comment]
It depends what you're calling "offline" and what you're exactly trying to do, but if you install all the dependencies before you call the command, the setup should run offline. Dependencies are documented in the [developer's documentation](../blob/master/docs/DEVELOP.md) but you can also use the [requirements.txt](../blob/master/requirements.txt).

**Comment by ericzolf** [comment]
No answer, I close the issue, feel free to re-open if you need more help.
