### ISSUE TITLE
Create .github/FUNDING.yml file for this repo?

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#50]
Github supports a built-in "help fund this open source project" button that can be activated via .github/FUNDING.yml. This is not a high priority, but some time later we might want to consider if we want this and also if we organize this project under the umbrella of some existing open source organisation, like SPI or Samba (Samba hosts rsync).

I will write more on this topic later, now I just opened this as a reminder to think about this later.

**Comment by ericzolf** [comment]
I'm doing this in my free time, just so that I don't lose my favourite backup tool at time of Python2 deprecation, so I don't really care

**Comment by ericzolf** [comment]
No progress, let me close it.

**Comment by ottok** [comment]
Does this mean you would not benefit from funding?

**Comment by ericzolf** [comment]
It wouldn't give me more free time, would it? Probably rather more obligations to deliver (and more stress).
