### ISSUE TITLE
[BUG] document minimal Ubuntu version for backport

### ISSUE THREAD

**Issue by mvoorhis** [rdiff-backup/rdiff-backup#500]
## Bug summary

Documentation in README.md fails to mention that rdiff-backup repo does not (and will not) support Ubuntu-16.04

## Version, Python, Operating System

rdiff-backup version and python versions don't matter.  OS Version is Ubuntu-16.04.X LTS.

Please place text into the README.md file, in the location containing instructions for using the repo for "old ubuntu versions", telling the poor users not to follow the instructions if they have Ubuntu-16.04 since the repo does not contain software for 16.04 (despite there being a directory for it in the repo).  Following the instructions from Ubuntu-16.04 produces no errors but silently fails to install rdiff-backup as the instructions imply should happen.

**Comment by ericzolf** [comment]
Sounds reasonable. Would you mind documenting it yourself and offering a PR from your fork?

**Comment by mvoorhis** [comment]
(I typed a bunch of stuff and then killed my browser-tab.  Sigh.. start over!)

Yes, I'd be willing to do the documentation but I'm not experienced doing PRs.  Since I started this with all my complaining, I should probably learn!

The newest version of Ubuntu, 20.04LTS, offers rdiff-backup v2 officially.  Is it is safe to say that availability of precompiled packages will be confined to 18.04LTS and 19.10? Ubuntu-19.10 is already EOL so I wasn't sure if that stuff would also disappear.  If only 18.04LTS binaries will exist, changing the the README doc will be easy, because the repo would only contain rdiff-backup v2 for Ubuntu-18.04LTS.

**Comment by ericzolf** [comment]
Not experienced doing PR: ask questions and they shall be answered, no issue :-)
https://reflectoring.io/github-fork-and-pull/ sounds like a good start. I would nevertheless recommend to always do with a feature branch (unless you only plan to do one PR and re-create the fork each time), means keeping master in sync with "upstream" and only doing your changes in your own branch.

Regarding the details of what is and will get supported on Ubuntu, I would refer you to @ottok

**Comment by ericzolf** [comment]
This issue is outdated, closing. Feel free to re-open if you think otherwise.
