### ISSUE TITLE
What to do about bugs filed at Savannah?

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#51]
There are a lot of open bugs at http://savannah.nongnu.org/bugs/?group=rdiff-backup

We should think about what to do with them. This is not a priority (after all they have been sitting there for years) but we should at some point deal with them. Maybe ask reporters to re-test with latest rdiff-backup 2.0 and re-report on Github if the issue still persists and they want it fixed.

**Comment by ericzolf** [comment]
I've closed all tasks and support tickets, and disabled the boards, took even the chance to re-direct a few links (Git and Homepage) at Savannah. The only tickets remaining are the [bugs](https://savannah.nongnu.org/bugs/?group=rdiff-backup) but there are 54 of them, so quite some tedious work to do...

**Comment by ericzolf** [comment]
You might have gotten the notifications, I've closed half of the bugs so that there are 27 ones left. They are either legit and/or would require relatively extensive tests to validate if they're legit.

I hesitate and I lack the time to create 27 new issues without filtering and quality check. My suggestion would be to ask the community for help. What do you think?

**Comment by ottok** [comment]
Yes, once 2.0 is released, ask them to install it and re-file the issue on Github if it still exists.

**Comment by ericzolf** [comment]
OK, I added the "beginner" label, as this is someone with little knowledge about the code can do:

- take ownership of one bug at https://savannah.nongnu.org/bugs/?group=rdiff-backup by adding a comment to the original bug and/or to this issue
- reproduce the issue with rdiff-backup v2.0.0
- create a [GitHub issue](https://github.com/rdiff-backup/rdiff-backup/issues/new) referring to the initial Savannah bug and to this issue #51, describing in the most succinct possible way how to reproduce the bug (something which could be used as test case)
- it's of course also fine to propose a PR to resolve the issue :-)

We'll close the original bug as duplicate once an issue has been created in GitHub or someone reports that the issue can't be reproduced.

**Comment by ericzolf** [comment]
Nobody volunteered and the bugs were anyway sh*t old, so I just closed them old, asking to re-open in GitHub if they're still of interest.
