### ISSUE TITLE
[ENH] install rdiff-backup v 1.3.3 on ubuntu 14.04

### ISSUE THREAD

**Issue by GusevVictor** [rdiff-backup/rdiff-backup#515]
## Is your feature request related to a problem? Please describe.

I have ubuntu 14.04 as client OS and I have install rdiff-backup-1 on my server OS (ubuntu 20.04).

After that I have WARNING about my client has rdiff-backup v 1.2.8 and server has rdiff-backup v 1.3.3

## Describe the solution you'd like

Please tell me about how to upgrade rdiff-backup up to  v 1.3.3 on ubuntu 14.04

**Comment by ikus060** [comment]
Take note, rdiff-backup v1.3.3 was never released as a production ready version. You should stick either with 1.2.8 or upgrade to v2.x.x. I'm not sure where is `rdiff-backup-1` coming from. Have you added a PPA ?

> After that I have WARNING about my client has rdiff-backup v1.2.8 and server has rdiff-backup v 1.3.3

Indeed, rdiff-backup requires you to have a similar or identical version running on both sides. (server and client).

I would recommend you to install v2.x. Read instruction here: https://github.com/rdiff-backup/rdiff-backup/blob/v2.0.5/README.md#installation

**Comment by GusevVictor** [comment]
Dear @ikus060 , is it possible to install v2.x on Ubuntu 14.04? I don't see a way for it. Because of this I use rdiff-backup-1 as a workarround. Yes, it comes from PPA of rdiff-backup developers

**Comment by ikus060** [comment]
It should be possible for you to install rdiff-backup v2.x by following instruction "Debian and derivatives, Raspbian, etc. (from PyPi)"

**Comment by GusevVictor** [comment]
Yes, but I'm looking for "librsync 1.0.0" for ubuntu 14. Did you see that?

**Comment by ikus060** [comment]
Tested in docker container.
The main issue is python 3.4. You need to install python >= 3.5

Here the steps:

rdiff-backup v2.x on ubuntu 14.04

# Install python 3.5
apt install software-properties-common
add-apt-repository ppa:fkrull/deadsnakes
apt update
apt install python3.5 python3.5-dev

# Install pip with python 3.5
apt install curl
curl https://bootstrap.pypa.io/get-pip.py | python3.5

# Install rdiff-backup dependencies
pip install pylibacl pyxattr

# Install rdiff-backup
pip install rdiff-backup

**Comment by GusevVictor** [comment]
Dear @ikus060 you look like a brilliant! I will test in with real backup script and post the final result! It looks like OK in the first touch!

**Comment by ericzolf** [comment]
No reaction since a long time, closing. Just re-open if you need more help on the same topic.
