### ISSUE TITLE
[ENH] Delete intermediate backups

### ISSUE THREAD

**Issue by Nick222** [rdiff-backup/rdiff-backup#527]
Can a user delete intermediate backups?

For example, backups were made daily from January 20 to 25.
Can a user delete only backups on January 21, 22, 23, 24, leaving only backups for January 20 and 25?

**Comment by ikus060** [comment]
To my knowledge, rdiff-backup doesn't have this feature. 

But you could delete the full history of a folder or a file!
Search for rdiff-backup-delete
This feature was sponsored by Brandorr Group

Feel free to reopen this ticket if you have more question on this topic.

**Comment by ericzolf** [comment]
This is also a duplicate of https://github.com/rdiff-backup/rdiff-backup/issues/257.
