### ISSUE TITLE
[SUPPORT] How to include hidden files

### ISSUE THREAD

**Issue by 3Domse3** [rdiff-backup/rdiff-backup#552]
I try to backup all files in all directories except those I excluded, but I don't understand how to include all hidden files (e.g. ".FILENAME").

Using

`sudo rdiff-backup -v5 --print-statistics --exclude /tmp --exclude /proc --exclude /mnt --exclude /media --exclude /sys / /media/pi/USB/rdiff_RaspberryPi4B/`

ignores hidden files,

`sudo rdiff-backup -v5 --print-statistics --exclude /tmp --exclude /proc --exclude /mnt --exclude /media --exclude /sys /.* /media/pi/USB/rdiff_RaspberryPi4B/`

outputs an error:

`Using rdiff-backup version 1.2.8`
`Fatal Error: Switches missing or wrong number of arguments`
`See the rdiff-backup manual page for more information.`

## Version, Python, Operating System

Using rdiff-backup version 1.2.8 (newest I can get with apt upgrade)
Python 3.7.3
Raspberry Pi OS 32bit with all updates installed

**Comment by ericzolf** [comment]
It is normal that the 2nd command fails because the `/.*` is probably expanded _by the shell_ to multiple files, which are seen by rdiff-backup as multiple source paths, which is wrong syntax.

Version 1.2.8 is out of support, and I can't test your use case, but I can't remember having changed anything to this behavior and rdiff-backup definitely doesn't ignore hidden files. What makes you think that it is the case? IMHO the first call should work as you expect it.

Could you please call `rdiff-backup --list-at-time now /media/pi/USB/rdiff_RaspberryPi4B/` and tell if the .DOT files really aren't listed?

**Comment by 3Domse3** [comment]
> Version 1.2.8 is out of support, and I can't test your use case, but I can't remember having changed anything to this behavior and rdiff-backup v2 definitely doesn't ignore hidden files. What makes you think that it is the case? IMHO the first call should work as you expect it.

Do you know whether it is possible to upgrade to version 2 manually on a Pi? I don't know why it doesn't get added officially :/

> Could you please call `rdiff-backup --list-at-time now /media/pi/USB/rdiff_RaspberryPi4B/` and tell if the .DOT files really aren't listed?
The disk I made the backups to had an error and i had to format it so I currently don't have any backups. But I know for sure because after my last reinstall, I wanted to restore my ".bash_aliases" file and together with als other ".XXX" files, it was missing.

**Comment by ericzolf** [comment]
> Do you know whether it is possible to upgrade to version 2 manually on a Pi? I don't know why it doesn't get added officially :/
rdiff-backup is in raspbian/testing according to https://repology.org/project/rdiff-backup/versions, so perhaps you could grab the package from there, else try https://github.com/rdiff-backup/rdiff-backup#other-linux-and-unx-oid-systems-eg-bsd-from-pypi (after having removed rdiff-backup using apt).
> 
> > Could you please call `rdiff-backup --list-at-time now /media/pi/USB/rdiff_RaspberryPi4B/` and tell if the .DOT files really aren't listed?
> 
> The disk I made the backups to had an error and I had to format it so I currently don't have any backups. But I know for sure because after my last reinstall, I wanted to restore my ".bash_aliases" file and together with als other ".XXX" files, it was missing.

Do a small test and let me know the result, but I can't tell you more for now than what I already wrote...

**Comment by 3Domse3** [comment]
I ran the command and the output says it did backup my .XXX files. I also checked the drive and they are there.
Don't know what caused the problem in earlier backups but the problem is solved :)

Does this mean that rdiff automatically saves ALL files and subfolder in a directory if not told to do something else?

**Comment by ericzolf** [comment]
> Does this mean that rdiff automatically saves ALL files and subfolder in a directory if not told to do something else?

Correct, unless it can't read them (e.g. SELinux stands in the way or backup user isn't root), but  then it should spit a warning. Shouldn't it be the case, it would be an issue you are welcome to report.

In the mean time, let me close this issue.
