### ISSUE TITLE
[BUG] Windows 64 bits version of rdiff-backup v2.1.0a0 can't find module named rdiff_backup

### ISSUE THREAD

**Issue by dtxl** [rdiff-backup/rdiff-backup#555]
## Bug summary

In command line calling rdiff-backup.exe, e.g. rdiff-backup.exe --version (or rdiff-backup -v9 or rdiff-backup info etc.) gives 

Traceback (most recent call last):
  File "rdiff-backup", line 19, in <module>
ModuleNotFoundError: No module named 'rdiff_backup'
[20568] Failed to execute script rdiff-backup

## Version, Python, Operating System
rdiff-backup Alpha Release v2.1.0a0, W10 LTSC 1809, Microsoft Visual C++ Redistributable - x64 9.0.3

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
cf. above
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
any parameter
```

**Comment by ericzolf** [comment]
Sorry, building it worked in my VM, but failed in the pipeline. I need to check the details. Thanks for reporting! You can try the 32 bits version in the meantime.

**Comment by dtxl** [comment]
Thanks. I try now the 32bit version and it's running now.
After starting it the message "WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'." was shown.
For testing I use
C:\rdiff-backup32\rdiff-backup.exe -v0 --force --exclude C:/Users/_user_/AppData --exclude C:/Users/_user_/Downloads C:/Users/_user_ B:/rdiff

**Comment by ericzolf** [comment]
The 64 bits build shows at [line 289](https://github.com/rdiff-backup/rdiff-backup/runs/2295641802?check_suite_focus=true#step:6:289) that PyInstaller grabs the 32 bits version of the libraries: `D:\\a\\rdiff-backup\\rdiff-backup\\build\\lib.win32-3.9`, and I see now that there is a stray `win32` in `tools/win_build_rdiffbackup.sh`, it simply needs to be replaced with `${py_win_bits}`. I'll fix this in the course of the day and push a new alpha version. Gaaah.

**Comment by ericzolf** [comment]
The warning is as expected, the new command would be `C:\rdiff-backup32\rdiff-backup.exe -v0 --force backup --exclude C:/Users/user/AppData --exclude C:/Users/user/Downloads C:/Users/user B:/rdiff` (notice the `backup` action after `--force`).

If you could try the 64 bits executable attached to the PR #556, I'd appreciate very much.

**Comment by dtxl** [comment]
The v2.1.0a1 doesn't show this bug any more.
