### ISSUE TITLE
Create a CONTRIBUTE.md and development policy

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#57]
We should adopt a development policy and rules, for example that nobody pushes to master and all changes go in via pull requests. This is common for open source projects. I will draft one as a starting point with the usual recommendations and policies.

What goes to coding style, we should probably enforce PEP-8 as is or with minor changes (e.g. longer line length).

As a first step, I protected the master branch in Github settings:
![image](https://user-images.githubusercontent.com/668724/62919400-34899580-bdab-11e9-808c-ed383bb5dec6.png)

**Comment by ottok** [comment]
Draft document visible in https://github.com/rdiff-backup/rdiff-backup/pull/100
Comments @ericzolf ?

**Comment by ottok** [comment]
Also, since we have now #95 merged, do you want to fix up the style @ericzolf or do you want me to do it?

**Comment by ottok** [comment]
Related to this, it would be nice to have a policy on what the versioning scheme is. Eventually we will make `git tag v2.0.0` and that is pretty clear, but regarding development releases things might need to be clarified. While developing 2.0.0, is the version 2.0.0~alpha1 or 1.9.9 or 1.4.0.beta or 1.4.0b0.

Currently in https://github.com/rdiff-backup/rdiff-backup/releases/tag/v1.4.0.beta there is the tag 1.4.0.beta but the filename is not rdiff-backup-1.4.0.beta.tar.gz but suffixed with 1.4.0b0.

Related:
- https://github.com/rdiff-backup/rdiff-backup/issues/66
- https://github.com/rdiff-backup/rdiff-backup/pull/152

**Comment by ericzolf** [comment]
The discrepancy is clearly due to my ignorance and future beta tags will be of the form x.y.zb0 so as to match the released files version. For example, next tag will probably be 1.4.1b0 or 1.5.0b0 (doesn't really matter, only increase matters).

**Comment by ottok** [comment]
Just built from latest master, ended up with an egg with this version: `rdiff_backup-1.4.0b1.dev29+gb1e044d.egg-info` because of https://github.com/pypa/setuptools_scm/#default-versioning-scheme

**Comment by ericzolf** [comment]
Correct. You need to check out a tag to get a "nice" version. What is your actual issue? And you shouldn't build eggs, deprecated, but wheels...

**Comment by ottok** [comment]
Somehow I would prefer, that is the plan is to release 2.0.0, the work done leading up to it would be done using version "2.0.0 alpha N" or "1.9.0" or something like that. The version "1.4.0" base does not seem intuitive or what other projects usually do in situations like these.

**Comment by ikus060** [comment]
Kinda agree with @ottok 
The right version number of our next release 2.0.0 should be 2.0.0 alpha 1, then 2.0.0 beta 1, etc. That is more simple for everyone and make it clear for users that our next release is 2.0.0. and not 1.4.0.

**Comment by ottok** [comment]
Judging from [the milestones](https://github.com/rdiff-backup/rdiff-backup/milestones?direction=asc&sort=title&state=open) you plan to have all dev versions use odd numbers, so after the 2.0.0 you will immediately tag 2.1.0?

**Comment by ottok** [comment]
Will the tar.gz releases always include a PKG-INFO file with line `Version:` from where the Debian builds can pick up the version string? At what stage of the build is this file generated, could I perhaps use it in the deb builds at the project itself?

Currently my plan to do dynamic versioning is via afcc8bd58f33aea74173328b182d1f35b8c0127b or something similar. I am still a bit skeptic on how well this tag based version control will work, but I expect you to prove my doubts wrong.. Personally I've always worked with projects that have the version string expressed somewhere in the source itself.

**Comment by ericzolf** [comment]
`./setup.py sdist` makes the magic, and `./setup.py --version` gives you the current version. We still need to add the sdist target to the deployment, but I was waiting for the current PRs to stabilize.

Regarding the milestones, it is not a set plan, it's just an idea, but I don't like choosing versions, so it makes my life easier.

**Comment by ottok** [comment]
For the record, in my tests `setup.py --version` emits version strings like `1.4.0b1.dev38+g02cbc7a`.

**Comment by ottok** [comment]
I've done my best to capture what we are now doing and finalized it in writing in https://github.com/rdiff-backup/rdiff-backup/pull/100

Is it OK?
