### ISSUE TITLE
[ENH] Avoid librsync delta calculation when only acl, perm or xattr changed

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#574]
## Is your feature request related to a problem? Please describe.

When updating the ACL, perm or xattr on a large number of directories, rdiff-backup is taking forever to run the following backup because the changes trigger recomputation of the delta. 

## Describe the solution you'd like

When the change the limited to acl, perm or xattr, it should not trigger creation of a diff. Or at least it should fast forward the creation of the detla file.

## Describe alternatives you've considered

Workaround is to disable ACL put it's not optional when you want to keep them.

## Additional context

What I found out so far.
1. The comparison happen here: https://github.com/rdiff-backup/rdiff-backup/blob/7bc406dc7fb21b776a6f58d5f2cc74cecd98b7c4/src/rdiff_backup/rpath.py#L135
2. But if any changes are detected, it always trigger the same behaviour later on
3. Maybe we could skip the creation of the patch here: https://github.com/rdiff-backup/rdiff-backup/blob/7bc406dc7fb21b776a6f58d5f2cc74cecd98b7c4/src/rdiff_backup/backup.py#L593

**Comment by ikus060** [comment]
@ericzolf After testing with master branch, this problem seams to be fixed. At least, the "patch" doesn't get generated whenever only the ACL changed. After further testing this also seams to be fixed with v2.2 with  `--api-version 201`.

So all in all, I think we could close this issue and mark it as fixed.

**Comment by ericzolf** [comment]
Closing, sorry I had overseen your message!
