### ISSUE TITLE
[ENH] metadata for lost information across file systems

### ISSUE THREAD

**Issue by brainchild0** [rdiff-backup/rdiff-backup#577]
Currently, the net effect of a backup-and-restore sequence is limited to the lowest set of common capabilities of the file systems of the original and backup media. Thus, a tree in a POSIX system will not in general be restored correctly, when backup up to a FAT32, exFAT, or NTFS target, due limitations of file names and varied support for hard and symbolic links in these systems.

Proposed is a feature that persists the  missing data, including translated file names, in a backup-level metadata store, which can be read during restore to recreate the exact original tree irrespective of limitations of the file systems.

Otherwise, a restored tree would have highly-unpredictable differences from the original, making the application an unsuitable choice for many scenarios.

**Comment by ikus060** [comment]
@brainchild0 Have you validate this ?

rdiff-backup is storing metadata of each file. That include file permissions, ACL, symbolik link, hard link, etc.

The only requirement is having the appropriate python libraries installed along rdiff-backup.
pyacl and pyxattr for linux.

**Comment by ericzolf** [comment]
Yes. Feel free to suggest a better wording in a pull request.

**Comment by brainchild0** [comment]
Sure I will think about it. 

To be clear on the capabilities, does the application only handle the target file system correctly in  cases of being invoked directly on a target of that system, or is moving a previously-generated backup target to a new type of file system also supported?

**Comment by ikus060** [comment]
You should be able to copy to another file system without problem. But be
aware of NTFS using special characters : and \

To rephrase, their is done limitation to copy from Linux to Windows.

**Comment by brainchild0** [comment]
I would imagine there could be problems with a basic copy utility dropping metadata  and links,. and changing names, without such changes reflected in the saved application data.

I just tried a FAT32 target and saw a warning about hard links. I am not sure of the actual significance of this warning with respect to this discussion or  the backup I was making. (I had originally attempted to a exFAT target, but support appears to be unavailable.)

**Comment by ericzolf** [comment]
Without the exact warning, difficult to tell. Regarding exfat, we don't exactly do not support it, but certain actions take too much time, so it's refused because the test fails.

**Comment by ericzolf** [comment]
Ah, and personally, I wouldn't move a backup repo from one file system to the next, the chance that something goes wrong is rather high. In other words, we don't test it, we don't support it.

**Comment by brainchild0** [comment]
> Ah, and personally, I wouldn't move a backup repo from one file system to the next, the chance that something goes wrong is rather high. In other words, we don't test it, we don't support it.

I understand. Migrating across file system could be supported in principle as an application feature, through an alternative invocation mode compared to backup or restore. Such a feature may have other uses.

More concretely, I wonder about an invocation option that causes the backup to take a form of a most basic shared feature set of file systems, providing safety for simple copies across media. As moving and replicating data across media is now pervasive, on removable media, NAS devices, cloud storage, and so on,  a way to ensure integrity of the data seems extremely valuable.

**Comment by ericzolf** [comment]
rdiff-backup is a backup tool, not a copy tool. For this there is e.g. rsync which does the job much faster. From the [man page](https://www.man7.org/linux/man-pages/man1/rsync.1.html):

> Note that rsync always verifies that each transferred file  was correctly reconstructed on the receiving side by
> checking a whole-file checksum that is generated as the file is transferred

Don't take it bad but we have so many things to do that we can't have issues opened for things we might never address.

**Comment by brainchild0** [comment]
I think you misunderstand. If I have a backup, I don't want it tied to some specific media. I may want to archive it, on another disk, or network storage.

**Comment by ericzolf** [comment]
I understand but still no. There are so many combinations, it's impossible to test realistically so we won't even try. If you want to do this, do it on the same file system family (between POSIX file systems, it should be fine, e.g. ext4 and xfs) and test it yourself.

**Comment by ikus060** [comment]
I confirm, it's possible to copy the backup between media. As mention by
Eric, copying between know POSIX file system should not cause any trouble.

I've copy between ext4, btrfs, ZFS, xfs without any issues. But copying
from POSIX to non-POSIX, like fat32 or NTFS is impossible to support.

So you have to choose from the start the type of storage. I would recommend
going with POSIX file system to save you trouble.

**Comment by brainchild0** [comment]
> But copying from POSIX to non-POSIX, like fat32 or NTFS is impossible to support.

Why?

**Comment by ikus060** [comment]
Mostly because posix is not compatible with NTFS. As an example, NTFS does
not support column (:) in path name, but POSIX does. So if you have file
name containing column (:) copying won't work.

It's not a limitation of rdiff-backup, more a limitation of inter
compatibility between file system.

**Comment by brainchild0** [comment]
> As an example, NTFS does not support column (:) in path name, but POSIX does.

Right, but how does noting this constraint support your  earlier generalization?

File `x:y` is allowed in POSIX but not Windows, whereas `x_y`  is allowed in both. Therefore, changing a name from the former to the  latter would support the ability of the file to be migrated safely between file systems of the two kinds.
