### ISSUE TITLE
[NOT a BUG] too many lstat() syscalls, therefore too many IOPS

### ISSUE THREAD

**Issue by b10s** [rdiff-backup/rdiff-backup#578]
Hello,

It is not a bug. Just want to know what might be wrong with my current setup. Maybe I do misuse the rdiff-backup.

Since recent, during backing up I can see spike in IOPS up to 500 which exhaust all my limit on VM. Therefore backup process takes very long. I've straced a bit and what I can see is there are many `lstat()` syscalls:

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 42.71    0.040247           9      4608      1420 lstat
 35.41    0.033370          12      2860           getdents
  9.41    0.008865           6      1431           open
  4.63    0.004363           3      1430           close
  4.03    0.003797           3      1431           fstat
  3.75    0.003536           2      1417           getuid
  0.04    0.000039          39         1           unlink
  0.01    0.000013           1         9           read
------ ----------- ----------- --------- --------- ----------------
100.00    0.094230                 13187      1420 total
```

What it does is trying to check existence of some file/dir:
```
10:13:16 lstat("/some/path/rdiff-backup-data/increments/foo/bar", 0x7ffd832fa810) = -1 ENOENT (No such file or directory) <0.000020>
```

After backup is done, there is still no such file.

Seems the part in path - `/rdiff-backup-data/increments/` - is some "config" for rdiff-backup and probably it tryies to find something but can't?

Can someone give some clues what can I check to make rdiff-backup happy?

**Comment by ericzolf** [comment]
Closing and continuing the discussion on the mailing list. Please avoid cross-posting in the future. You've not been ignored, we just have limited time.
