### ISSUE TITLE
Set up rdiff-backup on PyPi

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#58]
The package rdiff-backup is listed at https://pypi.org/project/rdiff-backup/ but no versions after 0.1.1 have been released and the author anyway is unknown. We should try to get access to this package on PyPi and integrate it to be automatically published from tags released on Github.

**Comment by ottok** [comment]
Current PyPi maintainer @AvdN responded to me by e-mail and assured this will be fixed once the new people doing the Python 3 rewrite have established themselves and #52 has been fixed.

**Comment by AvdN** [comment]
I have added Otto as maintainer on PyPI based on the data that at least one of the members on savannah.nongnu.org (Andrew Foster) has been involved in the mailing list thread and that the project page there has been updated with information on the move of the project.

**Comment by ottok** [comment]
Seems Travis-CI has PyPi integration, so we could push each tagged master branch there automatically in the future: https://docs.travis-ci.com/user/deployment/pypi/

**Comment by ericzolf** [comment]
I wouldn't want to rely too much on Travis' capabilities as it makes us dependent on GitHub/Microsoft. AFAICJ `setup.py upload` does the trick as well, could be called from within Travis but also outside of it.

**Comment by ikus060** [comment]
`setup.py upload` is not recommended to upload something to pypi.

The preferred and simple way is to use twine. Also as I mention mutiple
time, the automated build running by travis is not valid for pypi and it's
not generating the binaries using manylinux. Will need to address this
first. Pypa repository provide a very good example to get started with
manylinux. And allow to quickly generate the binaries for all the python
versions.

--
Patrik Dufresne Service Logiciel inc.
http://www.patrikdufresne.com <http://patrikdufresne.com/>/
514-971-6442
130 rue Doris
St-Colomban, QC J5K 1T9

**Comment by ikus060** [comment]
I want to bring this topic back and try to follow a bit more our contribution guide line. I want to improve the current travis CICD pipeline to build and test packages compatible with PYPi.

Since rdiff-backup has C modules, the recommended way is to use manylinux images to compile & test the pacakges.

Here some of the highlight changes I'm proposing:
1. Replace the debian:sid docker image by manylinux images
2. Remove the Dockerfile
3. Change travis pipeline to have stages:
  * test : where all our tox.ini test runs with a matrix for py35,36,37
  * deploy: where I will add a new step to build the wheel packages and push it to pypi with a matrix for manylinux2010_x86_64, manylinux2010_i686, manylinux1_x86_64, manylinux1_i686. That include py35,36,37

Question is should we keep the Makefile ?
@ericzolf @ottok Are you using that make file during your developement ? If not, I would recommend to move this logic in travis.yml or in a bash script under /tools/.

**Comment by ericzolf** [comment]
> I want to bring this topic back and try to follow a bit more our contribution guide line. I want to improve the current travis CICD pipeline to build and test packages compatible with PYPi.

We all agree with the objective, I think.

> Since rdiff-backup has C modules, the recommended way is to use manylinux images to compile & test the pacakges.

I'll trust you on this one, no clue.
 
>     1. Replace the debian:sid docker image by manylinux images
>     2. Remove the Dockerfile

I'm confused: how do you use the manylinux images? Aren't they docker images? RTFM with a link is fine.
 
>     3. Change travis pipeline to have stages:

>     * test : where all our tox.ini test runs with a matrix for py35,36,37
>     * deploy: where I will add a new step to build the wheel packages and push it to pypi with a matrix for manylinux2010_x86_64, manylinux2010_i686, manylinux1_x86_64, manylinux1_i686. That include py35,36,37

* What are the differences between the manylinux 2010 and 1?
* What about py38? It's been released since almost 2 weeks https://docs.python.org/3/whatsnew/3.8.html
* Rather as a side note, I'd like to have the slow tests taken out of the PR tests and moved to daily tests, so that we lose less time on PRs. We can improve this later.
 
> Question is should we keep the Makefile ?
> @ericzolf @ottok Are you using that make file during your developement ? If not, I would recommend to move this logic in travis.yml or in a bash script under /tools/.

I'm not, I'm only using `setup.py` and `tox`. The thing is that Otto created it for a good reason: he wanted the testing docker approach to be available locally to developers, which I think is a rather good thing. Even though I'm happy to test directly on my laptop, this isn't exactly best practice and a container is more secure. If there is a command line tool to do the same locally with travis.yml, fine with me.

This said, moving as much cruft away from the root directory as possible is in my sense, hence moving stuff to `tools` sounds good to me.

I've added this issue to the Milestone 2.0.0. Feel free to disagree but for me it belongs to goal Nr. 3

**Comment by ikus060** [comment]
@ericzolf 
>> Since rdiff-backup has C modules, the recommended way is to use manylinux images to compile & test the pacakges.

> I'll trust you on this one, no clue.

To create a wheel package that is compatible with all linux distro, we need to compile against a very old version of glibc. manylinux image provide all of this in a docker image that is simple to use.

> I'm confused: how do you use the manylinux images? Aren't they docker images? RTFM with a link is fine.

Those are docker image with multiple version of python pre-compiled. So with the same image we can build from py27 to py38 if we want. We need to use those to comply with pypi repository. Only manylinux packages can be uploaded to pypi.
Here a link to manylinux project: https://github.com/pypa/manylinux
And a demo of it usage: https://github.com/pypa/python-manylinux-demo

> What are the differences between the manylinux 2010 and 1?

Those are different docker image. maxylinux1 is based on centos5 and deprecated, but still required by some platform. manylinux2010 is base on centos6 and still suported. We can decide to use only 2010. But the effort to make manylinux1 working is minimal.

> What about py38? It's been released since almost 2 weeks https://docs.python.org/3/whatsnew/3.8.html

No worries, manylinux already provide python 3.8 environment.

> Rather as a side note, I'd like to have the slow tests taken out of the PR tests and moved to daily tests, so that we lose less time on PRs. We can improve this later.

Got it

> I'm not, I'm only using setup.py and tox. The thing is that Otto created it for a good reason: he wanted the testing docker approach to be available locally to developers, which I think is a rather good thing. Even though I'm happy to test directly on my laptop, this isn't exactly best practice and a container is more secure. If there is a command line tool to do the same locally with travis.yml, fine with me.

> This said, moving as much cruft away from the root directory as possible is in my sense, hence moving stuff to tools sounds good to me.

> I've added this issue to the Milestone 2.0.0. Feel free to disagree but for me it belongs to goal Nr. 3

I will wait for @ottok comments a bit. I'm not a big fan of Makefile for python project and prefer to stick with python tools. People who wants to use docker to run the build locally will be free to use the bash script I'm gonna provide in /tools/ directory. I will also take a very similar approach for appveyor build once I'm done with this one.

**Comment by ottok** [comment]
There should not be any conflict with Python tools vs Docker. Docker is used just as a wrapper for making the build in an isolated container which guarantees certain properties of the level of automation and documentation. Anybody can still do the build running the same Python tools manually and having them locally installed.

Anyway, I think the goal should be (as stated in https://github.com/rdiff-backup/rdiff-backup/issues/58#issuecomment-526036281) to make a automatic integration from git/Github so that latest versions show up on pypi automatically so we cater for people who which to use pypi without too much effort.

**Comment by ericzolf** [comment]
> Current PyPi maintainer @AvdN responded to me by e-mail and assured this will be fixed once the new people doing the Python 3 rewrite have established themselves and #52 has been fixed.

@AvdN we have now the control over the Savannah site, and  [#52 - now #1 of rdiff-backup.net](https://github.com/rdiff-backup/rdiff-backup.net/issues/1) is closed, can you tell us what could be the next step?

**Comment by AvdN** [comment]
I set up Otto as a maintainer on PyPI for the project a long time ago, so he should be able to do
```
python setup.py sdist
twine upload rdiff-backup_XYZ.tar.gz
```
I now made him an owner.
If you want to make pre-build binary wheel files, I can give some pointers on how I do that for ruamel.yaml using manylinux (on my local linux box), appveyor for windows and a MacOS VM for Apple.

There is also a rdiff-backup account on pypi, which is maintainer for rdiff-backup, let me know if someone wants the password for that. I am not using it (but emails for the account currently go to me).

**Comment by ericzolf** [comment]
@ottok is not very active in recent time (he shall feel free to chime in if he disagrees) and hence could you also give me the necessary rights?

Else, any pointer is more than welcome! Is https://bitbucket.org/ruamel/yaml/src/default/ still the correct repository (I see only Windows builds)?

**Comment by ottok** [comment]
For the record, PyPi project owners/access since December 2019:
![image](https://user-images.githubusercontent.com/668724/71643207-3652e780-2cbf-11ea-8827-06b816d4f2a7.png)

**Comment by ericzolf** [comment]
Yes! Than you! Next step is once we've fixed release to GitHub to release to PyPI.

**Comment by ottok** [comment]
What is the status with https://pypi.org/project/rdiff-backup/ ? I don't see anything new there even though I added you as admins in December when I got access. I assume you have some plan for an automatic release pipeline as envisioned above?

Do you mind if I do a manual beta release now so we get more testing feedback?

**Comment by ottok** [comment]
Notes on steps to upload:
```
$ cat $HOME/.pypirc
[pypi]
  username = rdiff-backup-new-version
  password = pypi-AgEIc....

$ git diff
diff --git a/Dockerfile b/Dockerfile
index 1ae1552..709762d 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -39,3 +39,9 @@ ENV RDIFF_TEST_USER testuser
 ENV RDIFF_TEST_GROUP testuser
 
 RUN useradd -ms /bin/bash --uid ${RDIFF_TEST_UID} ${RDIFF_TEST_USER}
+
+RUN DEBIAN_FRONTEND=noninteractive apt-get update -yqq && \
+    apt-get install -y --no-install-recommends \
+    python3-pip
+
+RUN python3 -m pip install --upgrade setuptools wheel auditwheel
diff --git a/Makefile b/Makefile
index 09719cd..fedfc4f 100644
--- a/Makefile
+++ b/Makefile
@@ -32,7 +32,7 @@ test-runtime-root: test-runtime-files
 
 test-runtime-slow: test-runtime-files
        @echo "=== Long running performance tests ==="
-       ${RUN_COMMAND} tox -c tox_slow.ini -e py
+       ${RUN_COMMAND} tox -c tox_slow.ini -e pypython3 setup.py sdist bdist_wheel
 
 build:
        # Build rdiff-backup (assumes src/ is in directory 'rdiff-backup' and it's
@@ -43,8 +43,8 @@ bdist_wheel:
        # Prepare wheel for deployment.
        # See the notes for target "build"
        # auditwheel unfortunately does not work with modern glibc
-       ${RUN_COMMAND} ./setup.py bdist_wheel
-       # ${RUN_COMMAND} auditwheel repair dist/*.whl
+       ${RUN_COMMAND} python3 setup.py sdist bdist_wheel
+       ${RUN_COMMAND} auditwheel repair dist/*.whl
 
$ make container
$ make bdist_wheel

$ python3 -m pip install --user --upgrade twine keyrings.alt

$ python3 -m twine upload --verbose dist/rdiff-backup-1.4.0b1.dev34+g1cce874.d20200119.tar.gz
Uploading distributions to https://upload.pypi.org/legacy/
Uploading rdiff-backup-1.4.0b1.dev34+g1cce874.d20200119.tar.gz
100%|| 301k/301k [00:01<00:00, 257kB/s]
Content received from server:
<html>
 <head>
  <title>403 Invalid or non-existent authentication information.</title>
 </head>
 <body>
  <h1>403 Invalid or non-existent authentication information.</h1>
  Access was denied to this resource.<br/><br/>
Invalid or non-existent authentication information.


 </body>
</html>
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
```

Still trying to figure out the full procedure..

**Comment by ericzolf** [comment]
Sorry, I'm still stuck on #221 (time issue, the beginning of the year was tough). I don't mind a manual upload, just leave .travis.yml alone until I've re-factored it please.

**Comment by ottok** [comment]
Ok, I figured it fully out now and uploaded:
```
$ python3 -m twine upload --verbose dist/rdiff-backup-1.4.0b2.tar.gz 
Uploading distributions to https://upload.pypi.org/legacy/
Uploading rdiff-backup-1.4.0b2.tar.gz
100%|| 301k/301k [00:02<00:00, 114kB/s]

View at:
https://pypi.org/project/rdiff-backup/1.4.0b2/
```

Notes:
- PyPi does not allow local version segments (https://www.python.org/dev/peps/pep-0440/#local-version-segments)
- As scm_version generates the version, I had to locally make a temporary tag v1.4.0b2 to get a PyPi-compatible build (https://github.com/pypa/setuptools_scm/#default-versioning-scheme)

![image](https://user-images.githubusercontent.com/668724/72872849-01064c00-3cf7-11ea-99ba-31a3f1d5c3d0.png)

**Comment by ottok** [comment]
Uploaded manually https://pypi.org/project/rdiff-backup/1.9.0b0/

**Comment by ericzolf** [comment]
I allow myself to take over the issue ownership to automate also the release to Pypi.

@ikus060 if you have time left, please review/merge my PRs.

**Comment by ikus060** [comment]
@ericzolf Sorry, I'm not present as I would like too. At least, I'm tracking the changes made to the code.
Tag me on the PR will take a look.

**Comment by ericzolf** [comment]
I'm currently stuck due to https://travis-ci.community/t/pypi-deploy-failing-on-windows-couldnt-install-pip-setuptools-twine-or-wheel/6338 on the branch [ericzolf-add-pypi-deploy-58](https://github.com/rdiff-backup/rdiff-backup/tree/ericzolf-add-pypi-deploy-58).

This given, I also learned that pypi release can only work with a "simple" looking version, i.e. _not_ something like `1.9.0b1.dev4+g8d7d85b`. Need to check if and how I can filter on such a condition.

**Comment by ericzolf** [comment]
I agree and they were tagged, but this makes development of the feature quite difficult.

Anyway the bug is already addressed: https://github.com/travis-ci/dpl/pull/1161 and https://github.com/travis-ci/dpl/pull/1162 but no clue when it'll be released.

**Comment by ericzolf** [comment]
To test we can use https://test.pypi.org/, just need to set it up in a smart way...

**Comment by ericzolf** [comment]
@ikus060 can you please make us maintainer of https://test.pypi.org/project/rdiff-backup ?

**Comment by ikus060** [comment]
@ericzolf Done
I added you as maintainer. Other user are not register to test.pypi.org

**Comment by ottok** [comment]
In https://github.com/rdiff-backup/rdiff-backup/commit/eb20edcff56c6ba83faa32c563c464a20d509bbf I enabled the commented out line `auditwheel repair dist/*.whl` but it didn't work and I am not familiar with auditwheel. Do we want to have it working and part of the build chain?

In the same test I also extended the Dockerfile. It is good practice to do release builds in a clean environment with well defined dependencies installed.

I understand the beauty of having a git tag that automatically makes everything happen, but it can be hard to get every detail in place. Releases don't happen so often, so I don't think it is that bad either if they are done manually.

**Comment by ericzolf** [comment]
> In [eb20edc](https://github.com/rdiff-backup/rdiff-backup/commit/eb20edcff56c6ba83faa32c563c464a20d509bbf) I enabled the commented out line `auditwheel repair dist/*.whl` but it didn't work and I am not familiar with auditwheel. Do we want to have it working and part of the build chain?

No, you can remove it if you're working on the Makefile, it was a try, replaced by the 3 jobs around manylinux we now have in our pipeline.

> In the same test I also extended the Dockerfile. It is good practice to do release builds in a clean environment with well defined dependencies installed.

Nothing to say about this. This said, the Travis CI environment is well defined enough for me, and using a Docker container adds even more time to the pipeline, so IMHO should be considered carefully for each use case.

> I understand the beauty of having a git tag that automatically makes everything happen, but it can be hard to get every detail in place. Releases don't happen so often, so I don't think it is that bad either if they are done manually.

Can you be more specific? We're probably two PRs away from being successful, I wouldn't want to give up now.

**Comment by ikus060** [comment]
> > I understand the beauty of having a git tag that automatically makes everything happen, but it can be hard to get every detail in place. Releases don't happen so often, so I don't think it is that bad either if they are done manually.

> Can you be more specific? We're probably two PRs away from being successful, I wouldn't want to give up now.

The way it's working right now is great. We create a tag and voilà, stuff get compiled and pushed everywhere. That is called continuous deliveries. Time where we do this manually is long gone. No body want the burden to do it manually and having everything automated make it easier to pass the ball to others.
