### ISSUE TITLE
[ENH] different name for metadata subdir

### ISSUE THREAD

**Issue by brainchild0** [rdiff-backup/rdiff-backup#580]
Currently, each backup   contains a directory called `rdiff-backup-metadata`, which holds essential data separate from  the directory tree of user files.

Beyond the remote possibility of a name collision with user data, this name  choice is less elegant than others possible due to the absence of any marking   that distinguishes it from user data. Specific prefixes might enhance usability  by separating the directory  from user data in a lexical sort or by hiding it  in a directory listing.

Putting aside the major question of backward compatibility, newer versions of the application might use a name such as `.rdiff-backup-metadata` or `@rdiff-backup-metadata`. A further possibility is making the name customizable by invocation parameters.

A   fully robust solution may be  one that detects the  sub-directory containing metadata in   an existing backup, regardless of name,  by looking for a file inside it with a particular name, and having content of a  specific "magic sequence".

**Comment by ericzolf** [comment]
Sorry, I will close this issue:

- the name is specific enough, well established and changing it would be calling for trouble with our existing users
- having it changeable with different names would be confusing and could cause even more issues. We have users with thousands of backup repos, if each could have a different metadata directory, would make it not understandable. Also rdiff-backup wouldn't be able so easily to detect that it's perhaps backing-up a back-up repository.
- nobody complained so far, so it's a theoretical issue, I don't think it's worth addressing theoretical issues (unless they address a potential data loss or anything really important).
- having a very simple name makes it also more secure on "exotic" file systems (a dot in front of a name is a Linux/UNIX convention, doesn't mean anything to Windows).

We might change the repository format but it'll be part of a bigger move and will require a lot of preparation, for migration and backward compatibility reasons.

**Comment by brainchild0** [comment]
I understand, but if you do migrate to a new format, you might consider one that keeps the metadata separate from the user data in the directory listing.

**Comment by brainchild0** [comment]
Further to the above, one solution would be to provide an option for the user for placing the user file tree in a subdirectory beneath the top level, rather than at the top level. In this scheme, the metadata location always would be in the same location, but may include fields that direct the application to find the user files beneath the top level. This solution accommodates users who prefer a clean view of the current snapshot of their backup data.
