### ISSUE TITLE
[ENH] evaluate providing support for exFAT

### ISSUE THREAD

**Issue by brainchild0** [rdiff-backup/rdiff-backup#581]
Following  #38, support has been removed for exFAT, due to limitations in the Linux kernel drivers.

Historically, memory cards have shipped with a FAT32 file system, its simpler design compared to  its  successor NTFS making it more suitable for support in small devices, which have utilized memory cards as a primary persistence medium.  Higher density memory cards are  now emerging too as an attractive medium   for backup of desktop data.

ExFAT is a relatively recent file system, adding support for larger files and larger volumes. As Linux support for exFAT is rapidly evolving, it would be useful to evaluate how recent or forthcoming developments affect the possibility of support in the application.

A few questions include the following:

- Have the problems from #38 been resolved in more recent revisions of the drivers?
- Are the developers of the drivers aware of its limitations?

Presently, the benefits of higher-capacity memory cards are only available for a backup target if reformatted to a different file system, sacrificing compatibility with non-desktop devices.

**Comment by ericzolf** [comment]
Your wish be my order! exFAT support is now there! :fireworks: 

Seriously, good point: we've never explicitly "removed" support for exFAT, it's just that the exFAT driver (probably the fuse one) used to not pass very basic tests. I now checked the new exFAT driver from Samsung (kernel 5.7+, the project you've pointed at is "only"  a back-port of it) and it does not have this flaw, so rdiff-backup works on it.

Just for sake of reference:

```
$ modinfo exfat
filename:       /lib/modules/5.11.19-300.fc34.x86_64/kernel/fs/exfat/exfat.ko.xz
author:         Samsung Electronics Co., Ltd.
description:    exFAT filesystem support
license:        GPL
alias:          fs-exfat
```

There is no place where we explicitly ban exFAT so directly closing, thanks for bringing this to our attention.

**Comment by brainchild0** [comment]
I still get an   [error message](https://github.com/rdiff-backup/rdiff-backup/commit/cba83ac2bd0b46ea41cf382e35698ce06aa57cc3).

Will this resolve when the kernel absorbs newer drivers?  I am running Linux 5.8.0-53.

**Comment by ericzolf** [comment]
That's my expectation,  yes.

**Comment by brainchild0** [comment]
But you say it resolves in Linux 5.7, and I still see it 5.8...

**Comment by ericzolf** [comment]
This is a kernel/driver issue, not a rdiff-backup issue: the test is as easy as `touch A; rm a; stat A` (on a case _insensitive_ file system); if `stat A` still gives you details about the file, the file system is deemed not reliable enough for a backup, and we won't change this. The code you've pointed to does just that and doesn't care about the name of the file system.

Now, make sure you're really using the exfat driver from the kernel and don't have the fuse driver still installed (it was a separate package on Fedora IIRC, perhaps also on your distro), or perhaps the quality of the driver increased greatly between 5.8 and 5.11, or, or, or...

If you've got more need for discussion and comparaison, ask on the mailing list, more people might have a different experience and more ideas. I can only tell you that it has nothing to do with rdiff-backup's code.

**Comment by brainchild0** [comment]
I am mounting with version 1.3.0-1 of the FUSE module.

**Comment by brainchild0** [comment]
As a quick update, even when I mount as root, the FUSE module is used.  I wonder whether my kernel  includes  exFAT support. Perhaps FUSE is considered adequate. Installing the kernel module through DKMS may be the only way to get support through the kernel.
