### ISSUE TITLE
[ENH] --no-owner and --no-perms options

### ISSUE THREAD

**Issue by brainchild0** [rdiff-backup/rdiff-backup#582]
I suggest adding a few options analogous to the current option `--no-acl`. These may include `--no-owner`, which would prevent preservation of user or group ownership, and `--no-perms`, which would do the same for basic permissions.

Many backup sources contain documents whose content is important, but lack any important or non-trivial ownership or permissions settings.  Often all files in a tree share the  same owner and permissions, which are just incidental to the local system configuration. Avoiding the hassle and overhead of saving and restoring this information may be preferred in some contexts.

**Comment by ericzolf** [comment]
You can already map a user (or a group) to another one, and permissions are generally always important, especially the executable one, so that it becomes more difficult to decide which permissions to keep and which ones to not keep, than to just keep them all. It sounds to me again like a theoretical need but let's keep the issue open for now, perhaps someone else will find the desire and the time to implement it, but IMHO it's additional complexity for little added value.

**Comment by brainchild0** [comment]
If I have a photo set, then permissions and owners are unimportant. When I restore, I would want  in the target location  whatever are the defaults for new files. 

Many file collections are just files, text documents, songs, videos, and so on. Permissions and owners are not part of what needs to be saved or restored, It is the same for many archive formats, that files are just files, so it might be slightly cleaner to let the backup creator decide whether to save metadata related to owner and permission.

*Executable* is a special case, which should always be saved.

**Comment by ericzolf** [comment]
If you restore as non root, this is mostly what you get,  but it's not forbidden to implement, I'm only saying that it isn't a priority.

**Comment by brainchild0** [comment]
So if the application lacks privileges  to set the owner and permissions  for the restored files, then it simply continues the restore operation without affecting this metadata?

**Comment by ericzolf** [comment]
Correct. It also normally doesn't give up on a single file it can't backup/restore, it just continues with the next file (not saying there can't be a bug, but that's the idea).

**Comment by brainchild0** [comment]
Do you feel   what  you're describing is how users generally prefer a backup program to behave?

**Comment by ericzolf** [comment]
This question is not relevant and I'm starting to ignore you, you're stealing my precious _volunteering_ time.

**Comment by brainchild0** [comment]
Well, sorry. For me, the preference is  that   a  restore operation would recreate the original data exactly as intended at the time of backup, *unless given an instruction to limit which data is restored*.

In the case that the running application lacks privileges to complete an otherwise intended operation, I would suggest that the application prints an error message  and exits.   An option can be offered for cases that  the user actually wishes  that the application would continue running simply without setting the file properties.

I suggest the application should never continue running but doing something different, simply  because run by a user with lower privilege.  This kind of design tends to  lead to unexpected consequences later in the user's workflow.

**Comment by ikus060** [comment]
@brainchild0 I would recommend you to properly test rdiff-backup before asking for enhancement.

If the permissions or any metadata cannot be restore, error get printed to the console and/or log file. This provide enough guidance to the user.

**Comment by brainchild0** [comment]
> If the permissions or any metadata cannot be restore, error get printed to the console and/or log file. This provide enough guidance to the user.


I understood that @ericzolf stated the opposite,  unless by  *error* you mean *warning*, in which the applications prints a message but continues running.

**Comment by ikus060** [comment]
Indeed the application continue running.

Again, Invite you to that the feature.

**Comment by brainchild0** [comment]
I think I am not able to submit a contribution at this time, but if you would consider including a submission, then you might leave the issue the open, so it would be easy to discover by someone browsing the tracker system.
