### ISSUE TITLE
Describe implications of FS warning messages

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#583]
Following is an example:

```
Warning: could not determine case sensitivity of source directory at
  <dirname>
because we can't find any files with letters in them.
It will be treated as case sensitive.
Warning: could not determine if source directory at
  <dirname>
permits trailing spaces or periods in filenames because we can't find any files.
It will be treated as permitting such files.
```

When on a FAT32 target   I saw a similar message about hard links. I no longer have a copy of the exact text, but I remember seeing no indication of how the issue would affect either the backup or the restore.

During a process of data transfer or archival any warning makes me uneasy if   it lacks clarity about the implications for the integrity of the data.

_Originally posted by @brainchild0 in https://github.com/rdiff-backup/rdiff-backup/issues/579#issuecomment-840007019_

**Comment by YoloClin** [comment]
I also have a similar recurring issue, when running a backup of my root FS while my machine is hot, I get the occasional UpdateError (presumably, the file is changing as rdiff-backup is attempting to duplicate it) or ListError permission denied.

In both cases, I care more about a 'rough' backup of my system than I do about any single file, but have no idea if those errors have rolled back the backup or similar.

Perhaps a more meaningful information message, as well as a 'rdiff-backup completed successfully but with some errors described above' message on completion or something similar?

**Comment by ericzolf** [comment]
That's an easy one and a good idea. We'll do so.

**Comment by ericzolf** [comment]
Just a note for myself, and whoever cares: both messages just mean that more "filename quoting" might be done than necessary. For example, if the source file system is deemed case sensitive but the target file system isn't, the capital letters will be quoted, even if the source file system isn't actually case sensitive. Purpose is to not lose data, at the cost of useless quoting. I'll try to find a terse(r) explanation and will add it. The same applies to trailing dots/blanks, which might get quoted even if not required.

**Comment by brainchild0** [comment]
> I'll try to find a terse(r) explanation

For me brevity would be less important than reassurance that the warning is harmless, with respect to the integrity of recovered data following a restore operation.
