### ISSUE TITLE
Change permission/mode of created files

### ISSUE THREAD

**Issue by Ma124** [rdiff-backup/rdiff-backup#59]
I want to backup my files to a remote server.
On the server the permissions are supposed to be 0750 (`rwxr-x---`) for directories and 0740 (`rwxr-----`) for files.
But when I restore my files I want to retain their original permissions which is done by `mirror_metadata.*.snapshot` how I understand it.
So I would like if their is any option besides running rdiff-backup and then `find -type d -exec chmod 0750 {} \; && find -type f -exec chmod 0740 {} \;`.

And if such an option does not exist I would like to propose:
- `--mirror-file-mode perm`: set the permissions of the mirror files to the given ones
- `--mirror-directory-mode perm`: set the permissions of the mirror directories to the given ones
- `--mirror-mode perm`: This is short for `--mirror-file-mode perm --mirror-directory-mode perm`
- `--mirror-owner uid_or_uname:gid_or_gname`: set the permissions of the mirror file to the given ones

**Comment by ericzolf** [comment]
Why don't you simply make sure that the umask of the remote user is set as you need it? something like `0027` would almost get you what you want (an executable would remain `r-x` for group, but this is no security issue as someone with read right can always copy the file to some other place and change the x-bit themself).

**Comment by Ma124** [comment]
Thank you for the quick response.
