### ISSUE TITLE
[ENH] Generate pacakge for Mac OS X

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#592]
Since Mac OS support is working, we should consider generating the package in our pipeline and provide the binary package as part of a release.

**Comment by ericzolf** [comment]
But we don't officially support Mac and we shouldn't do it until someone commits to support it actively and we've got the tests working as started at #82 else we can't claim that we are supporting MacOS.

**Comment by ikus060** [comment]
If found this solution to install on Mac OS: https://formulae.brew.sh/formula/rdiff-backup
For the time being it's enough.
