### ISSUE TITLE
[ENH] GUI

### ISSUE THREAD

**Issue by WMRamadan** [rdiff-backup/rdiff-backup#594]
## Is your feature request related to a problem? Please describe.

This tool can be made to be user friendly when including a GUI instead of running through command-line.

## Describe the solution you'd like

A simple GUI can be implemented using PyQT/PySide/GTK+/TKinter or any opensource free GUI Library.

## Describe alternatives you've considered

Most consumer back-up tools have GUI's for the non-technical user. (Apple Time Machine/Microsoft Backup and Restore)

**Comment by ikus060** [comment]
@WMRamadan You should take a look at [Rdiffweb](https://rdiffweb.org) and [Minarca](https://minarca.org)

Rdiffweb is a Web interface to browse and restore data.

While Minarca, is a more complete solution for non-technical users. It uses Rdiffweb with extra plugins for the server and provide a GUI to be installed on the desktop. Currently the GUI is written in Java. I'm working on a full re-write in Python.

Both are OpenSource and your feedback is appreciated.

**Comment by ericzolf** [comment]
@ikus060 perhaps you should add this information to the FAQ?

**Comment by WMRamadan** [comment]
> @WMRamadan You should take a look at [Rdiffweb](https://rdiffweb.org) and [Minarca](https://minarca.org)
> 
> Rdiffweb is a Web interface to browse and restore data.
> 
> While Minarca, is a more complete solution for non-technical users. It uses Rdiffweb with extra plugins for the server and provide a GUI to be installed on the desktop. Currently the GUI is written in Java. I'm working on a full re-write in Python.
> 
> Both are OpenSource and your feedback is appreciated.

I like Rdiffweb, perfect for cross-platform compatibility don't have to worry too much about the environment you are running in since it is web based.

I would very much like to be involved with your Python re-write. Are you thinking to make a platform native version like Minarca written in Python?

**Comment by ikus060** [comment]
@WMRamadan I'm re-writing the minarca-client in Python and plan to make it compatible with Linux, Windows and Mac. I'm currently in process of re-writing the core of Minarca. Then will quickly work on the user interface and the packaging for each platform. 

I've commit my intermediate work here: https://gitlab.com/ikus-soft/minarca/-/merge_requests/123

Until the foundation is written, I don't know how you could help me. I'm open to suggestion.
