### ISSUE TITLE
The system cannot find the file specified (Network Share, Windows 10)

### ISSUE THREAD

**Issue by nle-sztyler** [rdiff-backup/rdiff-backup#595]
Problem Description
I get "The system cannot find the file specified" errors (FileNotFoundError: [WinError 2]) and rdiff-backup stops working. **The file which rdiff-backup is referring too is always located in the target directory.** I think it is important to mentioned that the backup target is a network share. The problem is reproducible, and executing rdiff-backup with the same parameters several times in a row always leads to another file which couldn't be found.

Which rdiff-backup was used?
I get this error with 2.0.5 and v2.1.0a1

Which operating system do you use?
Windows 10 20H2

More information
I have the feeling that this is a synchronization problem because the "missing" file is always available when I search it manually. Maybe the network share does not reflect immediately the already transferred files but rdiff-backup tries to access them (this is a guess).

Log File (rdiff-backup 2.0.5)
[example-error-log.txt](https://github.com/rdiff-backup/rdiff-backup/files/6622788/example-error-log.txt)

**Comment by nle-sztyler** [comment]
Any feedback? Is the problem clear or already known? Can I help somehow to solve this? I would really like to use this tool. Thank you!

**Comment by ericzolf** [comment]
Sorry, I thought I had answered...
Sadly, it doesn't look like rdiff-backup is the culprit but rather the file system. I'm a bit at loss what we could do on our side. Introducing waiting time would make the backup too slow and the error is too generic to be catched, we might miss true errors.

Perhaps you can tweak the filer? Or if it's a Filer with an OS, install SSH and rdiff-backup on it and use it in client-server mode.

You could try again with -v9 and see if the debug information is more helpful, but I doubt it.

**Comment by nle-sztyler** [comment]
I will try to investigate this issue and come back to you. I don't think that my setup is special, but actual common. I am not the administrator of the network share to I am not sure which system and filesystem is used -but I will figure this out. In general, I think it is good to have this information so that it can at least be documented somewhere.
