### ISSUE TITLE
Clean-up the code with pep8 and replace tabs with spaces

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#60]
The code looks strange and more difficult to read and edit currently. That would be my next task after having got the bytes MR merged into master.

**Comment by ericzolf** [comment]
I would proceed like this:

- first commit with non important files `yapf --recursive --parallel --in-place misc setup.py python-rdiff`
- second commit with the test files `yapf --recursive --parallel --in-place testing` after checking that it doesn't break the results
- third commit with the actual source files `yapf --recursive --parallel --in-place src`, also checking that the tests aren't broken

The question is when to do it as it would conflict with any on-going pull request.

**Comment by ottok** [comment]
I suggest you do those changes now. There are no major code PRs pending, and the very old ones should be rebased on the new Python 3 codebase anyway soon.

**Comment by ericzolf** [comment]
I need #110 to be merged before I can do it, so that I'm sure I start from a sane base (tox tests wise).

**Comment by ottok** [comment]
This is now done for `testing/` and still needs to be done for `src/`. Any takers?

**Comment by ottok** [comment]
PR for `misc/`: https://github.com/rdiff-backup/rdiff-backup/pull/114

**Comment by ottok** [comment]
The PR #114 now also takes care of parts of `src/`. Great work by @elMor3no ! :muscle:

**Comment by elMor3no** [comment]
Which others need to be format?

**Comment by ericzolf** [comment]
That's an easy one :-)
Just run `tox -e flake8` and fix the code until tox and flake8 are happy and the test result is green.

**Comment by ottok** [comment]
@elMor3no If you don't have Tox and Flake installed, you can also run `make test-static` to run the tests inside a Docker container. This is all documented in the sources. Just make sure you have the latest upstream master pulled to the source you are reading.

The test results, including Flake8, are also visible on Travis-CI.org, e.g. https://travis-ci.org/rdiff-backup/rdiff-backup/jobs/580715485

**Comment by ericzolf** [comment]
Any progress on this topic? @elMor3no ?

**Comment by elMor3no** [comment]
Ohh Sorry... I dont see this notification until now... My inbox is full of trash mail now... 
I will check this in a couple of days

**Comment by ericzolf** [comment]
@elMor3no are you able to assign the issue to yourself in order to show that you're taking care of it?

On a related note, I discovered today https://fedoramagazine.org/make-your-python-code-look-good-with-black-on-fedora/ (not sure it does a better job than yapf but the output surely looks fancier :confetti_ball: - anyway, at the end of the day, flake8 needs to be happy.

**Comment by elMor3no** [comment]
Im not able to assing myself... An Owner or Collaborator need to assing me the issue...

**Comment by ericzolf** [comment]
All yours now @elMor3no !

**Comment by ericzolf** [comment]
This issue is hovering over the whole code and keeps people from doing changes to it by high risk of a conflict. It might perhaps make sense that you clean up the code starting with the first files in alphabetical order, someone could start from the end of the list, and meet with you in the middle of the list?

There are 33 files, with PRs cleaning up in group of 3 and 6, it would match. What do you think @elMor3no  ?

**Comment by elMor3no** [comment]
I will start from the top... 
I try to use `tox -e flake8` but start to have some issues...

**Comment by elMor3no** [comment]
> That's an easy one :-)
> Just run `tox -e flake8` and fix the code until tox and flake8 are happy and the test result is green.



> @elMor3no If you don't have Tox and Flake installed, you can also run `make test-static` to run the tests inside a Docker container. This is all documented in the sources. Just make sure you have the latest upstream master pulled to the source you are reading.
> 
> The test results, including Flake8, are also visible on Travis-CI.org, e.g. https://travis-ci.org/rdiff-backup/rdiff-backup/jobs/580715485

I try but i found an issue 
'
Unable to find image 'rdiff-backup-dev:debian-sid' locally
docker: Error response from daemon: pull access denied for rdiff-backup-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
'

**Comment by ottok** [comment]
@elMor3no You don't have the Docker image. Run `make all` first and then try again once the image is built. You can also just `sudo apt install flake8` and run it yourself or you can look at the latest Travis-CI log at travis-ci.org but I see you have not enabled Travis-CI.org for your repo, thus there is no CI for commits at https://github.com/elMor3no/rdiff-backup/commits/master

**Comment by elMor3no** [comment]
I have tox and flake8 install but also dont works

**Comment by ericzolf** [comment]
You don't need to use tox in this case, just call `flake8 --ignore=E501,W503 src/rdiff_backup/backup.py` (or whichever file you take first), and fix the issues until all are gone.

As a side note, if you replace all tabs with 4 blanks, you get rid already of many warnings. In case you use vi/vim, `:%s/^I/    /g` does wonders (`^I` is actually a Tab).

**Comment by elMor3no** [comment]
I will try again... Now im solving an issue in the updating the branch to get the last change before formating. 
Im having a some comflicts :(

**Comment by ottok** [comment]
Did you get your `git remote update && git rebase -i upstream/master` routine going?
I see you now Travis-ci.org working at https://travis-ci.org/elMor3no/rdiff-backup/builds – great!

Did you notice you can also see the flake8 results in the Travis logs?
![image](https://user-images.githubusercontent.com/668724/67639813-1d176e80-f8fd-11e9-84be-0157e24bbd63.png)

**Comment by elMor3no** [comment]
Yes.. i need to create a new branch but is working... 
Hopefully all works during the PR 

Thanks for the help...
