### ISSUE TITLE
[ENH] Provide a console-script entrypoint to automatically generate executable script on all platform

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#602]
## Is your feature request related to a problem? Please describe.

current version of rdiff-backup provide a mini script to launch rdiff-backup. While this script is "working" on Linux, it's not working on Windows platform. As a simple replaceent, I recommand using a setuptools entrypoint to automatically generate an executable when rdiff-backup is installed using `pip install rdiff-backup`

## Describe the solution you'd like

In setup.py we need to add 
```
entry_points = { "console_scripts": ["rdiff-backup = rdiff_backup.Main:error_check_Main" ] }
```
We also need to adapt a bit the main function call to make the arglist optional.

The same is probably true for `rdiff-backup-statistics`

**Comment by ericzolf** [comment]
Did you try it? I mean, the rdiff-backup script runs under Windows, Windows is just too stupid to recognize it as Python script,so you explicitly need to call Python. I mean, we can try, I'm just not convinced, it will solve anything.

From the docs, we might have to switch to a setup.cfg.

**Comment by ikus060** [comment]
Yes, I have tried, When installing with pip it's not possible to call `rdiff-backup` from command line. 
From a user perspective, it's not working. Since it's relatively simple to fix with an entrypoint, I would add it.

**Comment by ericzolf** [comment]
My question was more ifyou've tried it with an entry point and if it really works under Windows. I'm just wondering which kind of magic could make it work...

**Comment by ikus060** [comment]
Yes, it's working with an entry_point. When an entry_point is created, setuptools generate a "rdiff-backup.exe" along with a "rdiff-backup-script.py" that get launch when calling rdiff-backup.

I'm using it for Minarca as an example. I will submit a PR if you are ok with this.

**Comment by ericzolf** [comment]
Please do, that sounds really nice. I'm a bit concerned by the special imports in the current script, but perhaps Python does there also the needed magic.

**Comment by ericzolf** [comment]
It sounds like this could be the solution to #733 (the "scripts [must] be called .py [under Windows]" part). Did you do any progress on this resp. could this be something you do for 2.2.0?

**Comment by ericzolf** [comment]
This has been done, I'm surprised the issue hasn't been closed automatically...
