### ISSUE TITLE
Backup of symlinks fails on Windows when backing up root directory

### ISSUE THREAD

**Issue by desseim** [rdiff-backup/rdiff-backup#608]
On Windows 10 Home 21H1, using `v2.1.0a1` 64-bit build:

`rdiff-backup.exe backup C:\/Users D:\/backup_dir` seems to work fine, but
`rdiff-backup.exe backup --include "C:/Users/" --exclude "C:/" C:\/ D:\/backup_dir` fails with the following error as it tries to backup the first symbolic link it encounters in the source directory:

```
Exception 'symlink: src should be string, bytes or os.PathLike, not NoneType' raised of class '<class 'TypeError'>':
  File "rdiff_backup\robust.py", line 94, in check_common_error
  File "rdiff_backup\rpath.py", line 1555, in copy
  File "rdiff_backup\rpath.py", line 771, in symlink

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 38, in main_run_and_exit
  File "rdiff_backup\Main.py", line 95, in _main_run
  File "rdiffbackup\actions\backup.py", line 148, in run
  File "rdiff_backup\backup.py", line 39, in Mirror
  File "rdiff_backup\backup.py", line 198, in patch
  File "rdiff_backup\rorpiter.py", line 146, in __call__
  File "rdiff_backup\backup.py", line 603, in fast_process_file
  File "rdiff_backup\backup.py", line 658, in _patch_to_temp
  File "rdiff_backup\backup.py", line 700, in _patch_snapshot_to_temp
  File "rdiff_backup\backup.py", line 746, in _write_special
  File "rdiff_backup\robust.py", line 94, in check_common_error
  File "rdiff_backup\rpath.py", line 1555, in copy
  File "rdiff_backup\rpath.py", line 771, in symlink
TypeError: symlink: src should be string, bytes or os.PathLike, not NoneType
```

The symlink in question is `C:\Users\TheUser\AppData\Local\Application Data`, but if I explicitly exclude it the backup fails with the same error on the next symlink (`C:\Users\TheUser\AppData\Local\History` in this case).

Adding `--exclude-symbolic-links` to the backup command, it proceeds without error.

Both source and destination drives use NTFS.
FS abilities:
```
-----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 On
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       On
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
```
```
-----------------------------------------------------------------
Detected abilities for destination (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          Off
  Directory inc permissions                    Off
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   On
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 On
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       On
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
```

So (unless I'm mistaken ofc) the issues I see here:
1. backing up the same directory, either with `C:\/` or `C:\/Users` as the source directory, should yield the same result
2. symbolic links should be supported, or, if intentionally not, they should be excluded by default (or at least a warning or info should be displayed and no `TypeError` should occur)

Thanks!

**Comment by ericzolf** [comment]
It's strange because there is code which excludes symlinks under Windows: https://github.com/rdiff-backup/rdiff-backup/blob/6ccfe9bc7d6c07776633c4f5268bad549c815b05/src/rdiffbackup/locations/directory.py#L53 
I guess that it's the order which makes the difference... Can your try if it makes a difference if you place the exclude of symlinks before or after the other include/exclude statements?

**Comment by desseim** [comment]
Indeed, it seems dependent on the order the `--exclude-symbolic-links` and include/exclude options are stated in the command.

✔️ `rdiff-backup.exe backup --exclude-symbolic-links --include "C:/Users/" --exclude "C:/" C:\/ D:\/backup_dir`: proceeds
❌ `rdiff-backup.exe backup --include "C:/Users/" --exclude "C:/" --exclude-symbolic-links C:\/ D:\/backup_dir`: fails at the first symlink
✔️ `rdiff-backup.exe backup C:\/Users D:\/backup_dir`: proceeds
❌ `rdiff-backup.exe backup --include "C:/Users/" C:\/Users D:\/backup_dir`: fails at the first symlink

**Comment by ericzolf** [comment]
OK, the fix will be simple, I'll insert the option at the beginning instead of appending it at the end. Thinking about it, the code should also check if the option isn't already there before inserting it.

This said, `os.readlink` seems to work just fine under Windows, albeit with a strange returned value (but not evaluated by the code AFAICJ):

```
>>> os.readlink(b'AppData\Local\History')          
b'\\\\?\\C:\\Users\\vagrant\\AppData\\Local\\Microsoft\\Windows\\History' 
>>> os.readlink(b'AppData/Local/History') 
b'\\\\?\\C:\\Users\\vagrant\\AppData\\Local\\Microsoft\\Windows\\History' 
```

So, I'm still wondering why we  couldn't support them under Windows, but that's another story...

**Comment by ericzolf** [comment]
Ah, @desseim if you have Python 3.9 (3.8 should be OK) on your machine and could try it yourself:
```
python
>>> import os
>>> os.readlink(b'C:/Users/MyUser/AppData/Local/History')
```
the result could be interesting, perhaps it's an access right issue (the vagrant user is admin AFAIK).

**Comment by ericzolf** [comment]
The other story to support symlinks if you're interested: https://github.com/rdiff-backup/rdiff-backup/issues/484

**Comment by desseim** [comment]
Thank you for following up.
I think there are 2 issues here: option parsing and symlink support.

As for option parsing, obviously putting the `exclude-symbolic-links` option in front should fix this one particular bug, but I'd assume that unless the option parsing / processing is made order-independent (save for the order of each `include` / `exclude` option ofc) it will likely lead to more such edge-case bugs / headaches. I haven't looked into the code base though, so I may be wrong.

As for symlink support in Windows, I am personally fine doing without the feature for now as long as it can be disabled.
I'll gladly help investigating it though, if I can. The user I was running `rdiff-backup` under is an administrator account, and seems able to read symbolic links fine from a Python 3.9 non-elevated interpreter:
````python
>>> os.readlink(b'C:/Users/MyUser/AppData/Local/History')
b'\\\\?\\C:\\Users\\MyUser\\AppData\\Local\\Microsoft\\Windows\\History'
>>> os.path.realpath(b'C:/Users/MyUser/AppData/Local/History')
b'C:\\Users\\MyUser\\AppData\\Local\\Microsoft\\Windows\\History'
````

**Comment by ericzolf** [comment]
I anyway want to revamp the include/exclude mechanism so the fix will do for now.

Regarding support of symlinks, as said, there is another issue to look into it. You're more than welcome to own it.

**Comment by desseim** [comment]
Got it, thanks for the fix 👍
Should I close the issue after testing once a new release is out or let you manage it?

As for the other issue, let me know if you'd like me to run other tests to investigate the support of symlink backup on my setup.
I've subscribed to the issue for now.

**Comment by desseim** [comment]
I figured more about the original issue. I'm not sure if this should be considered an issue nor what kind (ACL support bug / lack of support / expected error which shouldn't be terminating / something else ?) so I leave it here as a comment for now.

It seems the symlinks which the backup fail on are Windows "junctions" set up by default for backward compatibility purposes but with access rights set as denied to everyone. Files are accessible through these junctions, but their content is not enumerable.
More details in [this blogpost](<https://rakhesh.com/windows/start-menu-and-other-directory-junctions-access-denied/>).

I'd guess that they should be ignored by the backup if the user has no access right to them, but I'm unsure of the state of ACL support under Windows.
