### ISSUE TITLE
Remove os_walk function from rdiff_backup/FilenameMapping.py

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#61]
<a href="https://github.com/ericzolf"><img src="https://avatars3.githubusercontent.com/u/3105685?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericzolf](https://github.com/ericzolf)**
_Sunday Apr 14, 2019 at 09:04 GMT_
_Originally opened as https://github.com/ericzolf/rdiff-backup/issues/2_

----

The function was only introduced to support Python 2.2 where os.walk didn't yet exist, and can be removed.

**Comment by frankcrawford** [comment]
Eric,
If ollytom already has this fix in his repo, are you really just after someone to turn this into a PR?

**Comment by ericzolf** [comment]
My main purpose was to give people a chance to get involved in the project (and win a t-shirt at Hacktoberfest :wink:), so @olllytom should create the PR from his branch (there shouldn't be any special rights required; if so, shout!).

**Comment by frankcrawford** [comment]
Okay @ollytom go for it, but if he doesn't before the end of the month, I may take it up, so I can get a shirt.  :-)
