### ISSUE TITLE
[ENH] Remove action with new syntax should support "B"/"before" time format

### ISSUE THREAD

**Issue by mbs** [rdiff-backup/rdiff-backup#618]
## Is your feature request related to a problem? Please describe.

Problem: I have to use the old options to use the "B" time format in "--remove-older-than".

## Describe the solution you'd like

Solution: In the new syntax, I'd like support for the "B" time format.

Ex. "--remove-older-than 2B" for removing increments before 2ct before the latest.

## Describe alternatives you've considered

Using the old syntax works, but throws warnings.

**Comment by ericzolf** [comment]
What about: `rdiff-backup remove increments --older-than 2B <backup_repo>`? Please re-open if you think I missed the point...
