### ISSUE TITLE
[QUESTION] How to de-escape filenames

### ISSUE THREAD

**Issue by eyolf** [rdiff-backup/rdiff-backup#627]
This is not really a bug report, but rather a question:

Is there a simple way to de-escape file names where uppercase letters have been escaped? I have a directory of files which previously were on a FAT file system. The original directory is gone, and I would like to return the files to their previous names. Is there a simple way to do that, either from within rdiff or with some other tool?

**Comment by ericzolf** [comment]
It should be as simple as using the restore feature of rdiff-backup, check in the manpage /docs the restore-as-of option.

**Comment by eyolf** [comment]
I've tried that, but I get the error message "Fatal Error: Could not find rdiff-backup repository at [directory]" ̣– logically, since the files come from an external drive from an old system, and I no longer have the metadata from the original backup.

**Comment by ericzolf** [comment]
Ah. No simple way. You will need some shell or Python magic to rename the files. Ask on the mailing list, someone has perhaps already done it.

**Comment by ericzolf** [comment]
No further question. Closing.
