### ISSUE TITLE
Decide and implement a generic documentation handling method

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#64]
The problem is bigger than initially described (see below the line):  we need to streamline the distribution process, also when it comes to documentation: we have currently a mixture of txt, md and html, and we should all align and handle similarly. 

----

During installation:

```
sudo python3 dist/setup.py install --prefix=/usr/local
[...]
running install_data
error: can't copy 'FAQ.html': doesn't exist or not a regular file
```
FAQ-body.html does exist but not FAQ.html, which is actually created in `dist/makedist` with the function `MakeHTML("FAQ", "rdiff-backup FAQ")`.

**Comment by ericzolf** [comment]
My suggestion: transform all documentation in markdown and generate HTML & co using pandoc or similar during the distribution process.

We can also switch to asciidoctor and even generate PDF and more easily :grin:

**Comment by frankcrawford** [comment]
While the idea of transforming all the files into markdown, as a simpler issue, both FAQ-body.html and example-body.html can both be permanently transformed into FAQ.html and example.html.

All that tools/makedist does in this particular case, is to add a header and footer on, for two files, one html and the other wml.

It looks like wml was used in one of the previous websites, but we no longer do, so we don't need the wml file anymore.

I'd suggest at present we just convert these two to html and drop all reference to wml, and then as a longer process covert all the documents to a generic document format.

What do you think about this as a first step?
