### ISSUE TITLE
[BUG] I/O Error when backing up to a remote mount via gocryptfs

### ISSUE THREAD

**Issue by nightbluepn** [rdiff-backup/rdiff-backup#641]
## Bug summary

Rdiff-backup fails during target filesystem ability check when the target folder is the decrypted view of a gocryptfs encrypted folder on a WebDAV mount (davfs2).

## Version, Python, Operating System

```yaml
2021-11-20 13:57:11.871218 +0100  <CLIENT-1717058>  Using rdiff-backup version 2.0.5
2021-11-20 13:57:11.871352 +0100  <CLIENT-1717058>      with cpython /usr/bin/python version 3.9.7
2021-11-20 13:57:11.875076 +0100  <CLIENT-1717058>      on Linux-5.10.76-1-lts-x86_64-with-glibc2.33, fs encoding utf-8
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup -v 9 /tmp/test/ /backup/hidrive-plain/rdiff-backup/test
```

## What happened and what did you expect?

I got an Input/Output error while rdiff-backup checked for target filesystem abilities, instead of rdiff-backup backing up the test folder.

## More information

Log : [V9-log.txt](https://github.com/rdiff-backup/rdiff-backup/files/7574579/V9-log.txt)

- Backing up to the Webdav mount directly (no gocryptfs) works
- Backing up to a decrypted view of a gocryptfs encrypted folder works, if the encrypted folder is on the local file system
- The WebDAV remote is mounted using davfs2
- I had similar problems when then remote was mounted using SMB3

Thanks for your help guys.

**Comment by ericzolf** [comment]
From the look of it, the error is within the Python code, not in the rdiff-backup code. It could be a bug in Python, or something very special with your file system.

What happens if you do something like:

```python
mkdir -p /backup/hidrive-plain/rdiff-backup/testX/rdiff-backup-data/rdiff-backup.tmp.0
python3
> import os
> path = '/backup/hidrive-plain/rdiff-backup/testX/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir'
> os.mkdir(path)
> import shutil
> shutil.rmtree(path)
> shutil.rmtree('/backup/hidrive-plain/rdiff-backup/testX')
```

**Comment by ericzolf** [comment]
After some more thinking, best would be to also create a python script and call it (note that `testX` will be removed):

```python
#!/usr/bin/python
import os
import shutil
base_path = '/backup/hidrive-plain/rdiff-backup/testX'
path = os.path.join(base_path, 'rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir')
os.makedirs(path)
shutil.rmtree(path)
shutil.rmtree(base_path)
```
Doing the test once "manually" and once with the script, it should tell us if there is possibly a timing issue, we had this already with exFAT-Fuse...

**Comment by nightbluepn** [comment]
Thanks for your reply. This is what i got:

```
$ mkdir -p /backup/hidrive-plain/rdiff-backup/test8/rdiff-backup-data/rdiff-backup.tmp.0
$ python
>>> import os
>>> path = '/backup/hidrive-plain/rdiff-backup/test8/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir'
>>> os.mkdir(path)
>>> import shutil
>>> shutil.rmtree(path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/shutil.py", line 730, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.9/shutil.py", line 728, in rmtree
    os.rmdir(path)
OSError: [Errno 5] Input/output error: '/backup/hidrive-plain/rdiff-backup/test8/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir'
>>> shutil.rmtree('/backup/hidrive-plain/rdiff-backup/test8')
>>>
```
i.e. the last command succeeds.
After that, the test8 directory still exists though:
```
$ tree /backup/hidrive-plain/rdiff-backup/test8
/backup/hidrive-plain/rdiff-backup/test8
└── rdiff-backup-data
```

Interestingly, if i do (in the shell):
```
$ mkdir /backup/hidrive-plain/rdiff-backup/test9/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir
$ rm -r /backup/hidrive-plain/rdiff-backup/test9/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir
rm: cannot remove '/backup/hidrive-plain/rdiff-backup/test8/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir': Input/output error
```
**but** if i remove the '.tmp.0' from the path, all works well:
```
$ mkdir -p /backup/hidrive-plain/rdiff-backup/test0/rdiff-backup-data/rdiff-backup/high_perms_dir
$ rm -r /backup/hidrive-plain/rdiff-backup/test0/rdiff-backup-data/rdiff-backup/high_perms_dir
```
 It doesn't seem to relate to the dots in the path though, since i can create and remove `/backup/hidrive-plain/rdiff-backup.tmp.0` just fine.

**Comment by ericzolf** [comment]
It could be a limit in the path length?

That is very weird and means for me at this stage that rdiff-backup does the right thing: it refuses to backup to a file system which doesn't show a sound behavior. You should probably address the bug to the gocryptfs author, I'm not sure we will be able to address it to your advantage.

**Comment by nightbluepn** [comment]
More weirdness - changing the python script paths to:
```
base_path = '/backup/hidrive-plain'
path = os.path.join(base_path, 'rdiff-backup.tmp.0/high_perms_dir')
```
gives
```
Traceback (most recent call last):
  File "/backup/./test.py", line 9, in <module>
    shutil.rmtree(base_path)
  File "/usr/lib/python3.9/shutil.py", line 726, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.9/shutil.py", line 663, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.9/shutil.py", line 663, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.9/shutil.py", line 663, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.9/shutil.py", line 667, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.9/shutil.py", line 665, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 5] Input/output error: 'high_perms_dir'
```

**Comment by nightbluepn** [comment]
> It could be a limit in the path length?
> 
> That is very weird and means for me at this stage that rdiff-backup does the right thing: it refuses to backup to a file system which doesn't show a sound behavior. You should probably address the bug to the gocryptfs author, I'm not sure we will be able to address it to your advantage.

I agree, this has nothing to do with rdiff-backup anymore, i will take it to them. Thanks for your time and willingness to help, i appreciate it.
