### ISSUE TITLE
Outdated rdiff-backup examples

### ISSUE THREAD

**Issue by daholzfeind** [rdiff-backup/rdiff-backup#661]
I tried to follow the examples on the official documentation https://rdiff-backup.net/docs/examples.html. The examples worked for me, but they throw a deprecation warning:
```
>rdiff-backup.exe source target
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.
```
After a long observation and blaming of the source code I was finally able to find a solution in https://github.com/rdiff-backup/rdiff-backup/pull/517. Also `rdiff-backup.exe --new --help` was not so helpful for me, since I've never used rdiff-backup in a console. 

Please update the command in the documentation according to the new syntax. 

Thanks!

**Comment by ericzolf** [comment]
You're using an alpha version, which is far from being finished,  and stable. Documentation will follow.
