### ISSUE TITLE
Issue : How to install rdiff-backup on synology DSM 7 ?

### ISSUE THREAD

**Issue by SVANNER** [rdiff-backup/rdiff-backup#665]
I would like to backup Linux Ubuntu folders into Synology DSM 7. I found how to install rdiff-backup on Ubuntu, but it seems that it has to be installed on the Synology. I do not found a way to install this on a DSM 7 Synology .

Could you please give some highlights ?

Thanks a lot,

S. VAN NEROM

**Comment by ericzolf** [comment]
It's a very specific question and difficult to answer. If https://github.com/rdiff-backup/rdiff-backup#19-other-linux-and-unx-oid-systems-eg-bsd-from-pypi doesn't help, then ask on the mailing list. The chances that someone else has done it are higher there.

**Comment by SVANNER** [comment]
Hi,

Thanks for your answer. Here is what i got : 

On a Synology 920+, (with DSM 7.0.1), i got no issue installng rdiff-backup, but on a Synology DS 418+ (also running DSM 7.0.1) i got the following output  running **sudo pip3 install rdiff-backup**:

Collecting rdiff-backup
  Using cached rdiff-backup-2.0.5.tar.gz (456 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (from rdiff-backup) (49.2.1)
Using legacy 'setup.py install' for rdiff-backup, since package 'wheel' is not installed.
Installing collected packages: rdiff-backup
    Running setup.py install for rdiff-backup ... error
    ERROR: Command errored out with exit status 1:
     command: /bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6todli1a/rdiff-backup_90d973edac9d42c08c9b8a72ac485ad2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6todli1a/rdiff-backup_90d973edac9d42c08c9b8a72ac485ad2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9e0bm3nc/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/rdiff-backup
         cwd: /tmp/pip-install-6todli1a/rdiff-backup_90d973edac9d42c08c9b8a72ac485ad2/
    Complete output (54 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    running build_templates
    templating tools/rdiff-backup.spec.template -> build/rdiff-backup.spec
    creating build
    templating tools/rdiff-backup.spec.template-fedora -> build/rdiff-backup.fedora.spec
    templating docs/rdiff-backup.1 -> build/rdiff-backup.1
    templating docs/rdiff-backup-statistics.1 -> build/rdiff-backup-statistics.1
    creating build/lib.linux-aarch64-3.8
    creating build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/win_acls.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/increment.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/Security.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/log.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/connection.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/librsync.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/manage.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/eas_acls.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/TempFile.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/longname.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/Rdiff.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/Globals.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/robust.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/selection.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/restore.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/backup.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/rorpiter.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/iterfile.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/SetConnections.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/user_group.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/Time.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/regress.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/FilenameMapping.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/__init__.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/metadata.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/Main.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/Hardlink.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/fs_abilities.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/hash.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/statistics.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/rpath.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    copying src/rdiff_backup/compare.py -> build/lib.linux-aarch64-3.8/rdiff_backup
    running build_ext
    building 'rdiff_backup.C' extension
    creating build/temp.linux-aarch64-3.8
    creating build/temp.linux-aarch64-3.8/src
    /usr/local/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-wrap-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DOPENSSL_NO_SSL3 -DOPENSSL_NO_SSL2 -DSYNOPLAT_F_ARMV8 -O2 -include /usr/syno/include/platformconfig.h -DSYNO_ENVIRONMENT -DBUILD_ARCH=64 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DSYNO_RUNNING_DSM_BUILD_SYSTEM -g -pipe -fstack-protector-strong -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -O2 -Wno-unused-result -fPIC -I/usr/include/python3.8 -c src/cmodule.c -o build/temp.linux-aarch64-3.8/src/cmodule.o
    unable to execute '/usr/local/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-wrap-gcc': No such file or directory
    error: command '/usr/local/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-wrap-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6todli1a/rdiff-backup_90d973edac9d42c08c9b8a72ac485ad2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6todli1a/rdiff-backup_90d973edac9d42c08c9b8a72ac485ad2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9e0bm3nc/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/rdiff-backup Check the logs for full command output.

**Comment by ericzolf** [comment]
Did you see the note at the end of the chapter I linked? It's an ARM machine whereas the DS920+ is an Intel machine with pre-compiled modules.

**Comment by SVANNER** [comment]
Yes indeed ! I completely forgot the DS 418 is an ARM machine ! Thanks a lot for the explanation !

**Comment by ericzolf** [comment]
You're welcome, closing!
