### ISSUE TITLE
[BUG] Character device with major/minor 0/0 handled incorrectly

### ISSUE THREAD

**Issue by rrendec** [rdiff-backup/rdiff-backup#678]
[rdiff-backup.log](https://github.com/rdiff-backup/rdiff-backup/files/8191915/rdiff-backup.log)
## Bug summary

A special character device file with major/minor numbers of 0/0 is handled incorrectly when the backup destination appears to support special files and in fact it doesn't.

## Version, Python, Operating System

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```
<CLIENT-6440>  Using rdiff-backup version 2.0.5  
<CLIENT-6440>   with cpython /usr/bin/python3 version 3.10.2 
<CLIENT-6440>   on Linux-5.16.12-200.fc35.x86_64-x86_64-with-glibc2.34, fs encoding utf-8
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup --remote-schema 'sudo -u rrendec %s' /test/src 'rdiff-backup --server'::/test/dst
```

## What happened and what did you expect?

rdiff-backup crashed while trying to copy this file to the destination:
```
ls -l /test/src/d/foo 
c--------- 1 100000 100000 0, 0 Mar  5 21:43 /test/src/d/foo
```

The destination filesystem is a CIFS mount and does not support special device files. The problem appears only when the major/minor numbers are 0/0. Other device files are created without any problem as regular files on the destination filesystem. This is likely because rdiff-backup expects to be able to create a 0/0 device as a regular user - which is true for a standard filesystem such as ext4. I'm assuming that the problem does not appear with other device files than 0/0 because rdiff-backup knows it can't create them as a regular user and falls back to creating a regular file and storing the metadata separately.

## More information

Crash stack trace:
```
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/Main.py", line 353, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/Main.py", line 442, in Backup
    backup.Mirror(rpin, rpout)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/backup.py", line 39, in Mirror
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/connection.py", line 439, in reval
    raise result
FileNotFoundError: [Errno 2] No such file or directory: b'/test/dst/d/rdiff-backup.tmp.3'
Fatal Error: Lost connection to the remote system

The full output (using -v9) is attached as a file.

**Comment by ericzolf** [comment]
I hesitate to add a specific check just for this one "impossible" device. This means code complexity and performance impact for everybody.
I'm happy to reconsider my position if you can give me a valid reason for having this file, but it seems rather constructed for now.
It's not saying I won't fix it, I might but I need to weight advantages and disadvantages.

**Comment by rrendec** [comment]
Fair enough. I was intrigued myself about these mysterious files and did a little bit more research. As it turns out, they are called whiteout files and they are used by overlayfs when you delete a file that belongs to one of the lower layers. Since the lower layers are read-only, a whiteout file is created in the upper read-write layer to mark that the file has been deleted, basically masking the file in the lower layers.

This kind of files is very likely to be encountered in real-life when you create a backup of the storage area of Docker containers (from outside the containers). In fact, this is exactly how I found this problem. The example I provided looks "constructed" because it is :) I isolated/reproduced the problem outside the real tree where I had found the problem. But that doesn't make it any less real.

For what is worth, I checked the Linux kernel code, and whiteout files have special permission handling in the `mknod` function the generic VFS layer. Any user is allowed to create a char device with major/minor 0/0, whereas for any other device file `CAP_MKNOD` is required. If you are curious, check the `vfs_mknod` function.

**Comment by ericzolf** [comment]
Ok, fair enough. I'll look into it, though a merge request wouldn't hurt, if you fancy.

**Comment by rrendec** [comment]
Sure, I can try to fix it and make a merge request, but it would be nice if you could give me some hints on where to look first. I already looked at the code when I found the problem, thinking it would be an easy fix, and quickly got lost in the various classes.

What puzzles me is that I see the wrong behavior only for whiteout files and not for other char device files. That makes me think that whiteout files already have special handling in rdiff-backup, based on the fact that any user is allowed to create them.

**Comment by ericzolf** [comment]
Yes, sorry, it's not an easy one, I'm in the middle of reshuffling and documenting (and understanding) the code, which I took over, and it's a bit all over the place currently.

I would start with the `makedev` function of the rpath.py file, it looks to me like it should actually capture and address your use case. Possibly your use case throws a specific error currently not captured.

**Comment by ericzolf** [comment]
I tried to repeat the issue on a vfat filesystem but it works properly there. Is your CIFS drive a samba drive or "pure" Windows?

**Comment by ericzolf** [comment]
At least, I couldn't reproduce the issue on a true Windows share:

On Windows:

```
net share temp=C:\temp /grant:vagrant,FULL
```

On Linux then:

```
sudo mount -t cifs -o username=vagrant,password=vagrant,uid=1000,gid=1000,forceuid //192.168.121.252/temp /mnt
mkdir /tmp/from
mknod /tmp/from/bla c 0 0
# using sudo in front to sudo back into my own user
sudo rdiff-backup --remote-schema 'sudo -u myuser %s' /tmp/from 'rdiff-backup --server'::/mnt/bak
rdiff-backup --restore-as-of now /mnt/bak /tmp/to
```
I get back my character device...

**Comment by ericzolf** [comment]
OK, I managed to get a samba server running, but I can't either reproduce your issue (approach is basically the same as described above). I definitely need some more information in order to reproduce the issue.

For example. you could try, as your user `rrendec`:

```
$ python
Python 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stat, os
>>> os.mknod('/mnt/myzerodev', stat.S_IFCHR | 0o600, os.makedev(0, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 1] Operation not permitted
```

**Comment by rrendec** [comment]
Sorry for the late reply! You are right, everything works as expected with vfat (and likely any destination filesystem that does _not_ support UNIX-ish attributes such as uid/gid/mode). A pure Windows share is similar, since it doesn't support any of the UNIX stuff by default.

My CIFS drive is Samba, but I think it's all about the mount options. I'm using version 1.0 of the CIFS protocol to force off the UNIX extensions, which otherwise would be active by default. These are all my mount options (following the `-o` parameter to `mount`). The last two of them probably make the difference.
```
username=rrendec,uid=rrendec,gid=rrendec,vers=1.0,nouser_xattr
```

I did the Python test and I'm getting a different error code (errno 13 instead of 1). Maybe that affects the filesystem feature tests in rdiff-backup?
```
$ python
Python 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stat, os
>>> os.mknod('/mnt/myzerodev', stat.S_IFCHR | 0o600, os.makedev(0, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 13] Permission denied
```

**Comment by ericzolf** [comment]
I can't reproduce the behaviour for some reason.

Can you patch the `rdiff_backup/rpath.py` file and see if it solves your issue? The diff in the `makedev` should roughly look like this:

```
diff --git a/src/rdiff_backup/rpath.py b/src/rdiff_backup/rpath.py
index abf8e6a..3441580 100644
--- a/src/rdiff_backup/rpath.py
+++ b/src/rdiff_backup/rpath.py
@@ -1240,7 +1240,8 @@ class RPath(RORPath):
             self.conn.os.mknod(self.path, mode,
                                self.conn.os.makedev(major, minor))
         except (OSError, AttributeError) as e:
-            if isinstance(e, AttributeError) or e.errno == errno.EPERM:
+            if (isinstance(e, AttributeError)
+                    or e.errno == errno.EPERM or e.errno == errno.EACCES):
                 # AttributeError will be raised by Python 2.2, which
                 # doesn't have os.mknod
                 log.Log("unable to mknod device file {df} - "
```

(`EPERM` is 1 and `EACCES` is 13 on my Linux)

**Comment by ericzolf** [comment]
OK, I got it now: it was indeed due to the vers=1.0 (I didn't realize that I need to set the `min server protocol` option to `NT1` on the server side to allow for it). My patch then fixes the one issue you reported but fails then on ACLs. Using the `--no-acls` option fixes the issue though.

This said, it seems to me that the option `vers=1.0` makes the whole file system quite unreliable, so that it doesn't seem a good choice for a backup. Using the option `noposix` instead seems to make it more reliable, then it works without the patch, and ACLs (lack of) support is properly recognized.

**Comment by rrendec** [comment]
Thank you so much for taking the time to look into this and fix the problem. I appreciate it! I tested, and the problem is fixed on my end too.

You are right, the `noposix` option seems to be better than `vers=1.0`. This is the configuration I've been using for years, and I can't even remember why I did it like this. So, double thanks for pointing this out!
