### ISSUE TITLE
[DOC] FAQ entry on using UTC as TZ on Windows seems outdated

### ISSUE THREAD

**Issue by desseim** [rdiff-backup/rdiff-backup#692]
The FAQ, which is referred to in several other places in the documentation, has [an entry](<https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/FAQ.adoc#22-how-can-rdiff-backup-use-utc-as-the-timezone>) about using UTC as timezone:

> 22. How can rdiff-backup use UTC as the timezone?
> Like other Unix and Python programs, rdiff-backup respects the `TZ` environment variable, which can be used to temporarily change the timezone. On Unix, simply set `TZ=UTC` either in your shell, or on the command line used to run rdiff-backup. On Windows, the command USE `TZ=UTC` sets the `%TZ%` environment variable, and can be used either in a batch script, or at the DOS prompt.

This is an important use case, but I can't get the Windows directives to work (under Windows 10 at least): there is no `TZ` environment variable preset and there is no `USE` command as far as I know.

If it is correct, it should be clarified.
I think that it is outdated though, in which case it should be updated, possibly with a way to set a specific timezone in the scope of a process, like in Linux. The only ways I know of in Windows modify the system timezone.

**Comment by ericzolf** [comment]
I don't know where the `USE` commands comes from, but it works as explained with `SET` instead. The document  https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/tzset explains the format of the TZ variable under Windows, which is different from under Linux, but works with the given example:

```
vagrant@WIN-154UNKLGRT2 C:\Users\vagrant>set TZ=UTC

vagrant@WIN-154UNKLGRT2 C:\Users\vagrant>python
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.now().astimezone().tzinfo 
datetime.timezone(datetime.timedelta(0), 'UTC') 
```

Do you feel like proposing a pull request to fix the docs accordingly?

**Comment by desseim** [comment]
Thanks.
I came across that `TZ` syntax documentation from Microsoft but it hadn't worked for me, so I tried again as per your example but again it had no effect in my environment:

```
PS > .\rdiff-backup.exe backup 'C:/example/dir/' 'C:/temp/backup'
Symbolic links excluded by default on Windows
PS > set TZ=UTC
PS > .\rdiff-backup.exe backup 'C:/example/dir/' 'C:/temp/backup.utc'
Symbolic links excluded by default on Windows
```

then check with:

```
$ zdiff -s /mnt/c/temp/backup/rdiff-backup-data/mirror_metadata.2022-04-19Txx-xx-xx+02-00.snapshot.gz /mnt/c/temp/backup.utc/rdiff-backup-data/mirror_metadata.2022-04-19Txx-xx-xx+02-00.snapshot.gz
Files /dev/fd/5 and - are identical
```

The backed up files also have the same timestamps.

I also tried your exact python example and it reported my system timezone, not UTC.

Not sure what the difference in environment might be. Is `set` somehow aliased to something on your system?
I am on Windows 10 Home 21H2, in a fairly vanilla state.

I can send a doc update PR once we've figured this out and I've managed to get something to work on my system, sure.

**Comment by ericzolf** [comment]
`set` is a command since I can think and I've used Windows (these are many years), it existed already on DOS. Ah, you are using the PowerShell whereas I'm using "good old" `cmd`. If I interpret correctly https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.2 you need to use a command of the form `$Env:TZ = 'UTC'`. We're not testing explicitly running rdiff-backup under PowerShell, but feel free to explain both options.

**Comment by desseim** [comment]
Ah, my bad. I think I got a bit of a tunnel vision from the issue I was working on; I had indeed tested with `cmd.exe` and with `$env:TZ` (among a bunch of other things), but was somehow looking for differences in recorded metadata when obviously none is to be expected there in this case.
Anyway, sorry for the bother.

I see what it does now, thanks. I'll submit a small PR for the FAQ entry.
