### ISSUE TITLE
[ENH] Documentation for using rdiff-backup as a module

### ISSUE THREAD

**Issue by bordaigorl** [rdiff-backup/rdiff-backup#703]
The documentation details how to use rdiff-backup as a CLI tool.
I could not find any documentation regarding using rdiff-backup as a module in a python project.
Of course one can spawn a subprocess using the CLI interface, but that seems like a waste and makes interpreting the output very clunky.
Imagine you have a project which establishes a SSH connection via Paramiko and as a subtask needs to invoke rdiff-backup.
It would be nice if this could just be some call `rdiff_backup.backup(ssh_client, local_path, key_value_options_mirroring_cli_interface, progress_callback)`.

My questions:

- is there already a way to achieve this functionality?
- is the module itself documented anywhere?

**Comment by ericzolf** [comment]
Well, the rdiff-backup script is super simplistic, so replacing it with your own code should be very simple. You just need to call rdiff_backup.Main.run_main_and_exit with the usual command line parameters, but it's not a stable interface.
