### ISSUE TITLE
[BUG] Errors running 2.1.1a0-64 on a Windows 7 system

### ISSUE THREAD

**Issue by dgasaway** [rdiff-backup/rdiff-backup#715]
## Bug summary

I tried to run the exe from rdiff-backup-2.1.1a0.win64exe.zip on a Windows 7 system, resulting in errors.

## Version, Python, Operating System

Cannot provide output of `rdiff-backup info`.  Windows version is Windows 7 with all patches.  Though I don't think it matters, this system does have Python 3.8.10 installed (official distribution from python.org).

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
D:\dev\backup>C:\Users\pdkg\Downloads\rdiff-backup-2.1.1a0-64\rdiff-backup.exe
```

## What happened and what did you expect?

First, I get a GUI dialog saying
```
The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer.  Try reinstalling the program to fix this problem.
```
Then on the CLI, I get
```
Error loading Python DLL 'C:\Users\pdkg\AppData\Local\Temp\_MEI395202\python39.dll
LoadLibrary: The specified module could not be found.
```

## More information

Given that rdiff-backup now requires a minimum of Python 3.9, and that Python support for Windows 7 only extends to 3.8.10, it may be that rdiff-backup is no longer operable for Windows 7.  If that's the case, Windows-README.adoc could use a statement to that effect. :)  Or at least, to say which Python version is bundled with the Windows builds, and that rdiff-backup only works on versions of Windows supported by said bundled Python.

I'm hoping the issue is something else, as #620 is causing problems for using the stable 2.0.5 version.

Just as background: My motivation was to move from the cygwin package to the native build, as the cygwin package hasn't moved up  from 2.0.0, and it would be better if my backup solution didn't have a cygwin dependency anyway.  Still, cygwin does have Python 3.9 , so they may get the newer versions eventually.  It's really unfortunate this system is stuck on Win7 for now.

**Comment by ericzolf** [comment]
Yes,  I'm sorry but I need 3.10 due to improvements to handling of bytes paths under Windows. Thanks for the analysis, I'll add this to the release notes.

**Comment by dgasaway** [comment]
I understand completely.  Thanks.
