### ISSUE TITLE
[ENH]  rdiff-backup is not friendly at all when called with --help

### ISSUE THREAD

**Issue by elMor3no** [rdiff-backup/rdiff-backup#749]
Hello,

I am helping to package rdiff-backup for Debian. Reviewing the reported bugs [1] I found this request from a user.

> Package: rdiff-backup
> Version: 1.2.8-6
> Severity: wishlist
> Tags: upstream
> 
> Hi there.
> 
> I have just started using rdiff-backup to, hummm, backup some of my files
> and some of the options are not exactly mnemonic. Then, by pure muscule
> memory, I always type "rdiff-backup --help" and I am greeted with the less
> than helpful:
> 
> ,----[ rdiff-backup --help ]
> | Fatal Error: Bad commandline options: option --help not recognized
> | See the rdiff-backup manual page for more information.
> `----
> 
> This is just a "papercut-like" bug that is easy to fix. I see that upstream
> already has a new development version of rdiff-backup that may, perhaps,
> have this "feature".
> 
> Is there the possibility of either packaging a newer version or of putting a
> patch in the version that is currently in sid?
> 
> 
> Thanks,
> 
> -- System Information:
> Debian Release: wheezy/sid
>   APT prefers unstable
>   APT policy: (500, 'unstable'), (300, 'experimental')
> Architecture: i386 (i686)
> 
> Kernel: Linux 2.6.38-1-686-bigmem (SMP w/2 CPU cores)
> Locale: LANG=en_US.utf-8, LC_CTYPE=pt_BR.utf-8 (charmap=UTF-8)
> Shell: /bin/sh linked to /bin/dash
> 
> Versions of packages rdiff-backup depends on:
> ii  libc6                         2.11.2-11  Embedded GNU C Library: Shared lib
> ii  librsync1                     0.9.7-7    rsync remote-delta algorithm libra
> ii  python                        2.6.6-11   interactive high-level object-orie
> ii  python-support                1.0.12     automated rebuilding support for P
> 
> Versions of packages rdiff-backup recommends:
> pn  python-pylibacl               <none>     (no description available)
> pn  python-pyxattr                <none>     (no description available)
> 
> rdiff-backup suggests no packages.
> 
> -- no debconf information

As the request implies changes in the operation of the project, I decided to report the request here.

You can find more details in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=618964

[1] https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=rdiff-backup

**Comment by ericzolf** [comment]
Short answer: no backport.
Longer answer: too many changes to back-port.
Even longer: a different library is being used to parse the command line arguments, so no chance. Beta has been released, wait for new version until end of the year.
