### ISSUE TITLE
Introduce pyproject.toml and keep else setuptools as build toolset

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#757]
Based on:
1. the discussion we started in PR #743
2. the rather ugly hack I needed to build properly Python wheels (see #754)
I wanted to have a proper discussion and inputs on the future (post 2.2) direction to take for building and packaging
@ikus060 @ottok @frankcrawford I'd appreciate your opinion as experienced developer and packagers.

**Comment by ericzolf** [comment]
Here my current thoughts, but let me first clarify that this is a post-2.2 discussion, nothing short term:

1. setup.py is rather ugly to read and maintain, but we need the plugins I've written to template files, create manpage(s) from asciidoctor or the hack written to copy the DLL under Windows. I'm rather fed up with the lack of plugin documentation of setuptools.
2. setup.cfg/pyproject.toml are more declarative approaches but the plugins/hacks would still need to remain in setup.py
    * pro: more declarative description in a configuration file, less code in setup.py
    * contra: the full truth would be split between setup.py and pyproject.toml/setup.cfg with potentially two files to manipulate to change things
    * NOTE: I assume that _if we go this path_ we go directly with pyproject.toml as its format is standardized by [PEP517](https://peps.python.org/pep-0517/)/[PEP518](https://peps.python.org/pep-0518/)
3. there don't seem to be any true alternative to `setuptools`, some observations I make:
    * many people use a Makefile to compensate shortcomings of setuptools and avoid writing a plugin, IMHO even uglier than my current approach
    * setuptools is still the default stated by PEP517
    * neither https://packaging.python.org/en/latest/guides/tool-recommendations/ nor https://packaging.python.org/en/latest/key_projects/ suggest any alternative to setuptools
    * I checked [PDM](https://pdm.fming.dev/latest/) and I'm not impressed, their plugin system offers even less help than setuptools to write your own
4. Flit is for very simple needs (no C extension), poetry focuses on dependencies
5. enscons/scons seems to be more like a build tool but probably requires major changes and isn't as well known as setuptools. Major caveat: the man-page has 200 pages as PDF, and 300 their user guide. Then better use a Makefile!
6. any change needs to work for our dear packagers _and_ for PyInstaller

Actually my only pain point with setuptools is when I need to extend its functionality, by lack of plug-in documentation, i.e. rather the build aspect of the whole show, and I don't see anything really helping me in this regard among the options I checked.

Currently my thinking is that I can add a minimal pyproject.toml to be PEP517/518 compliant, but keep more or less the current setup.py as it works currently, even if it's ugly. I might only replace my (very) ugly Windows wheel hack with a proper plug-in.

**Comment by ericzolf** [comment]
Aha, https://peps.python.org/pep-0621/ is also relevant, and implemented by [setuptools](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html). [trampolim](https://pypi.org/project/trampolim/) could have been an alternative but it seems stuck since more than one year.

**Comment by ikus060** [comment]
The way to go is `pyproject.toml` event if we need to keep some logic to `setup.py` It should slowly be migrated away as build tool evolve to support `pyproject.toml`.

> but the plugins/hacks would still need to remain in setup.py 

What are the "hack" you are referring too ? Because most of the weird logic is related to py2exe that is clearly a deprecated way to handle. Pyinstaller should be used and the way pyinstaller manage the binary creation is using a ".spec" file that will handle the binary specific logic. So Dll copy etc are handle by pyinstaller.

**Comment by ericzolf** [comment]
There are two plugins and 1.5 hacks (so to say):
* two plugins build_exec (mainly to call asciidoctor and generate the new man page) and build_templates to template the spec files and the old man page
* the hack is mainly the copy of the DLL, but everything outside of the `setuptools.setup(...)` is actually something you can't map into a setup.cfg/pyproject.toml IMHO.

The copy of the DLL and all the rest is needed for the creation of wheels, and has basically nothing to do neither with py2exe nor with PyInstaller, so I can't follow your statement.

**Comment by frankcrawford** [comment]
Yeah, I can't say a lot about how much work it is to covert to it, but from the Fedora packaging side, they are moving to `pyproject.toml`for all the future builds.
It does look to be a bit different structure, and the build macros for Fedora need to be updated, but it should be pretty standard.
However, the change is itself a bit of work, so should be planned between major updates.

**Comment by ikus060** [comment]
> The copy of the DLL and all the rest is needed for the creation of wheels, and has basically nothing to do neither with py2exe nor with PyInstaller, so I can't follow your statement.

I was really sure the dll copy was to create the binary. My bad.

**Comment by ikus060** [comment]
Maybe we should go back to: What is the problem you are trying to solve ?

If it's only the dependencies management. Then `pyproject.toml` is the way to go. And let keep our special `setup.py` around where it's needed.

**Comment by ericzolf** [comment]
I can live with this, I just wanted to make sure that there isn't a better alternative to setuptools.

**Comment by ikus060** [comment]
Sadly, `setuptools` seams to be the only thing available in python world and it's by far incomplete.

That said, if you ever work with Maven & Java. `setuptools` is really awesome. :D

**Comment by ericzolf** [comment]
OK, I take this as a decision and add this issue to milestone 2.4.0
