### ISSUE TITLE
[ENH] Pausing mid-backup.

### ISSUE THREAD

**Issue by technodragon253** [rdiff-backup/rdiff-backup#781]
## Is your feature request related to a problem? Please describe.

My backups take at least a day, which I'm fine with, except that if I need to interrupt the backup, I'll have to start over.

## Describe the solution you'd like

I would like some way to pause a backup. E.g. save the backup's progress when interrupted to a file so the next time a backup is run it'll pickup where it left off.

## Describe alternatives you've considered

I've thought of making a wrapper program in python to segment the backup into different "chunks" so less would be lost if an interruption was necessary. But at that point I may as well make my own backup script.

**Comment by technodragon253** [comment]
Whoops, sorry.

**Comment by ericzolf** [comment]
No issue, can happen.
