### ISSUE TITLE
[BUG] Duplicate ActionRemoveTest classes

### ISSUE THREAD

**Issue by pcanning** [rdiff-backup/rdiff-backup#785]
## Bug summary

I just noticed that both `testing/action_remove_test.py` and `testing/action_verify_test.py` contain a class named `ActionRemoveTest`.  I'm guessing this is a copy/paste error and that the class in  `testing/action_verify_test.py` should be named `ActionVerifyTest`.

My apologies if I'm wrong and confused.

**Comment by ericzolf** [comment]
Ah, yes, well spotted. Shame on me, it wasn't the only cut&paste error, some of the comments didn't make a lot of sense. Fixed in my current (anyway test related) branch. It'll close the issue once merged.
