### ISSUE TITLE
[BUG] using conn.os.name has never worked

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#788]
## Bug summary

The value returned by `conn.os.name` is always `os` (insted of `nt` & co), because it is the name of the `EmulateCallable` created by `conn.os`. There are actually two underlying issues:

1. `os.name` isn't a callable but a variable hence it returns in all cases the `EmulateCallable` object instead of the return value of the callable
2. Further more, `EmulateCallable` has an attribute `name` which would also overlap a method called `name()`

## Version, Python, Operating System

n/a - always been there

## rdiff-backup call

```
$ grep -r conn.os.name src
src/rdiff_backup/rpath.py:            if self.conn.os.name != 'nt' or not self.isdir():
src/rdiffbackup/locations/directory.py:        if (self.base_dir.conn.os.name == 'nt'
```

## What happened and what did you expect?

I noticed because it makes the remote call to compare fail if a symlink is involved in the comparison test.
I expect that the compare tests work under Windows (without need to skip, which is the workaround in my current branch).

## More information

I still need to look at the details but I think I'd like a generic `get_sys_info` method on all locations which could provide more information about remote locations than just the os name. I still need to check how to make it reachable in rpath.py.

It's a bigger change so I don't want to pack it in my current Windows tests branch.

**Comment by ericzolf** [comment]
I realized that I could do a simpler change replacing `os.name` with `platform.platform()`, which is a method. It won't work against a 2.0 server, due to security filtering, but it has never worked, so it won't really hurt.

**Comment by ikus060** [comment]
@ericzolf Could you explain how this bug is impacting the execution of a particular backup ? 

Is this bug affect only source linux, destination windows ? or the other way around ?

**Comment by ericzolf** [comment]
The source is relevant, it must be Windows, remote _and_ contain simlinks, for the issue to appear. I guess that it's seldom enough that we didn't notice before. Why?

**Comment by ikus060** [comment]
Just to better understand the impact of this bug. 

Since symlinks are rare if not existent on Windows, no wonder it was unnoticed !

Thanks for you explanation.
