### ISSUE TITLE
how to restore in a incremental way.

### ISSUE THREAD

**Issue by denishant** [rdiff-backup/rdiff-backup#797]
How to restore from the backup in a incremental way.

Let's say,
I have stored some data at "/root/mongodb/data" location.
I had taken one backup of this file location using rdiff-backup command(let's say this backup-name is first backup).
After first backup i deleted few files and added some more files. And then i had taken the second backup(let's say this backup-name is second backup).

Backup happened in incremental way as required.
Command used to take backup:
rdiff-backup -v5 --print-statistics /root/mongodb/data /tmp/rdiff/backup/

Now, if i want to get all the data of first backup at "/root/mongodb/data" file location back (as i think all the changes done after taking first backup are invalid)
So, i will do a restore.

when i do a restore using "rdiff-backup  -v5 --print-statistics  -r '2022-11-28T07:29:13Z' --force /tmp/rdiff/backup /root/mongodb/data", it looks like that rdiff is copying/processing all the files to /root/mongodb/data" and is time consuming.

## Describe the solution you'd like

rdiff should automatically find  changed files between /root/mongodb/data and first backup present at /tmp/rdiff/backup
and then should do processing on those changed files only to restore it to previous state of first-backup.
means restore will happen in incremental way also.

## Describe alternatives you've considered

Also i cannot use things like
rdiff-backup restore --increment  /backup/rdiff-backup-data/increments/usr/local.{time}.dir /usr/local.old
as it we would be very hestic if we have lots of changed files and data size is in TB.

**Comment by ericzolf** [comment]
You could use `rdiff-backup --compare -v0 /root/mongodb/data /tmp/rdiff/backup/ | awk -F ': *' '{print "/root/mongodb/data/" $2} > /tmp/list.txt'` to get a list of changes (you can of course use other `--compare-*` actions). Then `rdiff-backup --include-filelist /tmp/list.txt --exclude \** -r now --force /tmp/rdiff/backup /root/mongodb/data`.

Let me know if it helps, but rdiff-backup is already doing delta recovery; this said, the compare function only compares metadata (size, date, etc) so it might be a lot faster for big files than the diff based approach of the restore function. If you'd use the `--compare-full` option, it would become more secure but also slower.

**Comment by ericzolf** [comment]
No reaction, closing.
