### ISSUE TITLE
rdiff-backup 2.2.0 cannot install in Python neither 3.10 nor 3.11 on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by JD-Veiga** [rdiff-backup/rdiff-backup#806]
Hi,

I am not able to install rdiff-backup 2.2.0 neither in Python 3.10 nor in Python 3.11 running on macOS 10.14 Mojave.

I got a similar error in both cases:

```
      building 'rdiff_backup._librsync' extension
      /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -I/opt/local/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/_librsyncmodule.c -o build/temp.macosx-10.14-x86_64-cpython-310/src/_librsyncmodule.o
      src/_librsyncmodule.c:25:10: fatal error: 'librsync.h' file not found
      #include <librsync.h>
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
```

and 

```
      building 'rdiff_backup._librsync' extension
      /usr/bin/clang -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -I/opt/local/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/_librsyncmodule.c -o build/temp.macosx-10.14-x86_64-cpython-311/src/_librsyncmodule.o
      src/_librsyncmodule.c:25:10: fatal error: 'librsync.h' file not found
      #include <librsync.h>
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
```

I am running:
* macOS 10.14.6 Mojave
* Python 3.10.9 and Python 3.11.1
* pip 22.3.1 (both Python versions)
* librsync 2.3.2

Thank you.

**Comment by ericzolf** [comment]
I think @ikus060 has been fighting with similar issues, else ask on the mailing list. Else we're still looking for a MacOS maintainer to be able to support it properly. Just saying...

**Comment by JD-Veiga** [comment]
Ok.

However, I have reasons to think that this is a bug in `rdiff-backup` setup. Other `pip` packages suffer from this --not finding some C header while compiling-- and they were patched later (specially, as I can see, since Python 3.11 was released.)

I think that something in `pip` installation process has been changed between the release of current version of `rdiff-backup` and the previous one, something that could have broken installation in some architectures --one of them, mine.

Recent examples of this "bugs" are `editdistance`, `gmpy2`, `kivy` (not resolved yet), and other packages that I cannot remember now.

I should mention that I cannot even install `rdiff-backup 2.0.4` (previous version) in Python 3.11. (I do not try to make a clean re-installation of rdiff-backup 2.0.4 in Python 3.10 so I really do not know if it also happens in this Python version.)

Sorry but I can provide further information about the causes of this behaviour.

Thank you.

**Comment by ikus060** [comment]
We should change the title to reflect the real problem. MacOS is not the issue. it's Python 3.11 and/or 3.10. Rdiff-backup cannot get installed on those. As mention, something changed within pip that cause issue with binding or include source that precent the "C" module to get compiled.

@ericzolf I think I've already open an issue for that didn't I ? Or I wrote in the mailing list. I can't remember.

**Comment by ericzolf** [comment]
It can't be only Python3.11, it's the default for Fedora 37, which is my development environment. In my venv, I'm also using pip 22.3, without issue. I'm rather suspecting a clang vs. gcc issue.

Here was the issue: https://github.com/rdiff-backup/rdiff-backup/issues/773 - it looks different to me.

Looking again at the error message: could it be simply that you don't have the development files for librsync? No clue under Mac0S, but under linux you need to install a package librsync-dev resp. -devel. librsync.h should then be somewhere under /usr/include (again, under Linux).

**Comment by ericzolf** [comment]
Oh, and rdiff-backup 2.0 does definitely not work under Python 3.11.

**Comment by ericzolf** [comment]
`env "CFLAGS=-I/usr/local/include -L/usr/local/lib" pip install rdiff-backup` is an alternative.

**Comment by JD-Veiga** [comment]
I have try @ericzolf approach running: 

`sudo -H pip install --upgrade --global-option=build_ext --global-option='-I/opt/local/include' rdiff-backup` 

and got a new different error:

```
      running install_data
      error: can't copy 'build/rdiff-backup.1': doesn't exist or not a regular file
```

Running a similar command in Python 3.11: 

`sudo -H pip-3.11 install --global-option=build_ext --global-option='-I/opt/local/include' rdiff-backup` 

gives the same error.

The only difference to @ericzolf environment is that I am using a system-wide installation (though I think that this is  irrelevant).

**Comment by ericzolf** [comment]
You only missed the need to install asciidoctor.

**Comment by JD-Veiga** [comment]
Once `asciidoctor` has been installed, It works me both in Python 3.10 and 3.11.

**Comment by ericzolf** [comment]
Cool 🎆 and now if you want to make this ticket perfect, you write down everything you've done in a new file docs/MacOS-README.adoc and create a Pull Request out of it... 🥂

**Comment by chenrui333** [comment]
On the homebrew side, I can still see the issues of upgrading the project to use python@3.11 or rdiff-backup 2.2.0, see the linked issues.

**Comment by ericzolf** [comment]
@chenrui333 you're mixing things, that's confusing:
1. rdiff-backup 2.0.5 won't work with Python 3.11
2. I patched 2.2.0 in PR #808 to fix the DLL issue. Did you use it?

**Comment by ericzolf** [comment]
PR #808 merged, so I also close this issue. Please open a new ticket if you still have an issue, this one is too mixed up.

**Comment by mhadam** [comment]
Just posting in case anyone runs into the same issue I had, I must have migrated to macOS from Intel -> arm64 and `/usr/local/bin/brew` was on the path and overriding `/opt/homebrew/bin/brew`.

The solution was to just delete `/usr/local/bin/brew` and sort out all the dependencies I was installing for a different arch.
