### ISSUE TITLE
>=rdiff-backup 2.2.0: please provide generated manpages in the release tarballs

### ISSUE THREAD

**Issue by voyageur** [rdiff-backup/rdiff-backup#807]
Newer releases do not include most manpages in tree and rely on asciidoctor to build them.

For releases, this means depending on a ruby stack to regenerate identical files.
As reference, here is the list of packages pulled in in a Gentoo server for the added dependency:
```
[ebuild  N     ] app-eselect/eselect-ruby-20191222 
[ebuild  N     ] dev-libs/libyaml-0.2.5  USE="-doc -static-libs -test" 
[ebuild  N     ] dev-lang/ruby-2.7.7  USE="berkdb ipv6 rdoc ssl -debug -doc -examples -gdbm -jemalloc -jit -rubytests -socks5 -static-libs -systemtap -tk -xemacs" 
[ebuild  N     ] virtual/ruby-ssl-11  RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/rubygems-3.1.6  USE="-server -test" RUBY_TARGETS="ruby27" 
[ebuild  N     ] virtual/rubygems-16  RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/rake-13.0.3-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/power_assert-1.1.7  USE="-doc -test" RUBY_TARGETS="ruby27" 
[ebuild  N     ] dev-ruby/did_you_mean-1.4.0  USE="-test" RUBY_TARGETS="ruby27" 
[ebuild  N     ] dev-ruby/net-telnet-0.2.0-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30) (-ruby31)" 
[ebuild  N     ] dev-ruby/minitest-5.14.4  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/test-unit-3.3.9  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/json-2.5.1-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/kpeg-1.1.0-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/racc-1.6.0  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30) (-ruby31)" 
[ebuild  N     ] dev-ruby/rdoc-6.3.2  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/bundler-2.1.4  USE="doc -test" RUBY_TARGETS="ruby27" 
[ebuild  N     ] dev-ruby/webrick-1.7.0  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/xmlrpc-0.3.2-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30) (-ruby31)" 
[ebuild  N     ] dev-ruby/asciidoctor-2.0.16  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
```

As a workaround, I have patched setup.py to skip these parts and manually install manpages generated on another system.
So  it would be easier if release tarballs included these files.

**Comment by ericzolf** [comment]
Wouldn't it be forfeiting the purpose of _source_ tarball? The source of the manpage _is_ the asciidoc file.

**Comment by Schamschula** [comment]
Yes, but for those of us packaging `rdiff-backup` this causes a minor headache. I just updated the MacPorts Portfile to version 2.2.0, and this adds a rather significant dependency (ruby31).

P.S. `setup.py` insists on looking for `rsync.dll` under macOS. I just commented out the entire block.

**Comment by ericzolf** [comment]
> P.S. `setup.py` insists on looking for `rsync.dll` under macOS. I just commented out the entire block.

Do you define LIBRSYNC_DIR resp. '--librsync-dir'?

**Comment by Schamschula** [comment]
Yes:
`build.env           "LIBRSYNC_DIR=${prefix}"`

**Comment by voyageur** [comment]
> Wouldn't it be forfeiting the purpose of _source_ tarball? The source of the manpage _is_ the asciidoc file.
But for a given release, the manpage will always be the same?

I think the difference here is between a devel tarball and a release one. In a release source tarball, it helps to include anything that is constant in that release and brings no value to regenerate:
* on autotools builds, providing generated configure scripts so users do not have to run autoconf
* providing Changelog files so users do not need a full git tree checkout to recreate them
* or here man pages, where the regenerated version will always be identical

On development tarballs or git main checkouts, this is different, you can expect to need extra tools and dev environment, as these example files may change and need to be recreated

**Comment by ericzolf** [comment]
Good argumentation, let me think about this, and definitely need to fix the DLL issue.

**Comment by chenrui333** [comment]
> P.S. `setup.py` insists on looking for `rsync.dll` under macOS. I just commented out the entire block.

yeah, I had the similar issue, and that is what I did as well.

**Comment by ericzolf** [comment]
I really thought Windows was the only system stupid enough to not find its libraries (SCNR). Seriously, that's the easy part to fix.

**Comment by ericzolf** [comment]
Could you all please check that #808 solves your two problems? And @frankcrawford can you please check that it doesn't break your packaging effort?

**Comment by frankcrawford** [comment]
@ericzolf I'll give it a go over the next few days.

**Comment by frankcrawford** [comment]
> @ericzolf I'll give it a go over the next few days.

Eric, I tried it and it builds fine.  I'll probably should update the spec file to no longer have a BuildRequire for rubygem-asciidoctor, but that can come later.

**Comment by voyageur** [comment]
Thanks for the speedy fix! Sorry I could not try beforehand (end of year is busy time), but I can confirm 2.2.1 with released manpages worked here to avoid asciidoctor dependency. Bump in Gentoo in progress

**Comment by ericzolf** [comment]
I was the opinion that I borked release 2.2.1 in this aspect, see #813 closed (soon) by #814  and v2.2.2 (sorry for the noise). Do you create the sdist yourself from Git, or download it from GitHub, or some other method?

**Comment by frankcrawford** [comment]
In my case I have found what it does is a bit more complicated than I thought.  It does pull the sdist version from GitHub, but then pretty much runs all steps of the pre-build and build anyway.
So the only difference in my case is that for the manpages, if asciidoctor is not found then it just ignores the error on building.  However, it does check if the files exist after, and hence works anyway.

**Comment by voyageur** [comment]
Oh I see, I had bumped 2.2.1 fetching the manpages from release assets (so working around the issue).
2.2.2 source tarball looks good with them included in dist/ without any other steps and installs properly with asciidoctor
