### ISSUE TITLE
[BUG] "[Errno 5] Input/output error" when backing up from NTFS to ext4

### ISSUE THREAD

**Issue by Esperulo** [rdiff-backup/rdiff-backup#809]
## Bug summary

When backing up from an NTFS (Windows 10) partition to an ext4 partition, I get "[Errno 5] Input/output error" when backing up some specific directories.

## Version, Python, Operating System

Debian 11.

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```
Using rdiff-backup version 2.0.5
with cpython /usr/bin/python3 version 3.9.2
on Linux-5.10.0-20-amd64-x86_64-with-glibc2.31, fs encoding utf-8
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
/usr/bin/rdiff-backup  --exclude /vers-sauvegarde/pagefile.sys --exclude /vers-sauvegarde/hiberfil.sys --exclude /vers-sauvegarde/swapfile.sys --exclude /vers-sauvegarde/System\ Volume\ Information --exclude /vers-sauvegarde/\$Recycle.Bin /vers-sauvegarde /sauvegarde/Windows10
```

## What happened and what did you expect?

With some directories, I get an error similar to this one:

```
2022-12-27 20:40:15.399390 -0500  <CLIENT-8364>  ListError: '(b'Program Files', b'WindowsApps', b'9426MICRO-STARINTERNATION.MSICenter_1.0.33.0_x64__kzh8wxbdkxb8p', b'AppxBlockMap.xml')' [Errno 5] Input/output error: b'/vers-sauvegarde/Program Files/WindowsApps/9426MICRO-STARINTERNATION.MSICenter_1.0.33.0_x64__kzh8wxbdkxb8p/AppxBlockMap.xml'
```

## More information

The NTFS partition is mounted at /vers-sauvegarde, and the ext4 partition is mounted at /sauvegarde. Only some directories are affected. I've thoroughly checked the drives and file systems for errors.

Complete log of all errors:

[rdiff-backup.zip](https://github.com/rdiff-backup/rdiff-backup/files/10311631/rdiff-backup.zip)

**Comment by ericzolf** [comment]
From the look of it, there isn't much I can do. You seem to be saving an NFS share spawned from a Windows machine, which doesn't look to me like the most stable approach.

Why don't you enable SSH on your Windows machine, install rdiff-backup on there, and use rdiff-backup's remote capabilities to backup your Windows stuff?

Some more additional questions in the meantime:

*  Which kind of Windows machine are we talking about?
* Is it correct that the backup runs till the end overall? It's just that some files don't get saved? Could I get the last few messages in debug mode?
* if you run `journalctl -f` in a parallel window, does some relevant message appear in there? Same question for `dmesg --follow`?
* checking similarly errors on the Windows side would be helpful.

Input/Output errors are at file system level, nothing rdiff-backup can really influence. Your only chance is to see, and fix, the errors either on the Windows or Linux side. But, as said, my recommendation would be to rather use SSH and rdiff-backup directly.

**Comment by Esperulo** [comment]
I'm using Grub to boot either Linux or Windows. Both are on local drives, and I simply mount the Windows partition at /vers-sauvegarde . Windows isn't running at all.

I attach what `journalctl -f` reports. rdiff-backup starts at "déc 28 09:40:26". `dmesg --follow` merely reports that I've mounted the partitions.

I've thoroughly checked the Windows file system using Windows's own tools and found no error.

[journalctl.txt.zip](https://github.com/rdiff-backup/rdiff-backup/files/10314769/journalctl.txt.zip)

I notice there's a message about "Could not load plugin /usr/lib/x86_64-linux-gnu/ntfs-3g/ntfs-plugin". I've tried reinstalling ntfs-3g and there's no directory /usr/lib/x86_64-linux-gnu/ntfs-3g . Perhaps it's a problem with Debian or ntfs-3g?

**Comment by ericzolf** [comment]
Actually NTFS-3G is a FUSE driver, which are known to be rather slow and more or less unreliable, especially when it comes to heavy duty work like a backup. There is a "native" kernel model ntfs3 but only since kernel 5.15 according to [ArchLinux](https://wiki.archlinux.org/title/NTFS) (often the best documentation). As you only have 5.10, this sounds to me like you're stuck unless you try the [kernel 5.18 from the bullseye-backports](https://packages.debian.org/search?suite=bullseye-backports&arch=any&searchon=names&keywords=kernel).
Alternatively you could try to post your issue on the mailing list and see if someone else has solved your issue somehow.

**Comment by Esperulo** [comment]
I was wondering why you were talking about NFS. ;-)

It's clear this isn't a problem with rdiff-backup, so you can close it. I'll try bullseye-backports; thanks for the suggestion.

**Comment by ericzolf** [comment]
Then closing. Hope this helps.
