### ISSUE TITLE
[BUG] Release 2.2.1 Missing Manpages

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#813]
## Bug summary

In Release 2.2.1 the manpages are not being pre-built and are not in the dist directory.  The only file there is rdiff-backup-old.1, which is generated from a separate template.

## Version, Python, Operating System

Release 2.2.1 rdiff-backup-2.2.1.tar.gz, on Linux (Fedora 37)

## What happened and what did you expect?

`rpmbuild -ba rdiff-backup.spec` with previously working RPM spec file failed to build.  It was unable to find `rdiff-backup.1`

## More information

Can supply the build logs if you require, but issue is more at the release preparation stage.

**Comment by frankcrawford** [comment]
If `asciidoctor` is available it will still build the manpages, as it runs the pre_build_exec step during setup.

**Comment by ericzolf** [comment]
Ah, stupid me: asciidoctor has become a prerequisite of sdist in _my_ pipeline.
