### ISSUE TITLE
[BUG] remote-schema doesn't allow {} use in shell

### ISSUE THREAD

**Issue by tecordes** [rdiff-backup/rdiff-backup#818]
## Bug summary

My remote-schema has had { } curly-braces in it forever.  2.2.0 won't run with my remote-schema it seems.  Gives schema error.  tcsh which I use (not sure about bash) allows wrapping multiple commands in {} kind of like a subshell, but different from ().

I fixed the bug by changing in SetConnections.py in def _fill_schema the first findall to:
        if ((re.findall(b"(?<!{){[^{}]*}", cmd_schema)

And doubling-up my shell {} into {{}} in my remote-schema.  This "just works" because python string format allows escaping the {} by doubling up as such.  The only thing required to make it work is the regex change above to exclude checking the double-upped {}'s.

## Version, Python, Operating System

---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.0
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.10.9
system:
  fs_encoding: utf-8
  platform: Linux-6.0.15-200.fc36.x86_64-x86_64-with-glibc2.35
...

## rdiff-backup call

The remote-schema with the {} is (after I doubled them up and now working):

--remote-schema 'ssh -x -C -q -o StrictHostKeyChecking=no -o CheckHostIP=no -c aes256-gcm@openssh.com {h} '\''(/usr/local/sbin/netbak-smbmount '\''//192.168.100.2/Users'\'' '\''/mnt/netbak'\'' '\''netbak'\'' '\''0'\'' && ( {{ ok=1;  (( `find /mnt/netbak/Joe/Favorites | head -2 | wc -l` == 2 )) && ( umask 077; chmod --quiet 600 /tmp/rdb.log; rnice=/usr/bin/nice; [ -e /bin/nice ] && rnice=/bin/nice; $rnice -n19 /usr/bin/ionice -c2 -n7 rdiff-backup  server 2>>/tmp/rdb.log ) && ok=0; }} ; /usr/local/sbin/netbak-smbumount /mnt/netbak; rm -f /home/netbak/.netbak-smbmount.cred; exit $ok )) | /usr/bin/pv -L 200000 -rbWf -i2592000'\'

## What happened and what did you expect?

It immediately fails when checking the command line options with a bad remote-schema error.  Should work ok with my old remote-schema.

**Comment by ericzolf** [comment]
Fair and simple enough, you are of course welcome to provide a Pull Request (with a documentation update to explain the double curly brackets, where the double % is already explained). A test case would also be nice.

**Comment by tecordes** [comment]
Thanks for the quick help.  I am attempting a patch and PR as you requested.  It is my first time trying to patch on github, and trying to PR on github, so forgive any mistakes I may make.  I read the rdiff PR docs and did my best.  Let me know my mistakes so I can do better PRs for my other 2 bugs.  I especially am a bit confused where I place keywords like FIX.

I looked at the test case code to see if I could make a test case, but I couldn't find anything that looked similar for remote-schema for me to add to or use as a basis.  The test code is a bit out of my depth without some direction as to the best approach.  I can easily come up with a test case that doesn't rely on outside files or anything: you can just put in the remote-schema a useless:
true /{usr,var};
and it should error out without my fix, but produce no error with my fix.
