### ISSUE TITLE
Unclear how to handle "this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'"

### ISSUE THREAD

**Issue by fbb-git** [rdiff-backup/rdiff-backup#842]
Using 

rdiff-backup --api-version 201 --verbosity 5   --tempdir /tmp/rdiff-tmp \
    backup \
    --include-symbolic-links  --exclude-device-files  --exclude-sockets \
    --exclude-globbing-filelist  /root/etc/exclude-from.host  
    /src-dir/path/    /backup/dest/path/

I keep receiving the warning that the command line interface is deprecated. rdiff-backup's version is 2.2.2. The man-page doesn't mention the warning, and the FAQ at https://rdiff-backup.net/ states:

Call rdiff-backup with the higher API and the message will disappear.
Calling for example rdiff-backup --api-version 201 backup loc1 server2::loc2 

The backup is performed OK, but the warning doesn't disappear. What am I doing wrong?

**Comment by ericzolf** [comment]
Why didn't you fill the template provided for issues? Provide the missing information.

I used the exact same command you have and didn't get the warning. Something on your end. The FAQ is for remote execution which isn't your use case.

**Comment by fbb-git** [comment]
Dear Eric L., you wrote:
> Why didn't you fill the template provided for issues? Provide the missing
> information. 

Probably because the man-page doesn't even contain the word 'template'....

> I used the exact same command you have and didn't get the warning. Something
> on your end. The FAQ is for remote execution which isn't your use case. 

Wrt 'my end': you're probably right: I performed several checks from scratch
yesterday, calling 

rdiff-backup --verbosity 5 --tempdir /root/rdiff-tmp \
    --api-version 201 \
    backup \
    --include-symbolic-links \
    --exclude-device-files \
    --exclude-sockets \
    --exclude-globbing-filelist /root/etc/exclude-from \
    remoteFQDN::/ /backup-destination-directory

and all of them successfully completed. Since I haven't yet completed all
intended checks, I haven't already posted my findings, but so far things look
good.

Thanks for your reply :-)

-- 
    Frank B. Brokken
    (+31) 6 5353 2509
    PGP Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by ericzolf** [comment]
> Probably because the man-page doesn't even contain the word 'template'....

When you press the 'New issue' button on GitHub, you should have been confronted with a template choice. If this wasn't the case, then I'd like to know how you exactly created the issue.

**Comment by fbb-git** [comment]
Dear Eric L., you wrote:
> > Probably because the man-page doesn't even contain the word 'template'....
> 
> When you press the 'New issue' button on GitHub, you should have been
confronted with a template choice. If this wasn't the case, then I'd like to
know how you exactly created the issue. 

When opening a new issue I get a page offering options to open a bug report or
a feature request, or to open a blank issue. And indeed: there's also an entry
'View organization templates, but the page that opens when selecting that
option provides no useful information (i.e., it doesn't show info suggesting
anything related to the reported error rdiff-backup). And since the man-page
doesn't even contain the word 'template' it's unclear what these templates are
and how they should be used,

Don't get me wrong: I really appreaciate rdiff-backup, and I've been using it
for many, many years now. But the recently encountered error message was
really puzzling. Anyway, for me rdiff-backup runs fine again, calling it this
way:

rdiff-backup \
     --verbosity 5 \
     --tempdir /root/rdiff-tmp \
     --api-version 201 \
     backup \
     --include-symbolic-links \
     --exclude-device-files \
     --exclude-sockets \
     --exclude-globbing-filelist /root/etc/exclude-from.hostname \
     host-fqdn::/ /backupDest/hostname-rdiff

Cheers,

-- 
    Frank B. Brokken
    (+31) 6 5353 2509
    PGP Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by suovantie** [comment]
I get the same error message. I might be stupid, but still I would appreciate a manual for us, who have only MSc in computer science.

**Comment by fbb-git** [comment]
Dear suovantie, you wrote:
> I get the same error message. I might be stupid, but still I would
appreciate a manual for us, who have only MSc in computer science.

Thx for your e-mail but rdiff-backup has looong ago moved to gitlab....

-- 
    Frank B. Brokken
    (+31) 6 5353 2509
    PGP Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by ericzolf** [comment]
@suovantie your sarcastic remark, especially on a closed ticket, isn't helpful. If you have concrete needs, make them clear, or even improve suggest yourself improvements. After all, this is an open source program, we just do our best in our free time.

@fbb-git why would you say this? rdiff-backup is further on GitHub and _not_ on GitLab!

Beware both that 2.2.2 is an outdated version, 2.2.6 is the current version.

**Comment by suovantie** [comment]
Thank you for your answer.
I found this reporting system by Google, while searching for advice.
Google did not know it is historic, and did not give any other address
I did not find any forum, where to discuss about about some aspects of rdiff-backup.

I have replased my selfmade backup program with this about 4 months ago and so far I'm very pleased.

Still I find it very hard to set some parameters for optimum.
So I had to run many iterations, before I found a mixture, which works.
The manual, which I found, is too technical for me.

I know very well that writing manuals is hard work.

Please do not take this negative. Continue good work !

Pasi Mustalahti, MSc
________________________________________

**Comment by fbb-git** [comment]
Dear suovantie, you wrote:

> Still I find it very hard to set some parameters for optimum.
> So I had to run many iterations, before I found a mixture, which works.
> The manual, which I found, is too technical for me.
> 
> I know very well that writing manuals is hard work.
> 
> Please do not take this negative. Continue good work !

On second thought: there's probably some misunderstanding: I'm not an
rdiff-backup developer or maintainer, so I guess I accidentally received your
e-mail. Maybe you can open an issue at github's rdiff-backup site.

All the best,

-- 
    Frank B. Brokken
    (+31) 6 5353 2509
    PGP Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
