### ISSUE TITLE
Could GitHub Discussions be enabled?

### ISSUE THREAD

**Issue by YDX-2147483647** [rdiff-backup/rdiff-backup#843]
[GitHub Discussions](https://docs.github.com/en/discussions/quickstart) are …

- for **conversations** that (unlike [FAQ on website](https://rdiff-backup.net/FAQ.html)) …
- need to be transparent and accessible (better than [maling list](https://lists.nongnu.org/mailman/listinfo/rdiff-backup-users)) …
- but do not need to be tracked on a project board and are **not related to code** (unlike [GitHub Issues](https://github.com/rdiff-backup/rdiff-backup/issues/)).

So could it be enabled?

([How to](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository): repo settings → features, select discussions.)

**Comment by ericzolf** [comment]
No. Don't want to be too dependent on GitHub and mailing lists are fantastic.

**Comment by YDX-2147483647** [comment]
Thanks for explanation, I understand.
