### ISSUE TITLE
[ENH] Improved handling of new / old command

### ISSUE THREAD

**Issue by keesj** [rdiff-backup/rdiff-backup#844]
## Is your feature request related to a problem? Please describe.

I used to do 
`rdiff-backup user@host::/data /data` but the program is complaining about using a deprecated API it appears I need to 
now run `rdiff-backup backup user@host::/data /data` but then the program complains with

**WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.**

Reading the documentation I should be able to run `rdiff-backup --new backup user@host::/data /data` to "enforce" the new syntax but the result remains 

**WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.**

## Describe the solution you'd like

I would like better error handling or help and if I "enforce" the new syntax it should not accept the old one. It also appears that `rdiff-backup --new --help` produced the same output as `rdiff-backup --help` I am confused.

## Describe alternatives you've considered

using rsync and then running rdiff-backup as it appears that the remote syntax is causing the warning

## Additional context

Overall.. and certainly for a backup program it would like the program change less over time :P

**Comment by keesj** [comment]
rdiff-backup 2.2.2

**Comment by ericzolf** [comment]
https://rdiff-backup.net/FAQ.html#why_does_rdiff_backup_complain_about_command_line_interface_being_deprecated_even_though_im_using_the_new_syntax

> Overall.. and certainly for a backup program it would like the program change less over time :P

Less than a new version each two year, after a break of 9 to 10 years? There is plenty of technical debt to get rid of...

**Comment by keesj** [comment]
Hi,

Thank you for the link to the documentation. I would still suggest a few enhancements either to the documentation or the code
* --new should not accepts old (this defeats the purpose) 
* Improve version handling by selecting the highest compatible version between client and server (in my case I am running the same version on client and server
* The FAQ still leaves me a bit in the dark. What are those version and why do I care. it would be nice to provide a working example but I would prefer on e of the solutions above.

**Comment by ericzolf** [comment]
Fair enough but I won't be investing more time on this for version 2.2, the old CLI model will disappear in the next version anyway.

Regarding the handling of API versions, check the man page, it explains a bit how it works, but again fair enough, I'll try to improve the explanations and make it more transparent to users.
