### ISSUE TITLE
Decide if it makes any sense to backup proc

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#85]
<a href="https://github.com/ericzolf"><img src="https://avatars3.githubusercontent.com/u/3105685?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericzolf](https://github.com/ericzolf)**
_Sunday Jul 21, 2019 at 08:25 GMT_
_Originally opened as https://github.com/ericzolf/rdiff-backup/issues/35_

----

proc is generated on the fly so it might not make sense to backup it. Some points to consider:

* SELinux keeps a normal user from accessing /proc, perhaps it works better with root?
* Would need at least to fail graciously?
* How to detect a proc filesystem (might be somewhere else than /proc)?
* Do we allow knowledgeable users to backup proc?
* Need to adapt finaltest to approach (3 tests are being skipped for now)

In the meantime, recommendation is to exclude `/proc` from backup.

**Comment by ericzolf** [comment]
<a href="https://github.com/ericzolf"><img src="https://avatars3.githubusercontent.com/u/3105685?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ericzolf](https://github.com/ericzolf)**
_Thursday Jul 25, 2019 at 17:50 GMT_

----

It's not a regression, rdiff-backup 1.2.8 (Fedora) has exactly the same kind of issue when trying to backup `/proc` as normal user or even as root (many SELinux errors).

So this won't be fixed as part of the migration to Python 3.

**Comment by ottok** [comment]
If something is blocked by SELinux, AppArmor or some other Linux security module, being root does not bypass it.

I can't think of any sensible use case shy somebody would like to backup /proc. I'd suggest that rdiff-backup would just skip or fail gracefully is somebody accidentally tries to backup /proc, /sys, /dev or /run.

**Comment by davekempe** [comment]
I don't think we should build in things like this - there are plenty of include and exclude options already for this sort of thing. /proc isn't relevant everywhere, and maybe some weird docker or LXC thing might mean you can or maybe want to backup something that looks like /proc and isn't.

**Comment by frankcrawford** [comment]
While I agree that it is better not to build such exclusions into rdiff-backup, any such exclusions should be based on filesystem type, not on the mountpoint.  /proc is type proc, /sys is type sysfs, /dev looks to be type devtmpfs, etc.

**Comment by ericzolf** [comment]
Actually, decision was taken: no special handling (while I agree that the filesystem type is tempting, someone will always find an exception where it might make sense, so let's leave it to the user to decide what to exclude or not).
