### ISSUE TITLE
provide one method or api so that the upper layer can know the backup progress

### ISSUE THREAD

**Issue by aisnote** [rdiff-backup/rdiff-backup#856]
## Is your feature request related to a problem? Please describe.

Currently myapp.exe will call rdiff-backup.exe, but did not know the progress on the backup

## Describe the solution you'd like
simple solution is: rdiff-backup.exe write the progress info to one log file 
myapp.exe can read the real time log from that file.

**Comment by ericzolf** [comment]
I'm not sure what you expect. rdiff-backup doesn't know of a progress in terms of percentage or time. And each processed file is already listed, starting with verbosity 5. And there is already a logfile with this information.

**Comment by aisnote** [comment]
1. like a big file copying, can we know the percentage?
2. where is the current log saved?

what I want is to show the progress when starting backup.

the call flow is: myapp.exe  launch rdiff-backup.exe as I posted on another issue. 
https://github.com/rdiff-backup/rdiff-backup/issues/855

**Comment by ericzolf** [comment]
> * like a big file copying, can we know the percentage?

No.

> * where is the current log saved?

https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/rdiff-backup.1.adoc#files

**Comment by aisnote** [comment]
Thanks. And I think **backup.log** is good enough for my case. 
One more thing is this log file will be rotation or not?
Currently as I checked, it has 20M+ size.

**Comment by ericzolf** [comment]
No rotation. It's up to you to maintain it.
