### ISSUE TITLE
More clarity on new syntax roadmap

### ISSUE THREAD

**Issue by bobOnGitHub** [rdiff-backup/rdiff-backup#863]
## Is your feature request related to a problem? Please describe.

Concerns about new cli command syntax

## Describe the solution you'd like

Document why the syntax is being changed and if/when the old syntax will be dropped.

## Additional context

I spent a considerable amount of time last year on a backup solution based on rdiff-backup. 
I do not want to spend precious time learning a new syntax and more worryingly re-working my scripts - I thought I had this job done for the forseeable future. Now I see notices "this command line interface is deprecated and will disappear" .

I would like to know when the "disappear" will happen.

**Comment by ericzolf** [comment]
2.4 but no time line behind (1 year?)

**Comment by bobOnGitHub** [comment]
thx for that @ericzolf . 

Given this is going to make work for anyone using rdiff-backup it'd be nice to know _why_ its happening.

**Comment by ericzolf** [comment]
It has been discussed on the mailing list, if you want to summarize and create a pull request, be my guest.

**Comment by bobOnGitHub** [comment]
So if I want to know why there are going to be breaking changes to the API of a 20yr old utility I have to trawl through a mailing list ??!.  MORE TIME on something I, and I imagine most users, do not need.

Those responsible can't be bothered summarising the reasons for the changes on the main site but are happy to go ahead and break scripts across the globe. Speaks volumes.

I suspect I'll be dumping or forking rdiff-backup at some point.

(No response reqd.)

**Comment by ericzolf** [comment]
Why fork when you could participate and do it better?
