### ISSUE TITLE
Cannot regress last successful increment [?] 

### ISSUE THREAD

**Issue by PorcelainMouse** [rdiff-backup/rdiff-backup#878]
## What is it about?

I'm having problems with my backups, suddenly.  I've been using rdiff-backup since 2017, my last increment has failed repeatedly four times.  Each time, I fsck and regress.  I've tested the media with a read/write test, no errors were detected and SMART shows nothing.  I suspect the errors are due to corruption of unknown origin, since rdiff-backup verify reports many failed checksums.

However, I cannot delete or regress the last backup, as it was successful.  The documentation says that the --force option can be used to regress the last successful backup, but this is wrong; rdiff-backup refuses to regress.

## Version, Python, Operating System

 rdiff-backup info
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.4
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.11.3
system:
  fs_encoding: utf-8
  platform: Linux-6.2.14-200.fc37.x86_64-x86_64-with-glibc2.36
...

```yaml
2.2.4
```

## rdiff-backup call

If you tried something already, how did you call rdiff-backup, with which parameters:

```
rdiff-backup --force regress /path-to-backup
```

And what was the result?

```
rdiff-backup -v 3 --force regress <backup dir>
NOTE: Given repository doesn't need to be regressed
```

**Comment by ericzolf** [comment]
Where die you see this in the documentation? At least in the change log,  it states that you need to use API 201, I.e. with `--api-version 201`. As you're using it locally, it shouldn't make any difference, beside unlocking the feature.

Out of curiosity, which file system are you using for the repository?

**Comment by PorcelainMouse** [comment]
> Where die you see this in the documentation? At least in the change log, it states that you need to use API 201, I.e. with `--api-version 201`. As you're using it locally, it shouldn't make any difference, beside unlocking the feature.

Here: https://rdiff-backup.net/rdiff-backup.1.html . The full description of `regress` is just a few lines and the bit about --force is right there.

The CLI help for regress doesn't say anything about --force or the API option. The CLI general help shows the API option, but I didn't know where to look for API changes.  The manpage says that option is for matching with the server, which makes sense and I didn't realize it might have other implications.

> Out of curiosity, which file system are you using for the repository?

ext4

Okay, thank you, the API option makes it work.

**Comment by ericzolf** [comment]
Ok.I'll fix the manpage.
