### ISSUE TITLE
[BUG] rdiffbackup module fail to load with captured stderr and stdout

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#885]
## Bug summary

When loading `rdiffbackup` module on Windows with a fake strerr and stdout (mainly to capture logs during testing with pytest) the module refused to load.

## Version, Python, Operating System

On Windows, all python version.

## rdiff-backup call

```
import rdiffbackup
```

## What happened and what did you expect?

```
    import rdiffbackup.run
.tox\py3-win\lib\site-packages\rdiffbackup\run.py:30: in <module>
    msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)
.tox\py3-win\lib\site-packages\_pytest\capture.py:220: in fileno
    raise UnsupportedOperation("redirected stdin is pseudofile, has no fileno()")
E   io.UnsupportedOperation: redirected stdin is pseudofile, has no fileno()
```

## More information

I'm proposing to move the call of `msvcrt.setmode` into `main` function to let the module load regardless.

**Comment by ericzolf** [comment]
From the error line, it's not the import which fails, it's the the 2nd setmode command.

And looking at the code, we'd actually want the import to fail under Windows, if the module wouldn't exist, so the code is broken. I'd suggest to go for something like:

```python
if os.name == "nt":
    import msvcrt


def main():

    if os.name == "nt":
        # make sure line endings are kept under Windows like under Linux
        msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)
        msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)

    sys.exit(main_run(sys.argv[1:]))
```

Do you improve your PR accordingly? Not sure a test is required though.

And I wouldn't call this a bug but an enhancement, but fair enough :smirk:

**Comment by ikus060** [comment]
@ericzolf Thanks for the comment. I update the pull request.
