### ISSUE TITLE
Is it possible to define the time to be used on rdiff-backup backup?

### ISSUE THREAD

**Issue by dxdemetriou** [rdiff-backup/rdiff-backup#890]
## What is it about?

I'm trying to convert the backups I have with git to rdiff-backup (the git is as an example, it can be any backups needs to be converted to rdiff-backup's method). According to the command I don't see an option to manually  define the time I had on git's snapshot's.

rdiff-backup backup [CREATION OPTIONS] [COMPRESSION OPTIONS] [SELECTION OPTIONS] [FILESYSTEM OPTIONS] [USER GROUP OPTIONS] [STATISTICS OPTIONS] sourcedir targetdir

Is there any way to set the date-time for each differential (in my case, the git's commit times)?

## Version, Python, Operating System

---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.2
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.11.2
system:
  fs_encoding: utf-8
  platform: Linux-6.1.0-9-amd64-x86_64-with-glibc2.36
...

**Comment by ericzolf** [comment]
Yes, there is: check the generic options i.e. `rdiff- backup --help` --current-time

**Comment by dxdemetriou** [comment]
> Yes, there is: check the generic options i.e. `rdiff- backup --help` --current-time

Thanks, I tried it yesterday that but I had an error because I added it after the backup. Now I added it before the backup and worked.

rdiff-backup --current-time $timestamp backup --exclude '**/.git' "$src" "$dest"
