### ISSUE TITLE
[BUG] Test failures

### ISSUE THREAD

**Issue by muesli4** [rdiff-backup/rdiff-backup#897]
## Bug summary

I was building the corresponding [archlinux package](https://aur.archlinux.org/packages/rdiff-backup).  I got the following and more test failures.
```
======================================================================
FAIL: testBasic (__main__.EATest.testBasic)
Test basic writing and reading of extended attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/makepkg/rdiff-backup/src/rdiff-backup-2.2.5/testing/eas_aclstest.py", line 79, in testBasic
    self.assertEqual(new_ea.attr_dict, self.sample_ea.attr_dict)
AssertionError: {} != {b'user.empty': b'', b'user.not_empty': b'[1417 chars]xb1'}
Diff is 2186 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: testIterate (__main__.EATest.testIterate)
Test writing several records and then reading them back
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/makepkg/rdiff-backup/src/rdiff-backup-2.2.5/testing/eas_aclstest.py", line 194, in testIterate
    self.assertEqual(sample_ea_reread, self.sample_ea)
AssertionError: <rdiff_backup.eas_acls.ExtendedAttributes object at 0x7fc2130abb50> != <rdiffbackup.meta.ea.ExtendedAttributes object at 0x7fc2141faed0>

----------------------------------------------------------------------
Ran 20 tests in 11.431s

FAILED (failures=2)
```
See bash functions `prepare` and `build` in [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rdiff-backup) on how to reproduce.

## Version, Python, Operating System

2.2.5-2 (see [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rdiff-backup)).  I manually downloaded version 2.2.5 to confirm it.

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /home/moritz/Downloads/rdiff-backup-2.2.5/test-install/usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.5
python:
  executable: /usr/bin/python
  name: cpython
  version: 3.11.3
system:
  fs_encoding: utf-8
  platform: Linux-6.4.1-arch1-1-x86_64-with-glibc2.37
...
```

**Comment by ericzolf** [comment]
As apocalyptech commented: on which filesystem do you do the tests? Does it support EAs and ACLs?

**Comment by muesli4** [comment]
> As apocalyptech commented: on which filesystem do you do the tests? Does it support EAs and ACLs?
```
[moritz@phi ~]$ touch xattr-test
[moritz@phi ~]$ setfattr -n user.test -v "hello" xattr-test 
[moritz@phi ~]$ getfattr xattr-test 
# file: xattr-test
user.test

[moritz@phi ~]$ getfattr xattr-test  -n user.test
# file: xattr-test
user.test="hello"
```

The entry in `/etc/fstab` is:
```
LABEL=home          /home                ext4    rw,relatime,data=ordered           0      2
```
Also:
```
[moritz@phi ~]$ tune2fs -l /dev/disk/by-label/home  | grep 'Default mount'
Default mount options:    user_xattr acl
```
Thus, I would assume both is supported on my filesystem.  Have you tried running those tests?  Is the behavior expected?  Do all pass on your machine?

**Comment by muesli4** [comment]
I tried the fix related to the timezone.  But that did not change anything.  There are still quite a lot of test failures.

**Comment by ericzolf** [comment]
That did not change anything or that did change something but there are still quite a lot of test failures?

To make it clear, the tests do work perfectly in our pipeline (Ubuntu) and on my Fedora, since years and many versions, and for many other people (among them apocalyptech, so the issue seems to be rather in your environment than in our tests (not that we can't fix something to make our tests more robust).

So, I'd look first on how you unpack the test files: they need to be unpacked as root or some things won't be properly extracted. I've seen that you use fakeroot but I don't know how fakeroot does "fake root", so I'd try once to extract as "real" root and see if this solves the issue.

**Comment by muesli4** [comment]
> That did not change anything or that did fix the one issue but there are still quite a lot of (other) test failures?
> 
> To make it clear, the tests do work perfectly in our pipeline (Ubuntu) and on my Fedora, since years and many versions, and for many other people (among them apocalyptech), so the issue seems to be rather in your environment than in our tests (not that we can't fix something to make our tests more robust).

That is good to know.  And just to be clear, I am **not** saying you are supposed to fix this.  I was just reporting this in case there really is an issue.
 
> So, I'd look first on how you unpack the test files: they need to be unpacked as root or some things won't be properly extracted.

Is this documented anywhere?

> I've seen that you use fakeroot but I don't know how fakeroot does "fake root", so I'd try once to extract as "real" root and see if this solves the issue.

Some of the issues are gone.  [test-log.txt](https://github.com/rdiff-backup/rdiff-backup/files/11961453/test-log.txt) contains the full test output.

**Comment by ericzolf** [comment]
> Is this documented anywhere?

Don't tell me you've searched very hard: https://rdiff-backup.net/DEVELOP.html#testing

**Comment by Puxap-3opre** [comment]
I have failed builds trying to install from Arch Linux AUR, when my build dir was set to tmpfs (in /etc/makepkg.conf):

```
BUILDDIR=/tmp/makepkg
```

I'm not sure, maybe it's a package maintainer concern, but just in case I'm reporting it here. It seems that the installation tries tests in build dir but tmpfs doesn't support extended attributes or something.

Because when I comment out "BUILDDIR=/tmp/makepkg", it builds OK (apart from the timezone bug).

**Comment by ericzolf** [comment]
Without more information, I'm closing the issue. Re-open if you se fit.
