### ISSUE TITLE
Backupninja spits individual file warnings 

### ISSUE THREAD

**Issue by re-vax** [rdiff-backup/rdiff-backup#906]
## Bug summary

I get sometimes a warning about a missing index from iterator cache

## Version, Python, Operating System

debian 11.7
rdiff-backup                   2.0.5-2 
python3                        3.9.2-3

btw:
Calling `rdiff-backup info` returns:
Fatal Error: Switches missing or wrong number of arguments
See the rdiff-backup manual page for more information.

## rdiff-backup call

It's called by backupninja, no details about the command line/options in the logs

## What happened and what did you expect?

The backup seems to be successfull: I get this kind of email:
```
success -- /etc/backup.d/10-system.rdiff
*warning* -- /etc/backup.d/50-xdata.rdiff
success -- /etc/backup.d/99-ending-actions.sh

== warnings from /etc/backup.d/50-xdata.rdiff ==

Info: Removing backups older than 60D days succeeded.
Warning: index (b'xdata', b'docker', b'data-root', b'fuse-overlayfs', b'1a9f2cef1e00f04e99c642606c8ca7c09817ace145165d7bdbde6d6af97ce57e', b'merged', b'usr', b'bin', b'docker-entrypoint.sh') missing from iterator cache
Warning: index (b'xdata', b'docker', b'data-root', b'fuse-overlayfs', b'3b093792bdb33f857a82999173702e5700228e80e831b3d2d512521a9b68e836', b'merged', b'usr', b'share', b'zoneinfo', b'America', b'Creston') missing from iterator cache
Info: Successfully finished backing up source
```

This is just a warning. It appends sometime, not each time. And not on the same files but always on files in the fust-overlayfs sub folders. 
As the last message says : "Successfully finished backing up source" , I'm not worry, but I like my backups to be clean.
I'd really like to anderstand what this warning refers to.

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.
I don't know how to add this options with backupninja :(

**Comment by ericzolf** [comment]
Doesn't sound like a bug to me and version 2.0.5 is anyway outdated. The message probably only mean a hick-up with the file system, or that the file disappeared while it was being backed-up. Shouldn't impact the overall backup. 

> I don't know how to add this options with backupninja :(

`options= -v9` perhaps?

Please close the ticket if you have no further questions.

**Comment by re-vax** [comment]
Hi, Thanks for answering me.

> Doesn't sound like a bug to me and version 2.0.5 is anyway outdated. 

This is the stable version on current debian (Yes I know, always old versions on debian) . Not sure it's a good idea to use backport or manual install tu upgrade to a more recent version on this production server as it's only a warning.

> The message probably only mean a hick-up with the file system, or that the file disappeared while it was being backed-up. Shouldn't impact the overall backup.

What do you mean by 'hick-up '? This message apprends only on files that belongs to container layers, the are not moving nor been deleted while backup is running. (docker-entrypoint.sh,  time zone data files etc...)


> `options= -v9` perhaps?

I changed the config file to add this option. I'll see the results on the next night.
I hope the warning will append and see something usefull in the log file...

**Comment by ericzolf** [comment]
Fair enough, just didn't want that you expect a bug fix for this version.

Hick-up means that fuse file systems aren't known as the most reliable and performant ones, and rdiff-backup can hit them quite hard.

If you wish, you can also ask on the mailing list, the community might have a better answer, and I didn't know about backupninja, so others might also want to learn about it.

**Comment by re-vax** [comment]
I try to anderstand what can the cause be. The path contains 'fuse-overlayfs' as it's use by docker, but from the point of view of rdiff-backup, it's an ext4 FS.

The docker images are not upgraded during the backup, so the files are not modified and they are all there from the first backup, and the warning starts appearing at least one month after backup was setup.

Is is possible to check the index (iterator cache) for a corruption? 

Unfortunatly, the last backup from the night didn't catch the exception, so no more information on what append.
I'll keep the -v9  option in my config file until it appends again.

I'll also ask the community as you suggest.

**Comment by ericzolf** [comment]
No news after almost 2 months, I close the issue, feel free to re-open if you get more information.
