### ISSUE TITLE
[BUG] Homebrew contains unreleased version 2.4.0 of rdiff-backup

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#944]
## Bug summary

I pushed wrongly v2.4.0, which got packaged by Homebrew and this now makes all other (older but actually current) versions on our homepage to look outdated.

## More information

Asked for [rollback of rdiff-backup 2.4.0 back to 2.2.6](https://github.com/orgs/Homebrew/discussions/4882)

**Comment by ericzolf** [comment]
If anybody has magic powers in Homebrew, please help!

**Comment by samford** [comment]
As mentioned in https://github.com/orgs/Homebrew/discussions/4882#discussioncomment-7887022, I've downgraded the `rdiff-backup` formula to version 2.2.6. Existing users on 2.4.0 will not be automatically downgraded to 2.2.6 and will need to manually run `brew reinstall rdiff-backup` to do so.

**Comment by ericzolf** [comment]
I'm repeating myself but thank you very much!
