### ISSUE TITLE
[ENH] make tox.ini only write to readable places with --current-env

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#949]
## What is it about?

When trying to add a `%check` option to RPM spec file, using the current `tox.ini` file it attempts to write to a directory that it does not have permission to do, i.e. `open("{envsitepackagesdir}/coverage.pth","w")`

## Version, Python, Operating System

Current github version, i.e. 2.4.1+

## rdiff-backup call

Adding the following to rdiff-backup RPM fails:

```
%check
%tox
```

Causes a failure on writing:

```
+ /usr/bin/python3 -m tox --current-env -q --recreate -e py311
rdiff-backup 2.4.1.dev14+gf27110de3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/coverage.pth'
py311: exit 1 (0.01 seconds) /builddir/build/BUILD/rdiff-backup-weekly> python -c 'with open("/usr/lib/python3.11/site-packages/coverage.pth","w") as fd: fd.write("import coverage; coverage.process_startup()\n")' pid=1235
  py311: FAIL code 1 (0.19 seconds)
  evaluation failed :( (0.21 seconds)
error: Bad exit status from /var/tmp/rpm-tmp.HDMejv (%check)
    Bad exit status from /var/tmp/rpm-tmp.HDMejv (%check)

```

The question is `tox.ini` suitable for use for an RPM `%check`, or what can be used, and should it be attempting to write to that directory?

**Comment by ericzolf** [comment]
I think that the issue is the `--current-env`. I was wondering about this option, but this seems to come from a plug-in, not tox itself: https://pypi.org/project/tox-current-env/

Without this option/plugin, `{envsitepackagesdir}` is within the virtualenv created by tox and hence writable. From me the look of it, it needs to be there and nowhere else:

```shell
# write the hook file which will make sure that coverage is loaded
# also for sub-processes, like for "client/server" rdiff-backup
python -c 'with open("{envsitepackagesdir}/coverage.pth","w") as fd: fd.write("import coverage; coverage.process_startup()\n")'
```

Ah, that sounds like the solution to your issue: https://pypi.org/project/coverage_pth/ resp. https://github.com/dougn/coverage_pth.

Quick and dirty:

```diff
$ git diff
diff --git a/tox.ini b/tox.ini
index 836bec4..8bdcaec 100644
--- a/tox.ini
+++ b/tox.ini
@@ -22,15 +22,15 @@ setenv =
 deps = -r{toxinidir}/requs/base.txt
        -r{toxinidir}/requs/optional.txt
        -r{toxinidir}/requs/test.txt
+# write the hook file which will make sure that coverage is loaded
+# also for sub-processes, like for "client/server" rdiff-backup
+       coverage_pth
 allowlist_externals = sh
 commands_pre =
        rdiff-backup --version
 # must be the first command to setup the test environment
        python testing/commontest.py
        coverage erase
-# write the hook file which will make sure that coverage is loaded
-# also for sub-processes, like for "client/server" rdiff-backup
-       python -c 'with open("{envsitepackagesdir}/coverage.pth","w") as fd: fd.write("import coverage; coverage.process_startup()\n")'
 commands =
        coverage run testing/action_backuprestore_test.py --verbose --buffer
        coverage run testing/action_calculate_test.py --verbose --buffer
```

Let me know if this fixes your issue. This should, but I fear that you'll choke then on `COVERAGE_FILE = {envlogdir}/coverage.sqlite`. I guess that it'll need replacement with `{envtmpdir}`, which should be everywhere writable by a normal user.

**Comment by ericzolf** [comment]
One more thing: it's perhaps obvious but `coverage_pth` can't become a solid dependency, as it would change the behaviour of any usage of coverage.

**Comment by ericzolf** [comment]
More difficult than expected, the coverage_pth package is bogus... OK, need to find an alternative.

**Comment by ericzolf** [comment]
OK, even more difficult, the plug-in docs state "Unlike regular tox invocation, this installs no dependencies declared in deps.", so I can fix all I want in deps, it won't help you... I start to think that we need a `tox_nocov.ini` for your use case.
