### ISSUE TITLE
What are the errors in statistics?

### ISSUE THREAD

**Issue by audouts** [rdiff-backup/rdiff-backup#968]
## What is it about?

In "Session statistics" I see "Errors 2" but no indication of what the errors are. How can I find out?

## Version, Python, Operating System

```
rdiff-backup info
Fatal Error: Switches missing or wrong number of arguments
See the rdiff-backup manual page for more information.
```

I'm using Debian 11, Python 3.9.2, rdiff-backup 2.0.5.

## rdiff-backup call

Here is my command, with paths/names removed.
```
rdiff-backup --no-acls --no-eas --ssh-no-compression -v 0 \
             --print-statistics \
             --exclude {path} \
              {source} {dest}
```

And what was the result?

```
--------------[ Session statistics ]--------------
[...]
IncrementFiles 27
IncrementFileSize 68422 (66.8 KB)
TotalDestinationSizeChange 3154098 (3.01 MB)
Errors 2
--------------------------------------------------
```

What are those two errors? I see the same error count every time.

**Comment by ericzolf** [comment]
It should be listed in the backup.log file in the repository. Probably two files which can't be properly backed-up. BTW your version of rdiff-backup is rather old, you might want to upgrade.

**Comment by audouts** [comment]
Thanks @ericzolf. I'll have a look.

I will also look at upgrading but this is on a Synology device with limited resources. As I recall, it was non-trivial to get rdiff-backup installed.

**Comment by ericzolf** [comment]
You're welcome. Please close the issue once you've fixed your problem.

**Comment by ericzolf** [comment]
No reaction after 3 weeks, I'm closing. Simply re-open if needed.
