### ISSUE TITLE
[ENH] Suppress output line-wrapping when using --parsable-output

### ISSUE THREAD

**Issue by dominicraf** [rdiff-backup/rdiff-backup#987]
Many (but maybe not all) of the informational output messages from `rdiff-backup` (v2.2.6) seem to assume a line width of 80 and break text on that basis. That may be pretty if you happen to have an 80-character-width output device but is untidy if you have something bigger, and makes script-based referencing of the output harder. Using `--parsable-output` does not seem to make any difference.

I have not noticed the same behaviour with other (Linux) utilities. I think `rdiff-backup` should assume an unlimited output line width and leave such prettifying for subsequent processing by the user or script (e.g. using `fold`).

My feeling is that this is a bug but if you prefer to regard it as an enhancement request, that's fine by me.

(Also, as shown below, a message appears *twice* saying 'Unable to import win32security module.' As this is a backup from Linux to Linux this is doubly superfluous.)

## Version, Python, Operating System

```
# rdiff-backup info
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - rdiff-backup
  - info
  parsed: null
  version: 2.2.6
python:
  executable: /opt/rdiff-backup-2.2/rdiff-backup
  name: cpython
  version: 3.7.17
system:
  fs_encoding: utf-8
  platform: Linux-5.15.0-94-generic-x86_64-with-debian-bookworm-sid
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup --api-version 201 --force --remote-schema "ssh -C %s rdiff-backup server" --terminal-verbosity 5 backup --create-full-path --exclude-device-files --exclude-globbing-filelist "/tmp/totimedicer.sh.exc" --exclude-other-filesystems --exclude-sockets --preserve-numerical-ids "/boot" "root@192.168.110.135::/home/root-dl1/boot"
```

## What happened and what did you expect?

Extract from output, showing broken lines:
```
  *        Unable to import win32security module. Windows ACLs not supported by
           filesystem at path
           /home/root-dl1/boot/rdiff-backup-data/rdiff-backup.tmp.0
  *        Writing mirror marker
           /home/root-dl1/boot/rdiff-backup-data/current_mirror.2024-02-28T08:00:01Z.data
  *        Cleaning up
  *        Executing remote command ssh -C root@192.168.110.135 rdiff-backup
           server
  *        API version agreed to be actual 201 with command b'ssh -C
           root@192.168.110.135 rdiff-backup server'
  *        Using repository '/home/root-dl1/boot'
  *        Unable to import win32security module. Windows ACLs not supported by
           filesystem at path /boot
  *        Could not determine if source directory /boot permits trailing spaces
           or periods in filenames because we can't find any files with trailing
           dot/period. It will be treated as permitting such files, but none will
           exist if it doesn't, so it doesn't really matter and is harmless
...
  NOTE:    Starting backup operation from source path /boot to destination path
           /home/root-dl1/boot
```

**Comment by ericzolf** [comment]
This is a bit a mixture of different things:

- the message about win32security is sent by the client _and_ the server processes, for different file systems, so this is normal and won't change (and it's at INFO level)
- the output shouldn't be folded at 80 characters but at whatever the width of your screen is, according to the docs of `shutil.get_terminal_size` the value of `$COLUMNS` so you could try to play with this.
- the logfile isn't folded so you could try to use it
- And, yes, `--parsable-output` could have more influence on the output, but this is as designed.

All this said, I'm happy to take this as an enhancement request.

**Comment by dominicraf** [comment]
1. Noted re the win32security message, I had not realised that both client and server send messages.
2. Thanks! Yes - setting COLUMNS works though it is a bit horrible, especially as it has to be set for both client and server separately viz: `COLUMNS=30000 rdiff-backup --api-version 201 --force --parsable-output --remote-schema "ssh -C %s COLUMNS=30000 rdiff-backup server" --terminal-verbosity 5 backup "/mnt/srcdir" "root@192.168.1.35::/destdir"`. I still think it would be better if output ignored COLUMNS altogether, but this is working ok for me now.
3. Thanks for suggesting use of `rdiff-backup-data/backup.log`, it is an alternative but to be honest I prefer to work with the immediate output.
4. I cannot see any difference when using `--parsable-output` but I now use it anyway.

**Comment by ericzolf** [comment]
Yeah, parsable output could encompass more, it's currently only used for comparaison and list actions.
