### ISSUE TITLE
[ENH] Efficient restore to a populated destination

### ISSUE THREAD

**Issue by matejak** [rdiff-backup/rdiff-backup#996]
## Is your feature request related to a problem? Please describe.

When restoring a directory that already exists, the process ends with an error:
```
ERROR:   Target path ... exists and isn't empty, call with '--force' to overwrite
ERROR:   Action restore failed on step check
```

This is unfortunate if one would like to e.g. use regular invocations of the `restore` command to maintain a directory that is up-to-date with a backup. Especially if the volume of data is huge, but that only a small amount of files change.

## Describe the solution you'd like

Don't end with an error. Also, the suggestion is to use `--force`, but it is not totally clear what that will do. Will it remove everything and then restore into an empty directory?
Instead: Go file by file, and if a file that we want to restore

-  exists (in the corresponding destination) and there is no such file in the backup, print a warning or something (possibly even delete it).
-  exists and is the same as the one from the backup, don't do anything.
-  exists and is different from the backup, transfer its contents over the network and recreate it.
-  doesn't exist, transfer its contents over the network and therefore create it.

## Describe alternatives you've considered

I see that issues #604 and  #797 are related, but I struggle to recognize their exact relation to my issue.

It also seems that backing up the backup files into the target destination would achieve the required effect, but that is a little bit crazy.

**Comment by ericzolf** [comment]
These are the same topics and the current behavior with `--force` is what you described. `--force` is required because, as you wrote, pre-existing files without backup would get erased. You can also avoid this by excluding them with the right `--exclude...` options. Closing.

**Comment by matejak** [comment]
Well, I have tried to use the `--force` option, and it seems to completely ignore existing files, overwriting them.
Here is the `-v5` output:
```
rdiff-backup --api-version 201 -v5 --force restore "backups::data/dbs" dbs
*        Executing remote command ssh -C backups rdiff-backup --terminal-verbosity 5 server
* Starting server                                     
*        API version agreed to be actual 201 with command b'ssh -C backups rdiff-backup --terminal-verbosity 5 server'
WARNING: Target path dbs exists and isn't empty, content might be force overwritten by restore
*        Unable to import win32security module. Windows ACLs not supported by
         filesystem at path data/dbs
*        Could not determine if source directory data/dbs
         permits trailing spaces or periods in filenames because we can't find
         any files with trailing dot/period. It will be treated as permitting
         such files, but none will exist if it doesn't, so it doesn't really
         matter and is harmless
--- Repository file system capabilities ---
-----------------------------------------------------------------
Detected abilities for read-only file system
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
*        Backup: escape_dos_devices = False
*        Backup: escape_trailing_spaces = False
*        Windows ACLs test skipped as rdiff-backup was started with --no-acls option
--- Write directory file system capabilities ---
-----------------------------------------------------------------
Detected abilities for read/write file system
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 N/A
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
*        Backup: escape_dos_devices = False
*        Backup: escape_trailing_spaces = False
*        Given repository doesn't need to be regressed
NOTE:    Starting restore operation from source path data/dbs to destination path dbs
WARNING: Extended Attributes file not found
*        Processing changed file .
*        Processing changed file dump_db.sql
*        Restore successfully finished
*        Cleaning up
*        Cleaning up
WARNING: Action restore emitted warnings, see previous messages for details
```
The file hasn't changed since the last restore (and there was no update on the side of the backed up data either), and observing the restore folder indicated that the file was indeed transferred in its entirety from the server.
Am I doing something wrongly? I can't figure out what the `WARNING: Extended Attributes file not found`, could it be related?

**Comment by matejak** [comment]
@ericzolf could you please check it out? I have found out that `rsync` may be better for restoring, so I don't think that this feature is essential, but if my observation is indeed correct, e.g. the documentation could be updated.

**Comment by ericzolf** [comment]
So:

```console
$ mkdir /tmp/from
$ dd if=/dev/random of=/tmp/from/A bs=1k count=64
$ ll /tmp/from/A
-rw-r--r--. 1 ericl ericl 65536 Apr  5 07:32 /tmp/from/A
$ rdiff-backup -v5 backup /tmp/from /tmp/bak
[...]
* Processing file .
* Processing file A
* Cleaning up
$ rdiff-backup -v5 --force restore /tmp/bak /tmp/from
[...]
* Processing changed file .
* Restore successfully finished
* Cleaning up
```

As you can see, the file A hasn't been restored as it hasn't been modified. On the other hand, if I modify any metadata (timestamp & Co) or the content, the file A is being restored. This said, no delta is applied, it's just a plain copy, hence indeed the whole file is copied. Where is it documented otherwise?

**Comment by matejak** [comment]
Thank you for the answer.

> ... On the other hand, if I modify any metadata (timestamp & Co) or the content, the file A is being restored. This said, no delta is applied, it's just a plain copy, hence indeed the whole file is copied. Where is it documented otherwise?

Nothing is documented clearly. However, I was referring to your answer

> ... These are the same topics and the current behavior with `--force` is what you described. ...

and I have described a more efficient approach.
Thank you for the clarification though. Would you agree that restoring to an already partially restored backup is most efficient with e.g. `rsync` by means of copying the plain files to the destination, as `rdiff-backup` is generally more likely to transfer data that are already present at the destination?

**Comment by ericzolf** [comment]
> Would you agree that restoring to an already partially restored backup is most efficient with e.g. `rsync` by means of copying the plain (latest) files to the destination, as `rdiff-backup` is generally more likely to transfer data that are already present at the destination?

No question, this is the main advantage of rdiff-backup that you can use normal means to restore the last version.

**Comment by ericzolf** [comment]
Oh, and the aspect of "delta" recovery is covered in #604
