### ISSUE TITLE
problem [Errno 11] Resource temporarily unavailable, when running backup 

### ISSUE THREAD

**Issue by dallday** [rdiff-backup/rdiff-backup#999]
## What is it about?
I'm running rdiff-backup on a raspberry pi and the source files are on a Linux Mint PC.
It has been working fine for a few years but a few days ago I started to get a failure message.
The backup seems to run for some time before failing.
I have attached the end part of the journal from the run 

What I need to know is what might be causing the error, is it on the Raspberry Pi or the Mint PC ?
Has an update to either the Pi or the linux Mint PC caused it to fail.
[logfile.txt](https://github.com/rdiff-backup/rdiff-backup/files/14999959/logfile.txt)

## Version, Python, Operating System
Raspberry Pi 
  Description:	Raspbian GNU/Linux 11 (bullseye)
  Release:	11
  Codename:	bullseye
Linux Mint PC
  Linux Mint 21.3
  Release:	21.3
  Codename:	virginia

Rdiff-backup Version 2.0.5 on both Pi and Mint PC
Pi - Python 3.9.2 
Mint PC - Python 3.10.12 

## rdiff-backup call

nice rdiff-backup --verbosity 8 --print-statistics --exclude-filelist /backup/config/davidexclude david_backup::/home/david /backupdrive/files/david/

I increased the verbosity level to see if any of the messages help.
the resulting error was 
Exception '[Errno 11] Resource temporarily unavailable' raised of class '<class 'BlockingIOError'>':

**Comment by ericzolf** [comment]
It's the first time this kind of error is reported so I'm not exactly sure where it can come from. Looking for other similar issues, I find https://bugs.python.org/issue43743 which lists a few impacted Linux kernels. I don't think that the attached patch has ever been applied, but apparently it's an issue only in specific kernels. In any cases, it doesn't sound like something which rdiff-backup can handle, it seems to be two layers down.
BTW rdiff-backup 2.0.5 is rather outdated, you should go with 2.2.6.

**Comment by ericzolf** [comment]
Searching further, it could be coming from the (SSH) connection getting issues, but same problem: nothing rdiff-backup has under control. Try perhaps to call rdiff-backup locally on each device, same file system, and see if you get the same issue, to limit the possibilities. fsck both file systems?

**Comment by dallday** [comment]
Thanks for the comments certainly gives me somewhere to start 
I have rerun the backup using --no-eas --no-acls 
e.g. 
nice rdiff-backup --no-eas --no-acls --verbosity 8 --print-statistics --exclude-filelist /backup/config/davidexclude david_backup::/home/david /backupdrive/files/david/

and that seems to have worked - was not sure exactly what I lost cause I  was not sure I had any special extended attributes, and the  

Still investigating

**Comment by ericzolf** [comment]
> I have rerun the backup using --no-eas --no-acls

Which file system do you have on the server side?

> and that seems to have worked - was not sure exactly what I lost cause I was not sure I had any special extended attributes, and the

SELinux typically is using extended attributes, but if you're not using it explicitly, the loss of those isn't a big deal (after a restore, I would anyway call `restorecon` to make sure the SELinux attributes aren't broken).

**Comment by dallday** [comment]
The server, where the rdiff-backup is running, backing up files from my PC, is a Raspberry Pi and the file systems are ext4 and the backup drive has 204g free ( it's a 1TB drive ), the remote client is my PC running Mint linux with ext4 file system. 

After doing some more runs I found the backup of user david folders works if I include the --no-eas option.
What I had not checked was other user folders and these are running as they were before.
Also a separate computer that is being backup in the same way is working fine.

It is suggesting that there is a problem with the extended attributes on my client pc ( using ext4 ) maybe caused by a recent update to the my system. But I don't think I have SELinux running on either system.

I tried verbose 9 level and boy does that give me loads of output 
Attached is the end of the failed run in case this gives any better idea 

[endoffailuedlogv9.txt](https://github.com/rdiff-backup/rdiff-backup/files/15039208/endoffailuedlogv9.txt)

**Comment by dallday** [comment]
Thanks for all the comments.
I am now running the backups without the extended attributes and all seems to be running well.
It would be nice to know what caused the issue 
it might be as suggested to do with the number of files which are being processed
```
SourceFiles 316118
SourceFileSize 373600890841 (348 GB)
```
and the ram size on the Pi 
```
free -h
               total        used        free      shared  buff/cache   available
Mem:           921Mi        70Mi       602Mi        15Mi       248Mi       771Mi
Swap:           99Mi        51Mi        48Mi
```
Not sure how I can tell if that was the issue but I can happily live without the extended attributes.
Thanks again
David
p.s. If you want to close the issue then feel free.

**Comment by ericzolf** [comment]
I feel free! 😏
